<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>Tourmaster Jacket Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'tourmaster/brand_logo.jpg' ?>" alt="Tourmaster" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'tourmaster/jersey.jpg' ?>" alt="Jacket Sizes" /> </div>
  <h1>Size Measurement</h1>
  <p>Sleeve: Measure from center of the spine at the base of the neck, around the shoulder,over the elbow and down to the wrist</p>
  <p>Chest: Measure around the broadest part of the chest 1-2 below the arm pits. </p>
  <p>Height: Measure how tall you are.</p>
  <div class='fox-gloves-table-header'>Jacket Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens</td>
      <td>XS</td>
      <td>S</td>
      <td>M</td>
      <td>L</td>
      <td>XL</td>
      <td>2XL</td>
      <td>3XL</td>
      <td>4XL</td>
    </tr>
    <tr>
      <td class="title3">CHEST SIZE</td>
      <td>38-40</td>
      <td>40-42</td>
      <td>42-44</td>
      <td>44-46</td>
      <td>46-48</td>
      <td>48-50</td>
      <td>50-52</td>
      <td>52-54</td>
    </tr>
    <tr>
      <td class="title3">SLEEVE</td>
      <td>24</td>
      <td>24.5</td>
      <td>25</td>
      <td>25.5</td>
      <td>26</td>
      <td>26.5</td>
      <td>27</td>
      <td>27.5</td>
    </tr>
    <tr>
      <td class="title3">HEIGHT</td>
      <td>5'7-5'9</td>
      <td>5'9-5'10</td>
      <td>5'10-5'11</td>
      <td>5'11-6</td>
      <td>6-6'1</td>
      <td>6'1-6'3</td>
      <td>6'3-6'4</td>
      <td>6'4-6'5</td>
    </tr>
  </table>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens Tall</td>
      <td>M</td>
      <td>L</td>
      <td>XL</td>
      <td>2XL</td>
      <td>3XL</td>
    </tr>
    <tr>
      <td class="title3">CHEST SIZE</td>
      <td>42-44</td>
      <td>44-46</td>
      <td>46-48</td>
      <td>48-50</td>
      <td>50-52</td>
    </tr>
    <tr>
      <td class="title3">SLEEVE</td>
      <td>27</td>
      <td>27.5</td>
      <td>28</td>
      <td>28.5</td>
      <td>29</td>
    </tr>
  </table>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Womens</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td class="title3">JACKET STD SIZE</td>
      <td class="title1">XS</td>
      <td class="title1">S</td>
      <td class="title1">M</td>
      <td class="title1">L</td>
      <td class="title1">XL</td>
    </tr>
    <tr>
      <td class="title3">CHEST SIZE</td>
      <td>32-34</td>
      <td>34-36</td>
      <td>36-39</td>
      <td>38-40</td>
      <td>40-42</td>
    </tr>
    <tr>
      <td class="title3">SLEEVE</td>
      <td>24</td>
      <td>24.5</td>
      <td>25</td>
      <td>25.5</td>
      <td>26</td>
    </tr>
    <tr>
      <td class="title3">HEIGHT</td>
      <td>5-5'1</td>
      <td>5'1-5'2</td>
      <td>5'2-5'3</td>
      <td>5'35'4</td>
      <td>5'4-5'5</td>
    </tr>
  </table>
  <div class='fox-gloves-table-header'>ADDITIONAL SIZING FOR WOMENS STREET JACKET</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td width="136" class="title2">Womens</td>
      <td width="38">&nbsp;</td>
      <td width="33">&nbsp;</td>
      <td width="43">&nbsp;</td>
    </tr>
    <tr>
      <td class="title3">JACKET PLUS SIZE</td>
      <td class="title1">S</td>
      <td class="title1">M</td>
      <td class="title1">L</td>
    </tr>
    <tr>
      <td class="title3">CHEST SIZE</td>
      <td>38-42</td>
      <td>42-46</td>
      <td>46-50</td>
    </tr>
    <tr>
      <td class="title3">SLEEVE</td>
      <td>24.5</td>
      <td>25</td>
      <td>25.5</td>
    </tr>
  </table>
  <table class="sizing_chart">
    <tr class="title1">
      <td width="136" class="title2">Womens</td>
      <td width="38">&nbsp;</td>
      <td width="33">&nbsp;</td>
      <td width="43">&nbsp;</td>
    </tr>
    <tr>
      <td class="title3">JACKET TALL SIZE</td>
      <td class="title1">S</td>
      <td class="title1">M</td>
      <td class="title1">L</td>
    </tr>
    <tr>
      <td class="title3">CHEST SIZE</td>
      <td>34-36</td>
      <td>36-38</td>
      <td>38-40</td>
    </tr>
    <tr>
      <td class="title3">SLEEVE</td>
      <td>26.5</td>
      <td>27</td>
      <td>27.5</td>
    </tr>
  </table>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
