<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>Tourmaster Pant Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'tourmaster/brand_logo.jpg' ?>" alt="Tourmaster" /></div>
  <div style="text-align:center;"><img src="<?php echo $baseMediaUrl . 'tourmaster/pants.jpg' ?>" alt="Pant Sizes" /></div>
  <h1>Size Measurement</h1>
  <p>Waist: Measure about 1 inch below top of pelvic bone.</p>
  <p> Inseam: Measure down from the crotch to the top of the ankle bone.</p>
<div class='fox-gloves-table-header'>Pant Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td class="title3">PANT STD SIZE</td>
      <td class="title1">XS</td>
      <td class="title1">S</td>
      <td class="title1">M</td>
      <td class="title1">L</td>
      <td class="title1">XL</td>
      <td class="title1">2XL</td>
      <td class="title1">3XL</td>
      <td class="title1">4XL</td>
    </tr>
    <tr>
      <td class="title3">WAIST SIZE</td>
      <td>28-30</td>
      <td>30-32</td>
      <td>32-34</td>
      <td>34-36</td>
      <td>36-38</td>
      <td>38-40</td>
      <td>40-42</td>
      <td>42-44</td>
    </tr>
    <tr>
      <td class="title3">INSEAM SIZE</td>
      <td>30.5</td>
      <td>31</td>
      <td>31.5</td>
      <td>32</td>
      <td>32.5</td>
      <td>33</td>
      <td>33</td>
      <td>33</td>
    </tr>
    <tr>
      <td class="title3">HEIGHT</td>
      <td>5'7-5'9</td>
      <td>5'9-5'10</td>
      <td>5'10-5'11</td>
      <td>5'11-6</td>
      <td>6-6'1</td>
      <td>6'1-6'3</td>
      <td>6'3-6'4</td>
      <td>6'4-6'5</td>
    </tr>
  </table>
  <table class="sizing_chart">
    <tr class="title1">
      <td width="119" class="title2">Mens</td>
      <td width="38">&nbsp;</td>
      <td width="41">&nbsp;</td>
      <td width="47">&nbsp;</td>
      <td width="44">&nbsp;</td>
      <td width="44">&nbsp;</td>
      <td width="44">&nbsp;</td>
    </tr>
    <tr>
      <td class="title3">PANT TALL SIZE</td>
      <td class="title1">M</td>
      <td class="title1">L</td>
      <td class="title1">XL</td>
      <td class="title1">2XL</td>
      <td class="title1">3XL</td>
      <td class="title1">4XL</td>
    </tr>
    <tr>
      <td class="title3">WAIST SIZE</td>
      <td>32-34</td>
      <td>34-36</td>
      <td>36-38</td>
      <td>38-40</td>
      <td>40-42</td>
      <td>42-44</td>
    </tr>
    <tr>
      <td class="title3">INSEAM SIZE</td>
      <td>33.5</td>
      <td>34</td>
      <td>34.5</td>
      <td>35</td>
      <td>35</td>
      <td>35</td>
    </tr>
    <tr>
      <td class="title3">HEIGHT</td>
      <td>6-6'1</td>
      <td>6'1-6'2</td>
      <td>6'2-6'3</td>
      <td>6'3-6'4</td>
      <td>6'4-6'5</td>
      <td>6'5-6'6</td>
    </tr>
  </table>
  <table class="sizing_chart">
    <tr class="title1">
      <td width="119" class="title2">Mens</td>
      <td width="38">&nbsp;</td>
      <td width="41">&nbsp;</td>
      <td width="47">&nbsp;</td>
      <td width="44">&nbsp;</td>
      <td width="44">&nbsp;</td>
      <td width="44">&nbsp;</td>
    </tr>
    <tr>
      <td class="title3">PANT SHORT SIZE</td>
      <td class="title1">M</td>
      <td class="title1">L</td>
      <td class="title1">XL</td>
      <td class="title1">2XL</td>
      <td class="title1">3XL</td>
      <td class="title1">4XL</td>
    </tr>
    <tr>
      <td class="title3">WAIST SIZE</td>
      <td>32-34</td>
      <td>34-36</td>
      <td>36-38</td>
      <td>38-40</td>
      <td>40-42</td>
      <td>42-44</td>
    </tr>
    <tr>
      <td class="title3">INSEAM SIZE</td>
      <td>29.5</td>
      <td>30</td>
      <td>30.5</td>
      <td>31</td>
      <td>31</td>
      <td>31</td>
    </tr>
    <tr>
      <td class="title3">HEIGHT</td>
      <td>5'7-5'8</td>
      <td>5'8-5'9</td>
      <td>5'9-5'10</td>
      <td>5'10-5'11</td>
      <td>5'11-6</td>
      <td>6-6'1</td>
    </tr>
  </table>

  <table class="sizing_chart">
    <tr class="title1">
      <td width="136" class="title2">Womens</td>
      <td width="38">&nbsp;</td>
      <td width="33">&nbsp;</td>
      <td width="43">&nbsp;</td>
      <td width="43">&nbsp;</td>
      <td width="43">&nbsp;</td>
    </tr>
    <tr>
      <td class="title3">PANT STD SIZE</td>
      <td class="title1">XS</td>
      <td class="title1">S</td>
      <td class="title1">M</td>
      <td class="title1">L</td>
      <td class="title1">XL</td>
    </tr>
    <tr>
      <td class="title3">CHEST SIZE</td>
      <td>28-30</td>
      <td>30-32</td>
      <td>32-34</td>
      <td>34-36</td>
      <td>36-38</td>
    </tr>
    <tr>
      <td class="title3">SLEEVE</td>
      <td>30</td>
      <td>30.5</td>
      <td>31</td>
      <td>31.5</td>
      <td>32</td>
    </tr>
  </table>
  <table class="sizing_chart">
    <tr class="title1">
      <td width="136" class="title2">Womens</td>
      <td width="38">&nbsp;</td>
      <td width="33">&nbsp;</td>
      <td width="43">&nbsp;</td>
    </tr>
    <tr>
      <td class="title3">PANT TALL SIZE</td>
      <td class="title1">S</td>
      <td class="title1">M</td>
      <td class="title1">L</td>
    </tr>
    <tr>
      <td class="title3">CHEST SIZE</td>
      <td>30-32</td>
      <td>32-34</td>
      <td>34-36</td>
    </tr>
    <tr>
      <td class="title3">SLEEVE</td>
      <td>32.5</td>
      <td>33</td>
      <td>33.5</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
