<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Amasty_Rma
 */
?>
<div class="account-login">
    <div class="page-title">
        <h1><?php echo $this->__('Request RMA') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <form method="post" action="<?php print $this->getLoginPostUrl(); ?>" id="rma-login-form">
        <div class="col2-set">
            <div class="registered-users">
                <div class="content">                    
                    <p><?php echo $this->__('Please enter your email address and order #') ?>.</p>
                    <ul class="form-list">
                        <li>
                            <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                            <div class="input-box">
                                <input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                            </div>
                        </li>
                        <li>
                            <label for="pass" class="required"><em>*</em><?php echo $this->__('Order #') ?></label>
                            <div class="input-box">
                                <input type="text" name="login[order]" class="input-text required-entry" id="pass" title="<?php echo $this->__('Order #') ?>" />
                            </div>
                        </li>
                    </ul>
                    <div class="buttons-set2">
                        <button type="submit" class="button large" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                    </div>
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                </div>

            </div>
        </div>        
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
        //]]>
    </script>
</div>
