<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'answer'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Answer Offroad Men's and Women's Pants Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="Answer" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/pants.jpg' ?>" alt="Pants Sizes" />
	</div>

	<h1>WAIST</h1>

	<p>Measure about 1 inch below top of pelvic bone.</p>
	
	<h1>INSEAM</h1>

	<p>Measure down from the crotch to the top of the ankle bone.</p>

	<div class='fox-gloves-table-header'>Pants Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">PANT SIZE</td>
			<td>32</td>
			<td>34</td>
			<td>36</td>
			<td>38</td>
			<td>40</td>
			<td>42</td>
			<td>44</td>
			<td>46</td>
			<td>48</td>
			<td>50</td>
			<td>52</td>
			<td>54</td>
		</tr>
		<tr>
			<td class="title3">WAIST SIZE</td>
			<td>26-28</td>
			<td>28-29</td>
			<td>29-31</td>
			<td>31-33</td>
			<td>33-34</td>
			<td>34-36</td>
			<td>36-37</td>
			<td>37-39</td>
			<td>39-41</td>
			<td>41-42</td>
			<td>42-44</td>
			<td>44-45</td>
		</tr>
		<tr>
			<td class="title3">INSEAM SIZE</td>
			<td>28-29</td>
			<td>29-29 7/8</td>
			<td>30-30 3/4</td>
			<td>31-31 1/2</td>
			<td>31-32 1/4</td>
			<td>32-33 1/4</td>
			<td>33 1/2-33 7/8</td>
			<td>34 1/4-35</td>
			<td>35-35 3/8</td>
			<td>35-35 7/8</td>
			<td>35 7/8-36</td>
			<td>35 7/8-36 1/4</td>
		</tr>
	</table>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">WOMEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">PANT SIZE</td>
			<td>0</td>
			<td>2</td>
			<td>4</td>
			<td>6</td>
			<td>8</td>
			<td>10</td>
			<td>12</td>
			<td>14</td>
			<td>16</td>
			<td>18</td>
		</tr>
		<tr>
			<td class="title3">WAIST SIZE</td>
			<td>22-24</td>
			<td>24-26</td>
			<td>26-27</td>
			<td>27-29</td>
			<td>29-30</td>
			<td>30-32</td>
			<td>32-33</td>
			<td>33-35</td>
			<td>35-37</td>
			<td>37-38</td>
		</tr>
		<tr>
			<td class="title3">INSEAM SIZE</td>
			<td>28 3/8-28 3/4</td>
			<td>29 1/8-29 1/2</td>
			<td>29 7/8-30 3/8</td>
			<td>30 3/4-31 1/8</td>
			<td>31 1/2-32 5/8</td>
			<td>33 1/8-33 1/2</td>
			<td>33 1/8-33 1/2</td>
			<td>33 1/8-33 1/2</td>
			<td>33 78/-34 1/4</td>
			<td>33 7/8-34 1/4</td>
		</tr>
	</table>
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>