<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'alpinestars'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Alpinestars Casual Pants Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="Alpinestars" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/pants.jpg' ?>" alt="Pants Sizes" />
	</div>

	<h1>WAIST</h1>

	<p>Measure about 1 inch below top of pelvic bone.</p>
	
	<h1>INSEAM</h1>

	<p>Measure down from the crotch to the top of the ankle bone.</p>

	<div class='fox-gloves-table-header'>Pants Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">PANTS SIZE</td>
			<td>26</td>
			<td>28</td>
			<td>30</td>
			<td>32</td>
			<td>34</td>
			<td>36</td>
			<td>38</td>
			<td>40</td>
			<td>42</td>
			<td>44</td>
			<td>46</td>
			<td>48</td>
		</tr>
		<tr>
			<td class="title3">WAIST</td>
			<td>26 1/2-28</td>
			<td>28 1/2-30</td>
			<td>30 1/2-32</td>
			<td>32 1/2-34</td>
			<td>34 1/2-36</td>
			<td>36 1/2-38</td>
			<td>38 1/2-40</td>
			<td>40 1/2-42</td>
			<td>42 1/2-44</td>
			<td>44 1/2-46</td>
			<td>46 1/2-48</td>
			<td>48 1/2-50</td>
		</tr>
		<tr>
			<td class="title3">INSEAM</td>
			<td>32</td>
			<td>36</td>
			<td>38 1/2</td>
			<td>39</td>
			<td>40</td>
			<td>41</td>
			<td>41 1/2</td>
			<td>42</td>
			<td>42 1/2</td>
			<td>42 1/2</td>
			<td>43</td>
			<td>43</td>
		</tr>
	</table>
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>