<?php
$productID = Mage::getSingleton('checkout/session')->getLastAddedProductId(true);

if ($productID) :

    $catid = Mage::app()->getRequest()->getParam('catid');
    $category = Mage::getModel('catalog/category')->load($catid);

    $_product = Mage::getModel('catalog/product')->load($productID);

    $_productItem = null;
    $_productItems = array();

    $groupedProductsAssociatedIds = array();

    if ($_product->getTypeId() === 'grouped') :
        $associatedProducts = $_product->getTypeInstance(true)->getAssociatedProducts($_product);

        foreach ($associatedProducts as $_aitem) {
            array_push($groupedProductsAssociatedIds, $_aitem->getId());
        }
    endif;

    $session = Mage::getSingleton('checkout/session');
    foreach ($session->getQuote()->getAllItems() as $item) {

        if ($_product->getTypeId() === 'grouped') {
            if (in_array($item->getProductId(), $groupedProductsAssociatedIds)) {
                array_push($_productItems, $item);
            }
        } else {
            if ($productID == $item->getProductId()) {
                $_productItem = $item;
                break;
            }
        }

//    
//    $productID = $item->getProductId();
//    $productSku = $item->getSku();
//    $productName = $item->getName();
//    $productQty = $item->getQty();
//    echo $productID . "|" . $productSku . "|" . $productName . "|" . $productQty . "|" . $item->getPrice() . "<br>";
    }

//$catCollection = $_product->getCategoryCollection();
//foreach ($catCollection as $cat) {        
//    echo $cat->getUrl() . "<br/>";
//}
    ?>

    <div class="close-floating-cart-wrap"><a href="#" onclick="popupcart.hide(event);" class="close-floating-cart">x</a></div>
    <div class="block-floating-cart-wrap">
        <div class="floating-cart">            
            <?php /* <div class="continue-shopping"><a href="<?php echo $catid == 2 ? '#' : $category->getUrl($category); ?>" onclick="<?php echo $catid == 2 ? 'popupcart.hide(event)' : ''; ?>;" class="continue-shopping-link">Continue Shopping</a></div> */ ?>
            <div class="continue-shopping"><a href="#" onclick="popupcart.hide(event);" class="continue-shopping-link">Continue Shopping</a></div>
            <div class="product-brand-name">
                <?php if ($_product->getAttributeText('ari_brands')): ?>
                    <div class="product-brand">
                        <?php $_filename = Mage::getBaseDir() . "/media/catalog/product/brands/" . str_replace(' ', '-', strtolower($_product->getAttributeText('ari_brands'))) . ".jpg"; ?>
                        <?php $filename = Mage::getBaseUrl('media') . "catalog/product/brands/" . str_replace(' ', '-', strtolower($_product->getAttributeText('ari_brands'))) . ".jpg"; ?>
                        <?php if (file_exists($_filename)): ?>                    
                            <img src="<?php echo $filename; ?>" width="130" alt="<?php echo $_product->getAttributeText('ari_brands'); ?>" />                    
                        <?php else: ?>                    
                            <?php echo $_product->getAttributeText('ari_brands'); ?>                    
                        <?php endif; ?>
                    </div>
                <?php endif; ?>


                <?php if ($_product->getTypeId() === 'grouped') : ?>                
                    <?php foreach ($_productItems as $_productItem): ?>
                        <div class="product-name"><?php echo $_productItem->getName(); ?>&nbsp;<a title="Remove this item from the cart" class="remove-item" onclick="popupcart.removeFromCart(event, this)" href="<?php echo $this->getUrl('ajaxcheckout/cart/delete', array('id' => $_productItem->getId())); ?>">X</a></div>                       
                    <?php endforeach; ?>
                <?php else: ?>
                    <div class="product-name"><?php echo $_product->getName(); ?>&nbsp;<a title="Remove this item from the cart" class="remove-item" onclick="popupcart.removeFromCart(event, this)" href="<?php echo $this->getUrl('ajaxcheckout/cart/delete', array('id' => $_productItem->getId())); ?>">X</a></div>           
                <?php endif; ?>            
                <div class="crystal"></div>
            </div>

            <div class="product-cart-image-wrap">
                <div class="product-cart-image">
                    <?php if ($_product->getTypeId() !== 'grouped') : ?>
                        <?php
                        $_item = $_productItem->getProduct();
                        $simpleProduct = Mage::getModel('catalog/product')->loadByAttribute('sku', $_item->getSku());
                        ?>
                        <img src="<?php echo $this->helper('catalog/image')->init($simpleProduct, 'small_image')->resize(220); ?>" width="220" height="220" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />                                
                    <?php else: ?>                    
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(220); ?>" width="220" height="220" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />                                                    
                    <?php endif; ?>
                </div>
                <div class="product-attributes">
                    <div class="cart-product-attributes product-attributes-sku">
                        <span class="product-attribute-title">SKU #:&nbsp;</span><span class="product-attribute-value"><?php echo $_product->getSku(); ?></span>                   
                    </div>
                    <?php if ($_product->getTypeId() !== 'grouped') : ?>
                        <?php echo $this->getItemHtml($_productItem) ?>
                    <?php endif; ?>
                </div>
            </div>
            <div class="product-cart-details">
                <table class="product-details-tbl">
                    <?php if ($_product->getTypeId() === 'grouped') : ?>
                        <tr class="product-details-row product-details-row-price">
                            <td class="product-details-name">
                                <div class="product-details-price-label" style="display: none;">Price</div>
                                <table class="product-details-price-table-name">                                
                                    <?php $totalQty = 0; ?>
                                    <?php $subTotalAmount = 0; ?>
                                    <?php foreach ($_productItems as $_productItem): ?>
                                        <?php $totalQty += $_productItem->getQty(); ?>
                                        <?php $subTotalAmount += ($_productItem->getQty() * $_productItem->getPrice()); ?>
                                        <tr>
                                            <td><?php echo $_productItem->getName() . " ({$_productItem->getQty()})"; ?>&nbsp;<a title="Remove this item from the cart" class="remove-item" onclick="popupcart.removeFromCart(event, this)" href="<?php echo $this->getUrl('ajaxcheckout/cart/delete', array('id' => $_productItem->getId())); ?>">X</a></td>
                                        </tr>
                                    <?php endforeach; ?>
                                </table>
                            </td>
                            <td class="product-details-value">
                                <table  class="product-details-price-table-price">
                                    <?php foreach ($_productItems as $_productItem): ?>
                                        <tr>
                                            <td><?php echo Mage::helper('core')->currency(($_productItem->getPrice() * $_productItem->getQty()), true, false); ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                </table>
                            </td>
                            <td>&nbsp;</td>
                        </tr>
                    <?php else: ?>
                        <tr class="product-details-row product-details-row-price">
                            <td class="product-details-name">
                                Price
                            </td>
                            <td class="product-details-value">                            
                                <?php echo Mage::helper('core')->currency($_productItem->getPrice(), true, false); ?>                            
                            </td>
                            <td>&nbsp;</td>
                        </tr>
                    <?php endif; ?>                
                    <tr class="product-details-row product-details-row-subtotal">
                        <td class="product-details-name">Subtotal 
                            <?php if ($_product->getTypeId() === 'grouped') : ?>
                                <span class="item-qty">(<?php echo $totalQty; ?>&nbsp;Item)</span>
                            <?php else: ?>
                                <span class="item-qty">(<?php echo $_productItem->getQty(); ?>&nbsp;Item)</span>                            
                            <?php endif; ?>
                        </td>
                        <td colspan="2"><?php echo $_product->getTypeId() === 'grouped' ? Mage::helper('core')->currency($subTotalAmount, true, false) : Mage::helper('core')->currency($_productItem->getPrice() * $_productItem->getQty(), true, false); ?></td>                    
                    </tr>
                </table>
                <div class="product-cart-controls">
                    <button type="button" class="view-cart-btn" onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getCartUrl(); ?>')"><span><span>View Cart</span></span></button>
                    <?php //if ($_cartQty && $this->isPossibleOnepageCheckout()):   ?>                    
                    <button type="button" class="checkout-cart-btn" title="<?php echo $this->__('Checkout') ?>" class="button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button>                    
                    <?php //endif   ?>                     
                </div>
            </div>
            <div class="crystal"></div>
            <?php /* $related_products = $_product->getRelatedProductCollection();
              $related_products->AddStoreFilter();
              ?>
              <?php if (count($related_products) > 0): ?>
              <div class="product-related-items-accessories">
              <h2>Related Items and Accessories</h2>
              <ul class="product-related-items-list">
              <?php foreach ($related_products as $_prod): ?>
              <li></li>
              <?php endforeach; ?>
              </ul>
              </div>
              <?php endif; */ ?>

            <hr class="floatingcart-hr"/>
        </div>
    </div>
<?php endif; ?>       