<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'honda'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Honda Jacket Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.gif' ?>" alt="Honda" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/jersey.jpg' ?>" alt="Jacket Sizes" />
	</div>
	
	<h1>Sleeve</h1>

	<p>Measure from the center of spine at the base of the neck, around the shoulder, over the elbow and down to the wrist.</p>
	
	<h1>Chest</h1>

	<p>Measure around the broadest part of the chest, 1-2  inches below the arm pits.</p>

	<div class='fox-gloves-table-header'>Jacket Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">JACKET SIZE</td>
			<td>XS</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
			<td>3XL</td>
			<td>4XL</td>
			<td>5XL</td>
			<td>LT</td>
			<td>XLT</td>
			<td>2XLT</td>
		</tr>
		<tr>
			<td class="title3">CHEST SIZE</td>
			<td>36</td>
			<td>38</td>
			<td>40</td>
			<td>43</td>
			<td>46</td>
			<td>50</td>
			<td>53</td>
			<td>56</td>
			<td>59</td>
			<td>44</td>
			<td>47</td>
			<td>50</td>
		</tr>
		<tr>
			<td class="title3">SLEEVE LENGTH</td>
			<td>31.5</td>
			<td>32.5</td>
			<td>33.5</td>
			<td>34.5</td>
			<td>35.5</td>
			<td>36.5</td>
			<td>37.5</td>
			<td>38.5</td>
			<td>39.5</td>
			<td>36.5</td>
			<td>37.5</td>
			<td>38.5</td>
		</tr>
	</table>	
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit.</p>

</div>