<div class="tireshop-content">

	<h3 class="rlabel">UTV tire measurements:<span></span></h3>
	<p>Whether on the track, in the woods or in the desert traction is a concern. Choosing the right size and compound for the type of terrain you’ll be in will give you the traction your UTV needs.</p>
	<p>UTV Tires are normally measured in Inches by Height, Width & Rim Diameter. Please see the example below for assist or give one of our TMS Parts Specialist a call at 877-698-4123 or try our Live Chat for speedy service.</p>
	<div class="dimensions-street dimensions">
		<div class="dimensions-tips">
			<div class="dimensions-tips-header">Tubeless</div>
			<dl>
				<dt>Tread:<dt>
				<dd>4 Plies Nylon</dd>
				<dt>Sidewall:<dt>
				<dd>2 Plies Nylon</dd>
			</dl>
		</div>
		<div class="dimensions-graphic dirt-measurement">
			<img src="/skin/frontend/default/temecula/vk_fitment/images/tireshop/content/measurements/utv.jpg" alt="Tire Measurements" />
		</div>			
	</div>
	<ul class="dimensions-sizes">
		<li>
			<div class="dimensions-sizes-title">Width:</div>
			<div class="dimensions-sizes-value">190</div>
		</li>
		<li>
			<div class="dimensions-sizes-title">Aspect Ratio:</div>
			<div class="dimensions-sizes-value">50</div>
		</li>
		<li>
			<div class="dimensions-sizes-title">Rim Diameter:</div>
			<div class="dimensions-sizes-value">17&quot;</div>
		</li>
		<li class="dimensions-sizes-total">190/50X17</li>
	</ul>

	<h3 class="rlabel">Terms definitions:<span></span></h3>
	<dl class="terms-definitions">
		<dt>Width</dt>
		<dd>The first number or second letter in a tire size represents the nominal width. Width is measured in a straight line from the furthest point on one sidewall, across the tread, to the furthest point on the opposite sidewall. If there is any question whether or not a larger than OEM tire will fit your bike, you're encouraged to <strong>our TMS Parts Specialist<strong>. The different size numbering systems specify widths in different measurements.</dd>

		<dt>Aspect Ratio</dt>
		<dd>Aspect Ratios indicate a tires cross-sectional profile. The smaller the number, the lower the profile. It expresses the height to width ratio as a percent. A 90 aspect ratio means the tire's cross sectional height is 90% of it's width. The aspect ratio appears immediately after the width in the Metric, Alpha and Low Profile Inch numbering systems.</dd>

		<dt>Rim Diameter</dt>
		<dd>Rim diameter is the diameter of the rim/wheel on which the tire will be mounted, in inches.</dd>

		<dt>Speed Rating</dt>
		<dd>Speed Ratings are internationally recognized maximum speeds at which the tire may be used with maximum load when the maximum listed inflation pressure is used. Maximum loads and inflation pressures are found on the sidewalls of the tires. Speed ratings are coded by a letter, which appears directly after the width, aspect ratio, or as part of a three digit Load/Speed Index, found on the tire directly after the complete size designation.
			<table class="speedRating-chart">
				<thead>
					<tr>	<td>SS</td>		<td>Km/h</td>	<td>Mph</td>	</tr>
				</thead>
				<tbody>
					<tr>	<th>F</th>		<td>80</td>		<td>50</td>		</tr>
					<tr>	<th>J</th>		<td>100</td>	<td>62</td>		</tr>
					<tr>	<th>L</th>		<td>120</td>	<td>75</td>		</tr>
					<tr>	<th>M</th>		<td>130</td>	<td>81</td>		</tr>
					<tr>	<th>N</th>		<td>140</td>	<td>87</td>		</tr>
					<tr>	<th>P</th>		<td>150</td>	<td>94</td>		</tr>
					<tr>	<th>R</th>		<td>170</td>	<td>106</td>	</tr>
					<tr>	<th>S</th>		<td>180</td>	<td>112</td>	</tr>
					<tr>	<th>H</th>		<td>210</td>	<td>130</td>	</tr>
					<tr>	<th>V</th>		<td>240</td>	<td>149</td>	</tr>
					<tr>	<th>Z</th>		<td>240+</td>	<td>149+</td>	</tr>
					<tr>	<th>W</th>		<td>270</td>	<td>168</td>	</tr>
					<tr>	<th>(W)</th>	<td>270+</td>	<td>168+</td>	</tr>
				</tbody>
			</table>
		</dd>

		<dt>Tire Construction</dt>
		<dd>
			The Tire Construction, when included in the size numbering, is listed after the speed rating. The two options for tire construction are Belted (B) or Radial (R). A belted tire has fiberglass, Kevlar, or aramid fiber belts for added strength and load capacity, however not all belted tires will have the B designation. If a tire does not have the Radial (R) designation, it is a bias-ply tire.
			<div class="tireConstruction-utv tireConstruction">
				<div class="tireConstruction-popup-radial tireConstruction-popup">
					<div class="tireConstruction-popup-title">Radial</div>
					Radial constructed tires utilize both ply and breaker (or belt) cords. The Ply cords extend from bead to bead at approximately 90 degree angle to the centerline of the tire. The breaker (or belt) cords are placed on top of the ply cords across the width of the tire. 
Advantages: Adding breaker (or belt) cords results in a stiffer carcass which helps provide a longer tread and tire life, better steering control and handling, overall smoother ride and ride comfort, and higher tread puncture resistance.
				</div>
				<div class="tireConstruction-popup-belted tireConstruction-popup">
					<div class="tireConstruction-popup-title">Bias (&quot;B&quot;)</div>
Bias tires typically have the ply cords that extend diagonally from bead to bead at a range of 30 to 60 degree angles from the centerline. Each successive ply is laid at an opposing angle, forming a kriss-cross pattern. 
Advantages: The design allows the entire tire body to flex easily, giving a comfortable ride on rough surfaces.
				</div>
				<div class="tireConstruction-popup-biasPly tireConstruction-popup">
					<div class="tireConstruction-popup-title">Ply-Rating</div>
					ATV tires come in several different ply ratings. 2-Ply Rating, 4-Ply Rating, 6-Ply Rating, 8-Ply Rating etc. The higher the ply rating the stronger the tire is. But also remember the tire will be heavier. 
				</div>
			</div>
		</dd>

		<dt>Load Rating</dt>
		<dd>The load rating is found after the tire size. This number represents the tire's load carrying maximum capacity at maximum air pressure.
			<div class="loadRating-container clearer">
				<table class="loadRating-chart">
					<thead>
						<tr>	<td>LI</td>	<td>KGS</td>	<td>LBS</td>	</tr>
					</thead>
					<tbody>
						<tr>	<th>21</th>	<td>82.5</td>	<td>182</td>	</tr>
						<tr>	<th>22</th>	<td>85 </td>	<td>187</td>	</tr>
						<tr>	<th>23</th>	<td>87.5</td>	<td>193</td>	</tr>
						<tr>	<th>24</th>	<td>90 </td>	<td>198</td>	</tr>
						<tr>	<th>25</th>	<td>92.5</td>	<td>204</td>	</tr>
						<tr>	<th>26</th>	<td>95 </td>	<td>209</td>	</tr>
						<tr>	<th>27</th>	<td>97.5</td>	<td>215</td>	</tr>
						<tr>	<th>28</th>	<td>100</td>	<td>220</td>	</tr>
						<tr>	<th>29</th>	<td>103</td>	<td>227</td>	</tr>
						<tr>	<th>30</th>	<td>106</td>	<td>234</td>	</tr>
						<tr>	<th>31</th>	<td>109</td>	<td>240</td>	</tr>
						<tr>	<th>32</th>	<td>112</td>	<td>247</td>	</tr>
						<tr>	<th>33</th>	<td>115</td>	<td>254</td>	</tr>
						<tr>	<th>34</th>	<td>118</td>	<td>260</td>	</tr>
						<tr>	<th>35</th>	<td>121</td>	<td>267</td>	</tr>
						<tr>	<th>36</th>	<td>125</td>	<td>276</td>	</tr>
						<tr>	<th>37</th>	<td>128</td>	<td>282</td>	</tr>
						<tr>	<th>38</th>	<td>132</td>	<td>291</td>	</tr>
						<tr>	<th>39</th>	<td>136</td>	<td>300</td>	</tr>
						<tr>	<th>40</th>	<td>140</td>	<td>309</td>	</tr>
						<tr>	<th>41</th>	<td>145</td>	<td>320</td>	</tr>
						<tr>	<th>42</th>	<td>150</td>	<td>331</td>	</tr>
						<tr>	<th>43</th>	<td>155</td>	<td>342</td>	</tr>
						<tr>	<th>44</th>	<td>160</td>	<td>353</td>	</tr>
						<tr>	<th>45</th>	<td>165</td>	<td>364</td>	</tr>
						<tr>	<th>46</th>	<td>170</td>	<td>375</td>	</tr>
						<tr>	<th>47</th>	<td>175</td>	<td>386</td>	</tr>
						<tr>	<th>48</th>	<td>180</td>	<td>397</td>	</tr>
						<tr>	<th>49</th>	<td>185</td>	<td>408</td>	</tr>
						<tr>	<th>50</th>	<td>190</td>	<td>419</td>	</tr>
					</tbody>
				</table>

				<table class="loadRating-chart">
					<thead>
						<tr>	<td>LI</td>	<td>KGS</td>	<td>LBS</td>	</tr>
					</thead>
					<tbody>
						<tr>	<th>51</th>	<td>195</td>	<td>430</td>	</tr>
						<tr>	<th>52</th>	<td>200</td>	<td>441</td>	</tr>
						<tr>	<th>53</th>	<td>206</td>	<td>454</td>	</tr>
						<tr>	<th>54</th>	<td>212</td>	<td>467</td>	</tr>
						<tr>	<th>55</th>	<td>218</td>	<td>481</td>	</tr>
						<tr>	<th>56</th>	<td>224</td>	<td>494</td>	</tr>
						<tr>	<th>57</th>	<td>230</td>	<td>507</td>	</tr>
						<tr>	<th>58</th>	<td>236</td>	<td>520</td>	</tr>
						<tr>	<th>59</th>	<td>243</td>	<td>536</td>	</tr>
						<tr>	<th>60</th>	<td>250</td>	<td>551</td>	</tr>
						<tr>	<th>61</th>	<td>257</td>	<td>567</td>	</tr>
						<tr>	<th>62</th>	<td>265</td>	<td>584</td>	</tr>
						<tr>	<th>63</th>	<td>272</td>	<td>600</td>	</tr>
						<tr>	<th>64</th>	<td>280</td>	<td>617</td>	</tr>
						<tr>	<th>65</th>	<td>290</td>	<td>639</td>	</tr>
						<tr>	<th>66</th>	<td>300</td>	<td>661</td>	</tr>
						<tr>	<th>67</th>	<td>307</td>	<td>677</td>	</tr>
						<tr>	<th>68</th>	<td>315</td>	<td>694</td>	</tr>
						<tr>	<th>69</th>	<td>325</td>	<td>716</td>	</tr>
						<tr>	<th>70</th>	<td>335</td>	<td>736</td>	</tr>
						<tr>	<th>71</th>	<td>345</td>	<td>761</td>	</tr>
						<tr>	<th>72</th>	<td>355</td>	<td>783</td>	</tr>
						<tr>	<th>73</th>	<td>365</td>	<td>805</td>	</tr>
						<tr>	<th>74</th>	<td>375</td>	<td>827</td>	</tr>
						<tr>	<th>75</th>	<td>387</td>	<td>853</td>	</tr>
						<tr>	<th>76</th>	<td>400</td>	<td>882</td>	</tr>
						<tr>	<th>77</th>	<td>412</td>	<td>908</td>	</tr>
						<tr>	<th>78</th>	<td>425</td>	<td>937</td>	</tr>
						<tr>	<th>79</th>	<td>437</td>	<td>963</td>	</tr>
					</tbody>
				</table>
			</div>
		</dd>
	</dl>

	<h3 class="rlabel">Motorcycle tire designations charts<span></span></h3>
	<div class="tireDesignationsCharts-container clearer">
		<div class="tireDesignationsCharts-decipher"></div>
		<div class="tireDesignationsCharts-tables">
			<div class="tireDesignationsCharts-tables-title">Front tires</div>
			<table>
				<tr>	<th>Metric</th>	<th>Alpha</th>	<th>Inch</th>		</tr>
				<tr>	<td>80/90</td>	<td>MH</td>		<td>2.50/2.75</td>	</tr>
				<tr>	<td>90/90</td>	<td>MJ90</td>	<td>2.75/3.00</td>	</tr>
				<tr>	<td>100/90</td>	<td>MM90</td>	<td>3.25/3.50</td>	</tr>
				<tr>	<td>110/90</td>	<td>MM90</td>	<td>3.75/4.00</td>	</tr>
				<tr>	<td>120/80</td>	<td>N/A</td>	<td>4.25/4.50</td>	</tr>
				<tr>	<td>120/90</td>	<td>MR90</td>	<td>4.25/4.50</td>	</tr>
				<tr>	<td>130/90</td>	<td>MT90</td>	<td>5.00/5.10</td>	</tr>
			</table>
			<div class="tireDesignationsCharts-tables-title">Rear tires</div>
			<table>
				<tr>	<th>Metric</th>	<th>Alpha</th>	<th>Inch</th>		</tr>
				<tr>	<td>110/90</td>	<td>MP85</td>	<td>4.50/4.75</td>	</tr>
				<tr>	<td>120/90</td>	<td>MR90</td>	<td>1.50/4.75</td>	</tr>
				<tr>	<td>130/80</td>	<td>N/A</td>	<td>5.00/5.10</td>	</tr>
				<tr>	<td>130/90</td>	<td>MT90</td>	<td>5.00/5.10</td>	</tr>
				<tr>	<td>140/80</td>	<td>N/A</td>	<td>5.00/6.00</td>	</tr>
				<tr>	<td>140/90</td>	<td>MU90</td>	<td>6.00/6.25</td>	</tr>
				<tr>	<td>150/90</td>	<td>MV65</td>	<td>6.00/6.25</td>	</tr>
				<tr>	<td>150/90</td>	<td>MV65</td>	<td>6.00/6.25</td>	</tr>
			</table>
		</div>
	</div>


	<h3 class="rlabel">Wheel sizing and offset<span></span></h3>
	<dl class="wheelSizing-container">
		<dt>To determine the diameter of a wheel:</dt>
		<dd>Measure the width of the bead area of the wheel (not the outer rim). In the diagram above, the diameter measures 12 inches.</dd>

		<dt>To determine the offset and width of a wheel:</dt>
		<dd>Measure from the center weld to the center of the tire bead area on both sides of the wheel. The outer measurement will be the one with the valve stem. The offset of a wheel is stated by reading the measurement of the inside first, then the measurement of the outside (valve stem side). For example: In the diagram above, the offset is 5+2; meaning the inside half of the wheel measured 5 inches, and the outside (valve stem side) measured 2 inches. Add these 2 numbers together to find the total width of the rim (7 inches).</dd>

		<dd><strong>Note:</strong> If the rim has a tire on it, usually the tire will have the rim diameter imprinted on it (8", 9", 10"...). You can also measure the rim from inside using the diagram above and getting the measurements as close as possible.</dd>
		<div class="wheelSizing-chart"></div>
	</dl>

	<dl class="safety-warning">
		<dt>Safety:</dt>
		<dd>Inspect and check tire pressure often. This is the most important time-maintenance function you can perform. Refer to your machine's documentation for proper maintenance. Always give tires a gentle "run-in" period of 100 miles to get the feel of new tires - this means they should not be subjected to maximum power, abrupt lean-over, hard cornering, etc. Always match the front and rear tires for optimal handling, safety, and performance. Mixing radials, or mixing radials with bias or belted-bias tires may adversely affect handling and stability.
</dd>

		<dt>Warning:</dt>
		<dd>The charts and information on this page do not imply interchangeability. Consult your machine's manual to determine correct replacements, clearances, compatibility and stability, load-bearing capacity, speed rating, radial vs. non-radial, pattern and tread compound requirements, inflation recommendations and front-to-rear tire matching. Wrong selection can result in tire failure or loss of control with serious injury or death.</dd>
	</dl>

	<a class="backToTop" href="#">Back to top</a>
</div>