<?php
/**
 * Description of Logo
 * @package   CueBlocks_SitemapEnhanced
 * @company    CueBlocks - http://www.cueblocks.com/
 
 */
?>
<?php
/**
 * @see CueBlocks_SitemapEnhanced_Block_System_Config_Fieldset_Logo
 */
?>
<div style="border:1px solid #ccc; margin-bottom:10px; ">
    <h4 style="margin:0;padding:10px 5px 5px 15px;" >
        What this extension does ?
    </h4>

    <p style="padding:10px 5px 5px 15px;">
        XML Sitemaps Generator and Splitter extension will enable you to split the XML sitemaps of your store easily (whether you have over 50,000 pages or not) and help Search Engines like Google, Bing/Yahoo to find content on your store. The maximum limit to which Google follows an XML sitemap is 50 MB size or 50,000 URLs for each sitemap. Thus if your store has more than 50,000 pages, this extension will automatically split your store's XML Sitemap into smaller sitemaps and also create a sitemap index file, which will house all these sub-sitemaps in it.
        Even if the total number of pages in your store are less than 50,000, this extension will create separate sitemap.xml files for the different 'kinds' of 'Magento controlled' pages on your store (eg. Category, product, reviews, tags, CMS pages).
        <br/><br/>
        Use the following settings to control the way the sitemap.xml of your store(s) will be generated.
        </a>
    </p>
</div>
