<?php
/**
 * Description of Logo
 * @package   CueBlocks_SitemapEnhanced
 * @company    CueBlocks - http://www.cueblocks.com/
 
 */
?>
<?php
/**
 * @see CueBlocks_SitemapEnhanced_Block_System_Config_Fieldset_Logo/home/fra/Downloads/logo.png/home/fra/Downloads/cb_logo.png
 */
?>
<div style="background:url(<?php echo $this->getSkinUrl('images/cb_logo.png') ?>)no-repeat 5px center #eaf0ee; border:1px solid #ccc; margin-bottom:10px; padding:10px 5px 5px 115px;">
    <h4 style="margin:0;" >
        'XML Sitemap Generator & Splitter' is a product of CueBlocks. You can read more about the setup process & FAQs of this extension and others
        <a  style="text-decoration:none;" target="_blank" href="http://www.magentocommerce.com/magento-connect/developer/CueBlocks">
            <?php echo Mage::helper('sitemapEnhanced')->__('here') ?>
        </a>.
        You can visit our website at -<a target="_blank" style="text-decoration:none;" href="http://www.cueblocks.com">
            <?php echo Mage::helper('sitemapEnhanced')->__('www.CueBlocks.com') ?>
        </a>
    </h4>
</div>
