<?php

$ride = $this->getCurrentRide();
$fits = false;//$this->getFits();

?>
<div class="fitment-grouped fitment-selector">

	<div class="fitment-selected">
		<p class="fitment-selected-note"><?php echo $this->__('Select your vehicle:') ?></p>
		<div class="fitment-selected-ridename-container">
			<label><?php echo $this->__('Currently selected:') ?></label>
			<span id="fitment-ride-name"><?php echo Mage::helper('fitment')->formatRideName($ride) ?></span>
		</div>
		<p class="fitment-change">
			<button type="button" class="<?php echo $ride['id'] ? '' : 'fitment-hidden' ?> fitment-selector-reset" onclick="groupedFitmentSelector.resetRide({target:this})"><?php echo $this->__('Reset vehicle') ?></button>
			<button type="button" class="fitment-selector-change" onclick="groupedFitmentSelector.changeRide({target:this})"><?php echo $this->__('Choose your vehicle') ?></button>
		</p>
	</div>

	<div class="fitment-selectors">
		<span><?php echo $this->__('Select your ride:') ?></span>
		<div class="fitment-notice"><?php echo $this->__('If your ride is not within this list, then current product doesn\'t fit it. Try searching for other products.') ?></div>
		<ul>
			<li class="make">
				<label for="fitment-make"><?php echo $this->__('Select Make') ?></label>
				<select id="fitment-make" name="fitment-make" onchange="groupedFitmentSelector.changedMake({target:this})">
					<option value=""><?php echo $this->__('-- Select Make --') ?></option>
				</select>
			</li>

			<li class="year">
				<label for="fitment-year"><?php echo $this->__('Select Year') ?></label>
				<select id="fitment-year" name="fitment-year" onchange="groupedFitmentSelector.changedYear({target:this})">
					<option><?php echo $this->__('-- Select year --') ?></option>
				</select>
			</li>

			<li class="model">
				<label for="fitment-model"><?php echo $this->__('Select Model') ?></label>
				<select id="fitment-model" name="fitment-model" onchange="groupedFitmentSelector.changedModel({target:this})">
					<option><?php echo $this->__('-- Select model --') ?></option>
				</select>
			</li>
		</ul>
		<p>
			<button class="fitment-save" type="button" onclick="groupedFitmentSelector.saveRide({target:this})"><?php echo $this->__('Select') ?></button>
			<button class="fitment-cancel" type="button" onclick="groupedFitmentSelector.restoreRide({target:this})"><?php echo $this->__('Close') ?></button>
		</p>
	</div>

</div>

<div class="fitment-grouped-partlist-container"></div>
