<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>Z1R Street Glove Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'z1r/brand_logo.jpg' ?>" alt="Z1R" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'z1r/zr1_glove2.jpg' ?>" alt="Street Glove Sizes" /> </div>
  <h1>Size Measurement</h1>
  <p>Icon glove size is determined by measuring the width of your palm at its widest point, little below the knuckles</p>
  <div class='fox-gloves-table-header'>Street Glove Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens</td>
      <td>S</td>
      <td>M</td>
      <td>L</td>
      <td>XL</td>
      <td>2XL</td>
      <td>3XL</td>
      <td>4XL</td>
    </tr>
    <tr>
      <td class="title3">INCHES</td>
      <td>2 3/4</td>
      <td>3 1/4</td>
      <td>3 3/4</td>
      <td>4 1/4</td>
      <td>4 3/4</td>
      <td>5 1/4</td>
      <td>5 3/4</td>
    </tr>
  </table>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Womens</td>
      <td>S</td>
      <td>M</td>
      <td>L</td>
      <td>XL</td>
      <td>2XL</td>
    </tr>
    <tr>
      <td class="title3">INCHES</td>
      <td>2 1/8</td>
      <td>2 5/8</td>
      <td>3</td>
      <td>3 1/2</td>
      <td>4</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
