<?php
$isAjax = $this->getIsAjax();
$cartItems = array();
$_cartQty = (int) $this->getSummaryCount();
?>
<?php if ($isAjax): ?>
    <div class="top-cart <?php if (!$_cartQty) echo 'no-items' ?>">
        <?php if ($this->getIsLinkMode() || !$this->getIsNeedToDisplaySideBar()): ?>
            <div class="block-title no-items">
                <ul class="links cart-link">
                    <li>
                        <a href="<?php echo $this->getUrl('checkout/cart'); ?>">
                            <p class="cart-item">this is a test<?php echo $_cartQty ?></p> <p class="incart"><?php echo nl2br($this->__("items \nin your cart")) ?></p><div class="crystal"></div>
                        </a>
                    </li>
                </ul>
            </div>
        <?php else: ?>
            <div class="block-title cart-table" onclick="jQuery('#topCartContent').css({visibility: 'visible'})">
                <strong id="cartHeader">
                    <p class="cart-item"><a href="<?php echo Mage::helper('checkout/cart')->getCartUrl() ?>" class="cart-count"><?php echo (int) $_cartQty ?></a></p>                     
                </strong>
            </div>
            <div id="topCartContent" class="block-content" onmouseleave="jQuery(this).css({visibility: 'hidden'})">
                <div class="inner-wrapper"><?php // extra div to smooth slideUp and slideDown        ?>
                    <?php $_items = $this->getRecentItems() ?>
                    <?php if (count($_items)): ?>
                        <p class="block-subtitle" style="display:none">
                            <span id="recent_items_count"></span> <?php echo $this->__('Items added to cart') ?>
                            <span onclick="cart.hideCart()" class="close-btn" style="position: absolute; padding-left: 35px; color: red; cursor: pointer;"><?php echo $this->__('Close'); ?></span>
                        </p>
                        <table>
                            <thead>
                                <tr>
                                    <th class="topcart-col-part"><?php echo $this->__('Part') ?></th>
                                    <th class="topcart-col-qty"><?php echo $this->__('Qty') ?></th>
                                    <th class="topcart-col-price"><?php echo $this->__('Price') ?></th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                        <ul id="mini-cart" class="mini-products-list">
                            <?php foreach ($_items as $_item): ?>
                                <?php $cartItems[] = $_item->getSku(); ?>
                                <?php echo $this->getItemHtml($_item) ?>
                            <?php endforeach; ?>
                        </ul>
                        <script type="text/javascript">decorateList('mini-cart', 'none-recursive')</script>
                    <?php else: ?>
                        <p class="block-subtitle">
                            <span onclick="cart.hideCart()" class="close-btn"><?php echo $this->__('Close'); ?></span>
                            <?php echo $this->__('Recently added item(s)') ?>
                        </p>
                        <p class="cart-empty">
                            <?php echo $this->__('You have no items in your shopping cart yet.') ?>
                        </p>
                        <?php if ($this->getCartEmptyMessage()): ?>
                            <p class="cart-empty cart-empty-message"><?php echo $this->getCartEmptyMessage(); ?></p>
                        <?php endif; ?>
                    <?php endif ?>
                    <?php if ($_cartQty || $this->getAllowCartLink()): ?>
                        <?php $isPossibleOnepageCheckout = $_cartQty && $this->isPossibleOnepageCheckout() ?>
                        <?php if ($isPossibleOnepageCheckout): ?>
                            <p class="subtotal">
                                <?php if ($this->canApplyMsrp()): ?>
                                    <span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                                <?php else: ?>
                                    <span class="label"><?php echo $this->__('Cart Total:') ?></span> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?><?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?> / <?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?><?php endif; ?>
                                <?php endif; ?>
                            </p>
                        <?php endif ?>
                        <div class="actions">
                            <div>
                                <?php if ($isPossibleOnepageCheckout): ?>
                                    <?php echo $this->getChildHtml('extra_actions') ?>
                                    <button class="button" type="button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
                                <?php endif ?>                                    
                            </div>
                        </div>
                    <?php endif ?>
                    <div class="close-cart-header" onclick="_cartHeader.close()">Close <span class="close-x">x</span></div>
                </div>
            </div>
        <?php endif; ?>
        <input type='hidden' id='cartItems' value='<?php echo json_encode($cartItems) ?>' />
    </div>
<?php else: ?>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            jQuery.ajax({
                url: '<?php echo $this->getUrl('ajaxcheckout/cart/topCart') ?>'.replace('http:', document.location.protocol),
                dataType: 'html',
                cache: false,
                success: function (response) {
                    jQuery('#minicart').html(response);
                }
            });

            _cartHeader = {
                close: function () {
                    jQuery("#topCartContent").css({
                        visibility: 'hidden'
                    });
                }
            };
        });

    </script>
<?php endif ?>