<div class="ven-prehead striped">
	<div class="site-width">
        	<h1>Call Us <span>951 698-4123</span></h1> | <a class="sign-in toacctlink">Sign In</a>
    </div>
</div>
<div class="ven-head">
	<div class="site-width">
            <h1 class="ven-logo"><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>"><img src="<?php echo $this->getSkinUrl('images/header/logo-temecula.png');?>" alt=""/></a></h1>
            <div class="rightvh">
            <p class="activity-sort">Shop by Activity</p>
            <div class="corner">
            <div class="cart-table">
                            <p class="cart-item">99</p><p class="incart">items <span class="in-cart">in your cart</span></p>
                            <div class="crystal"></div>
                        </div>
</div>
<?php echo $this->getChildHtml('topSearch') ?>
<div class="crystal"></div>
			</div>				
<div class="crystal"></div>
</div>            
            

            
</div>

<div class="ven-headlinks striped">
	<div class="site-width">
    <div class="vendor-logo"><img src="<?php echo $this->getSkinUrl('images/vendor/vendor-logo/fox-logo.jpg');?>" alt=""/>
    
    </div>
    <div class="vendor-links">
      <ul>
        <li><a href="#">guys</a></li>
        <li><a href="#">girls</a></li>
        <li><a href="#">footwear</a></li>
        <li><a href="#">mx</a></li>
        <li><a href="#">surf</a></li>
        <li><a href="#">mtb</a></li>
        <li><a href="#">bmx</a></li>
        <li><a href="#">wake</a></li>
        <li><a href="#">eyewear</a></li>
        <li><a href="#">active</a></li>
      </ul>
<script type="text/javascript">
			//<![CDATA[
			decorateGeneric($$('.vendor-links li'), ['first','last'])
			//]]            
            </script>    
    <div class="crystal"></div>
    </div>
    
	</div>
</div>
<div class="vendor-banner">
<img src="<?php echo $this->getSkinUrl('images/vendor/foxbg.jpg');?>" alt=""/>
</div>
<div class="ven-extracat">
<div class="striped">
	<div class="site-width">
	  <ul>
		  <li><a href="#"><img src="<?php echo $this->getSkinUrl('images/vendor/fox-racing-gear.png');?>" alt=""/></a></li>
          <li><a href="#"><img src="<?php echo $this->getSkinUrl('images/vendor/fox-boots.png');?>" alt=""/></a></li>
          <li><a href="#"><img src="<?php echo $this->getSkinUrl('images/vendor/fox-helmets.png');?>" alt=""/></a></li>
          <li><a href="#"><img src="<?php echo $this->getSkinUrl('images/vendor/fox-gloves.png');?>" alt=""/></a></li>
	  </ul>
<script type="text/javascript">
			//<![CDATA[
			decorateGeneric($$('.ven-extracat li'), ['first','last'])
			//]]            
            </script>
            <div class="crystal"></div>
	</div>
</div>
</div>