<div class="vendor-footer-container">
    <div class="site-width">
<div class="vendor-news">
	<div class="left">
    	<div class="ventitle">
        <h1>Latest News</h1><a href="#">view all</a>
        </div>
        <ul class="newsfeed">
          <li><img src="<?php echo $this->getSkinUrl('images/vendor/placev1.jpg');?>" alt=""/>
          <div class="toright">
            <p>Lorem ipsum dolor sit amet, consectetur.tempor incididunt ut labore et dolore magna aliqua. Ut enim.<a href="#">MORE</a></p></div><div class="crystal"></div>          <p class="date">August 08, 2014</p>
          </li>
          <li><img src="<?php echo $this->getSkinUrl('images/vendor/placev2.jpg');?>" alt=""/>
          <div class="toright">
            <p>Lorem ipsum dolor sit amet, consectetur.tempor incididunt ut labore et dolore magna aliqua. Ut enim.<a href="#">MORE</a></p></div><div class="crystal"></div>          <p class="date">August 08, 2014</p>
          </li>
          <li><img src="<?php echo $this->getSkinUrl('images/vendor/placev3.jpg');?>" alt=""/>
          <div class="toright">
            <p>Lorem ipsum dolor sit amet, consectetur.tempor incididunt ut labore et dolore magna aliqua. Ut enim.<a href="#">MORE</a></p></div><div class="crystal"></div>          <p class="date">August 08, 2014</p>
          </li>
          <li><img src="<?php echo $this->getSkinUrl('images/vendor/placev4.jpg');?>" alt=""/>
          <div class="toright">
            <p>Lorem ipsum dolor sit amet, consectetur.tempor incididunt ut labore et dolore magna aliqua. Ut enim.<a href="#">MORE</a></p></div><div class="crystal"></div>          <p class="date">August 08, 2014</p>
          </li>

        </ul>

    </div>
    
    <div class="right">
    <div class="ventitle">
        <h1>Featured Video</h1><a href="#">view all</a>
        </div>
    <div class="video-place">
    <img src="<?php echo $this->getSkinUrl('images/vendor/video-place.jpg');?>" alt=""/>
    </div>
    </div>
    <div class="crystal"></div>

</div>

    </div>
</div>
<div class="ven-socials">
<div class="site-width dasher">
<p>
<span>Follow FOX</span> <a href="#"><img src="<?php echo $this->getSkinUrl('images/vendor/ico-fb.gif');?>" alt=""/></a> <a href="#"><img src="<?php echo $this->getSkinUrl('images/vendor/ico-tw.gif');?>" alt=""/></a> <a href="#"><img src="<?php echo $this->getSkinUrl('images/vendor/ico-ig.gif');?>" alt=""/></a> <a href="#"><img src="<?php echo $this->getSkinUrl('images/vendor/ico-yt.gif');?>" alt=""/></a></p>
</div>
</div>
