<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>Atlas Snow Neck Brace Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'atlas/brand_logo.jpg' ?>" alt="Atlas" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'atlas/neck_brace.jpg' ?>" alt="Snow Neck Brace Sizes" /> </div>
  <h1>Size Measurement</h1>
  <p>Chest: Measure your chest right below your arms</p>
  <div class='fox-gloves-table-header'>Snow Neck Brace Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens</td>
      <td>S</td>
      <td>M</td>
      <td>L</td>
    </tr>
    <tr>
      <td class="title3">CHEST</td>
      <td>33-36</td>
      <td>37-41</td>
      <td>42+</td>
    </tr>
  </table>
  <p>Small: 33&rdquo; - 36&rdquo; (84cm - 92 cm)<br />
  Medium: 37&rdquo; - 41&rdquo; (94cm - 104 cm)<br />
  Large: 42+ (106 cm+)</p>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
