<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>Tourmaster  Glove Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'tourmaster/brand_logo.jpg' ?>" alt="Tourmaster" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'tourmaster/default_glove3.jpg' ?>" alt="Glove Sizes" /> </div>
  <h1>Hand Length</h1>
  <p>Measurement should be at the widest point of your palm.</p>
  <div class='fox-gloves-table-header'> Glove Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">MEN'S</td>
      <td>XS</td>
      <td>S</td>
      <td>M</td>
      <td>L</td>
      <td>XL</td>
      <td>2XL</td>
      <td>3XL</td>
    </tr>
    <tr>
      <td class="title3">INCHES</td>
      <td>2.5</td>
      <td>3</td>
      <td>3.5</td>
      <td>4</td>
      <td>4.5</td>
      <td>5</td>
      <td>5.5</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
