<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */

$_category = Mage::registry('current_category');

?>
<?php if ($this->canShowBlock() && $this->getRequest()->getControllerName() != 'result' && $this->getRequest()->getControllerName() != 'advanced'): ?>
    <div class="block block-layered-nav">
        <?php if ($this->getCategoryPage() && ($_category->getLevel() != 2)): ?>
            <div class="block-title">
                <strong><span><?php echo $this->__('Shop By') ?></span></strong>
            </div>
        <?php endif; ?>
        <div class="block-content">
            <div class="layered-nav-label"><span>Layered Navigation</span></div>
            <?php if ($this->canShowOptions()): ?>
                <dl id="narrow-by-list">
                    <?php if (($_category->getLevel() == 3 || $_category->getLevel() == 4 || $_category->getLevel() == 5)): ?>
                        <dt class="dt-layered-nav-department">
                        <?php echo $this->__('Department') ?>
                        </dt>
                        <dd class="dd-layered-nav-department dd-layered-nav-department-<?php echo $_category->getLevel(); ?>">
                            <select class="layered-nav-select" onchange="window.location = this.value">
                                <?php
                                if ($_category->getLevel() == 5) {
                                    $parentId = $_category->getParentId();
                                    $parentCategory = Mage::getModel('catalog/category')->load($parentId);

                                    $grandParentId = $parentCategory->getParentId();

                                    $grandParentCategory = Mage::getModel('catalog/category')->load($grandParentId);

                                    $currentCategory = $grandParentCategory;
                                    $categoryId = $grandParentCategory->getParentId();
                                } else if ($_category->getLevel() == 4) {
                                    $parentId = $_category->getParentId();
                                    $parentCategory = Mage::getModel('catalog/category')->load($parentId);

                                    $currentCategory = $parentCategory;
                                    $categoryId = $parentCategory->getParentId();
                                } else {
                                    $currentCategory = $_category;
                                    $categoryId = $_category->getParentId();
                                }

                                $category = Mage::getModel('catalog/category')->load($categoryId);
                                $catList = $category->getChildrenCategories();



                                foreach ($catList as $subcategory) {
                                    ?>
                                    <option value="<?php echo $this->urlEscape($subcategory->getUrl()) ?>" <?php echo $currentCategory->getId() == $subcategory->getId() ? 'selected="selected"' : '' ?>>
                                        <?php echo $subcategory->getName(); ?>
                                    </option>
                                    <?php
                                }
                                ?>
                            </select>
                        </dd>
                    <?php endif; ?>

                    <?php if ($_category->getLevel() == 4 || $_category->getLevel() == 5): ?>
                        <dt class="dt-layered-nav-department">
                        <?php echo $this->__('Category') ?>
                        </dt>
                        <dd class="dd-layered-nav-department">
                            <select class="layered-nav-select" onchange="window.location = this.value">
                                <?php
                                if ($_category->getLevel() == 5) {
                                    $parentId = $_category->getParentId();
                                    $parentCategory = Mage::getModel('catalog/category')->load($parentId);

                                    $currentCategory = $parentCategory;
                                    $categoryId = $parentCategory->getParentId();
                                } else {
                                    $currentCategory = $_category;
                                    $categoryId = $_category->getParentId();
                                }

                                $category = Mage::getModel('catalog/category')->load($categoryId);
                                $catList = $category->getChildrenCategories();

                                foreach ($catList as $subcategory) {
                                    ?>
                                    <option value="<?php echo $this->urlEscape($subcategory->getUrl()) ?>" <?php echo $currentCategory->getId() == $subcategory->getId() ? 'selected="selected"' : '' ?>>
                                        <?php echo $subcategory->getName(); ?>
                                    </option>
                                    <?php
                                }
                                ?>
                            </select>
                        </dd>
                    <?php endif; ?>

                    <?php if ($_category->getLevel() == 5): ?>
                        <dt class="dt-layered-nav-department">
                        <?php echo $this->__('Type') ?>
                        </dt>
                        <dd class="dd-layered-nav-department">
                            <select class="layered-nav-select" onchange="window.location = this.value">
                                <?php
                                $currentCategory = $_category;
                                $categoryId = $_category->getParentId();


                                $category = Mage::getModel('catalog/category')->load($categoryId);
                                $catList = $category->getChildrenCategories();

                                foreach ($catList as $subcategory) {
                                    ?>
                                    <option value="<?php echo $this->urlEscape($subcategory->getUrl()) ?>" <?php echo $currentCategory->getId() == $subcategory->getId() ? 'selected="selected"' : '' ?>>
                                        <?php echo $subcategory->getName(); ?>
                                    </option>
                                    <?php
                                }
                                ?>
                            </select>
                        </dd>
                    <?php endif; ?>

                    <?php
                    if ($_category->getLevel() == 3 || $_category->getLevel() == 4 || $_category->getLevel() == 5):
                        if ($_category->getHasFitment()):
                            $fitmentSelectorBlock = $this->getLayout()->createBlock('fitment/landing_selector');
                            if ($fitmentSelectorBlock instanceof Mage_Core_Block_Template) {
                                echo $fitmentSelectorBlock
                                        ->setCategory($_category)
                                        ->toHtml();
                            }
                        endif;
                    endif;
                    ?>

                    <?php $_filters = $this->getFilters(); ?>
                    <?php $hasCategoryFilter = false; ?>
                    <?php foreach ($_filters as $_filter): ?>

                        <?php
                        //only show category filter on level 2, 3 and 4 categories
                        $_mcategory = Mage::getModel('catalog/category')->load($_category->getId());
                        $_catList = $_mcategory->getChildrenCategories();

                        if (($_category->getLevel() == 3 && count($_catList) > 0) && strtolower($_filter->getName()) != 'category') {
                            continue;
                        }
                        ?>
                        <?php if ($_filter->getItemsCount()): ?>
                            <?php if ($this->getCategoryPage() && ($_category->getLevel() == 2 && strtolower($_filter->getName()) == 'category')): ?>
                                <dt class="dt-layered-nav-department">
                                <?php echo $this->__('Department') ?>
                                </dt>
                                <dd class="dd-layered-nav-department"><?php echo $_filter->getHtml() ?></dd>
                            <?php else: ?>

                                <dt style="<?php echo strtolower($_filter->getName()) == 'product is' ? 'display: none' : ''; ?>">
                                <?php if ($_category->getLevel() == 2 && strtolower($_filter->getName()) == 'category'): ?>
                                    <?php echo $this->__('Department') ?>
                                <?php else: ?>
                                    <?php
                                    if ($_category->getLevel() == 4 && strtolower($_filter->getName()) == 'category') {
                                        echo $this->__('Type');
                                    } else {
                                        echo $this->__($_filter->getName());
                                    }
                                    ?>
                                <?php endif; ?>
                                </dt>
                                <dd  style="<?php echo strtolower($_filter->getName()) == 'product is' ? 'display: none' : ''; ?>" class="<?php echo $_filter->getCode() ?>"><?php echo $_filter->getHtml() ?></dd>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </dl>
                <script type="text/javascript">decorateDataList('narrow-by-list')</script>

                <?php
                if ($_category->getLevel() == 2):
                    if ($_category->getHasFitment()):
                        $fitmentSelectorBlock = $this->getLayout()->createBlock('fitment/landing_selector');
                        if ($fitmentSelectorBlock instanceof Mage_Core_Block_Template) {
                            echo $fitmentSelectorBlock
                                    ->setCategory($_category)
                                    ->toHtml();
                        }
                    endif;
                endif;
                ?>

            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>

<?php if ($this->canShowBlock() && ($this->getRequest()->getControllerName() == 'result' || $this->getRequest()->getControllerName() == 'advanced')): ?>
    <div class="block block-layered-nav">
        <div class="block-content">
            <?php echo $this->getStateHtml() ?>
            <?php if ($this->getLayer()->getState()->getFilters()): ?>
                <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
            <?php endif; ?>
            <?php if ($this->canShowOptions()): ?>
                <dl id="narrow-by-list">
                    <?php $_filters = $this->getFilters() ?>
                    <?php foreach ($_filters as $_filter): ?>
                        <?php if ($_filter->getItemsCount()): ?>
                            <dt><?php echo $this->__($_filter->getName()) ?></dt>
                            <dd><?php echo $_filter->getHtml() ?></dd>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </dl>
                <script type="text/javascript">decorateDataList('narrow-by-list')</script>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>