<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'msr'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>MSR Offroad Pants Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="MSR" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/pants.jpg' ?>" alt="Pants Sizes" />
	</div>

	<h1>INSEAM</h1>

	<p>While standing without shoes and with feet slightly apart, measure from the crotch along the leg to the floor.</p>
	
	<h1>WAIST</h1>

	<p>With a tape measure about 1 inch below the pelvis bone and holding it level, measure the circumference at the waist while standing with natural bend.</p>

	<div class='fox-gloves-table-header'>Pants Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">PANTS SIZE</td>
			<td>26</td>
			<td>28</td>
			<td>30</td>
			<td>32</td>
			<td>34</td>
			<td>36</td>
			<td>38</td>
			<td>40</td>
			<td>42</td>
			<td>44</td>
			<td>46</td>
			<td>48</td>
			<td>50</td>
		</tr>
		<tr>
			<td class="title3">WAIST SIZE</td>
			<td>26-27 1/2</td>
			<td>28-29 1/2</td>
			<td>30-31 1/2</td>
			<td>32-33 1/2</td>
			<td>34-35 1/2</td>
			<td>36-37 1/2</td>
			<td>38-391/2</td>
			<td>40-41 1/2</td>
			<td>42-43 1/2</td>
			<td>44-41 1/2</td>
			<td>46-41 1/2</td>
			<td>48-49 1/2</td>
			<td>50-51 1/2</td>
		</tr>
		<tr>
			<td class="title3">INSEAM SIZE</td>
			<td>26 3/4</td>
			<td>27 1/2</td>
			<td>28 1/4</td>
			<td>29</td>
			<td>29 3/4</td>
			<td>30 1/2</td>
			<td>31 1/4</td>
			<td>32</td>
			<td>32 1/2</td>
			<td>33 1/2</td>
			<td>34</td>
			<td>34 1/2</td>
			<td>35</td>
		</tr>
	</table>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">WOMEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">PANTS SIZE</td>
			<td>2</td>
			<td>4</td>
			<td>6</td>
			<td>8</td>
			<td>10</td>
			<td>12</td>
			<td>14</td>
		</tr>
		<tr>
			<td class="title3">WAIST SIZE</td>
			<td>24-25 1/2</td>
			<td>26-27 1/2</td>
			<td>28-29 1/2</td>
			<td>30-31 1/2</td>
			<td>32-33 1/2</td>
			<td>34-35 1/2</td>
			<td>36-37 1/2</td>
		</tr>
		<tr>
			<td class="title3">INSEAM SIZE</td>
			<td>26 1/2</td>
			<td>27 1/4</td>
			<td>28</td>
			<td>28 3/4</td>
			<td>29 1/2</td>
			<td>30 1/8</td>
			<td>30 3/4</td>
		</tr>
	</table>
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">YOUTH</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">PANTS SIZE</td>
			<td>Y16</td>
			<td>Y18</td>
			<td>Y20</td>
			<td>Y22</td>
			<td>Y24</td>
		</tr>
		<tr>
			<td class="title3">WAIST SIZE</td>
			<td>16-17 1/2</td>
			<td>18-19 1/2</td>
			<td>20-21 1/2</td>
			<td>22-23 1/2</td>
			<td>24-25 1/8</td>
		</tr>
		<tr>
			<td class="title3">INSEAM SIZE</td>
			<td>15 1/2</td>
			<td>17</td>
			<td>18 1/2</td>
			<td>20</td>
			<td>21</td>
		</tr>
	</table>
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>