<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'cyber'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Cyber Helmets Helmet Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.png' ?>" alt="Cyber Helmets" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/helmet.jpg' ?>" alt="Helmet Sizes" />
	</div>

	<h1>Description</h1>

	<p>For best Results use a tape measure keeping it level, measure the widest point of your head, approximately 1" above your eyebrows.</p>
	
	<div class='fox-gloves-table-header'>Helmet Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">HELMET SIZE</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
		</tr>
		<tr>
			<td class="title3">USA HAT SIZE</td>
			<td>6 3/4-6 7/8</td>
			<td>7-7 1/8</td>
			<td>7 1/4-7 3/8</td>
			<td>7 1/2-8</td>
		</tr>
		<tr>
			<td class="title3">INCHES</td>
			<td>21-21 5/8</td>
			<td>21 3/4-22 3/8</td>
			<td>22 1/2-23 1/8</td>
			<td>23 1/4-24</td>
		</tr>
	</table>

	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>