<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'troylee'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Troy Lee Jersey Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="Troy Lee" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/jersey.jpg' ?>" alt="Glove Sizes" />
	</div>

	<h1>Description</h1>

	<p>Jerseys will run slightly bigger for a good comfortable and unrestricted fit.</p>
	
	<h1>Sleeve</h1>

	<p>Measure from center of the spine at the base of the neck, around the shoulder, over the elbow and down to the wrist.</p>
	
	<h1>Chest</h1>

	<p>Measure around the broadest part of the chest 1-2 below the arm pits.</p>

	<div class='fox-gloves-table-header'>Jersey Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">JERSEY SIZE</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
			<td>3XL</td>
		</tr>
		<tr>
			<td class="title3">CHEST SIZE</td>
			<td>21</td>
			<td>22</td>
			<td>23</td>
			<td>24</td>
			<td>25.5</td>
			<td>26.5</td>
		</tr>
		<tr>
			<td class="title3">SLEEVE SIZE</td>
			<td>33</td>
			<td>35</td>
			<td>37</td>
			<td>38</td>
			<td>39</td>
			<td>39</td>
		</tr>
	</table>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">WOMEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">JERSEY SIZE</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
		</tr>
		<tr>
			<td class="title3">CHEST SIZE</td>
			<td>19</td>
			<td>20</td>
			<td>21</td>
			<td>22</td>
		</tr>
		<tr>
			<td class="title3">SLEEVE SIZE</td>
			<td>32</td>
			<td>32.5</td>
			<td>33</td>
			<td>34</td>
		</tr>
	</table>
	
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">YOUTH'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">JERSEY SIZE</td>
			<td>YXS</td>
			<td>YS</td>
			<td>YM</td>
			<td>YL</td>
			<td>YXL</td>
		</tr>
		<tr>
			<td class="title3">CHEST SIZE</td>
			<td>14</td>
			<td>15.5</td>
			<td>17</td>
			<td>18.5</td>
			<td>20</td>
		</tr>
		<tr>
			<td class="title3">SLEEVE SIZE</td>
			<td>22</td>
			<td>24</td>
			<td>26</td>
			<td>28</td>
			<td>30</td>
		</tr>
	</table>
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit.</p>

</div>