<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>Troy Lee Offroad Moto Shorts Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'fox/brand_logo.jpg' ?>" alt="Fox" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'fox/glove_size.jpg' ?>" alt="Glove Sizes" /> </div>
  <h1>Size Measurement</h1>
  <p>Inseam: While standing without shoes and with feet slightly apart, measure from the crotch along the leg to the floor.</p>
  <p>Waist: With a tape measure about 1 inch below the pelvis bone and holding it level, measure the circumference at the waist while standing with natural bend.</p>
  <div class='fox-gloves-table-header'>Offroad Moto Shorts Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="title3">SHORT SIZE</td>
      <td>28</td>
      <td>30</td>
      <td>32</td>
      <td>34</td>
      <td>36</td>
      <td>38</td>
    </tr>
    <tr>
      <td class="title3">WAIST SIZE</td>
      <td>27-29</td>
      <td>29-31</td>
      <td>31-33</td>
      <td>33-35</td>
      <td>35-37</td>
      <td>37-39</td>
    </tr>
    <tr>
      <td class="title3">INSEAM SIZE</td>
      <td>14.75</td>
      <td>14.75</td>
      <td>14.75</td>
      <td>14.75</td>
      <td>14.75</td>
      <td>14.75</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
