<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>Troy Lee Offroad Jersey Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'fox/brand_logo.jpg' ?>" alt="Fox" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'fox/glove_size.jpg' ?>" alt="Glove Sizes" /> </div>
  <h1>Size Measurement</h1>
  <p>Jerseys will run slightly bigger for a good confortable and unrestricted fit.</p>
  <p>Sleeve: Measure from center of the spine at the base of the neck, around the shoulder,over the elbow and down to the wrist</p>
  <p>Chest: Measure around the broadest part of the chest 1-2 below the arm pits.</p>
  <div class='fox-gloves-table-header'>Offroad Jersey Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Youth</td>
      <td>YXS</td>
      <td>YS</td>
      <td>YM</td>
      <td>YL</td>
      <td>YXL</td>
    </tr>
    <tr>
      <td class="title3">CHEST SIZE</td>
      <td>14</td>
      <td>15.5</td>
      <td>17</td>
      <td>18.5</td>
      <td>20</td>
    </tr>
    <tr>
      <td class="title3">CHEST</td>
      <td>22</td>
      <td>24</td>
      <td>26</td>
      <td>28</td>
      <td>30</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
