<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>Troy Lee Offroad Helmet Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'fox/brand_logo.jpg' ?>" alt="Fox" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'fox/glove_size.jpg' ?>" alt="Glove Sizes" /> </div>
  <h1>Head Measurement</h1>
  <p>For best results use a tape measure keeping it level, measure the widest point of your head, approximately 1" above your eyebrows. Headliners and cheekpads can be interchanged within the same EPS size. SE3 cheekpads are interchangable through the entire size range.</p>
  <div class='fox-gloves-table-header'>Offroad Helmet Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">MEN'S</td>
      <td>XS</td>
      <td>S</td>
      <td>M</td>
      <td>L</td>
      <td>XL</td>
      <td>2L</td>
    </tr>
    <tr>
      <td class="title3">USA HAT SIZE</td>
      <td>6 5/8-6 3/4</td>
      <td>6 3/4-7</td>
      <td>7-7 1/4</td>
      <td>7 1/4-7 1/2</td>
      <td>7 1/2-7 3/4</td>
      <td>7 3/4-7 7/8</td>
    </tr>
    <tr>
      <td class="title3">INCHES</td>
      <td>20 7/8-20 1/4</td>
      <td>21 1/4-22</td>
      <td>22-22 3/4</td>
      <td>22 3/4-23 5/8</td>
      <td>23 5/8-24 1/2</td>
      <td>24 1/2-24 7/8</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
