<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'troylee'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Troy Lee Pants Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="Troy Lee" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/pants.jpg' ?>" alt="Pants Sizes" />
	</div>

	<h1>INSEAM</h1>

	<p>While standing without shoes and with feet slightly apart, measure from the crotch along the leg to the floor.</p>
	
	<h1>WAIST</h1>

	<p>With a tape measure about 1 inch below the pelvis bone and holding it level, measure the circumference at the waist while standing with natural bend.</p>

	<div class='fox-gloves-table-header'>Pants Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	
		<tr>
			<td class="title3">PANT SIZE</td>
			<td>28</td>
			<td>30</td>
			<td>32</td>
			<td>34</td>
			<td>36</td>
			<td>38</td>
			<td>40</td>
			<td>42</td>
			<td>44</td>		
		</tr>
		
		<tr>
			<td class="title3">WAIST SIZE</td>
			<td>29-33</td>
			<td>31-34</td>
			<td>33-36</td>
			<td>35-38</td>
			<td>37-40</td>
			<td>39-42</td>
			<td>41-44</td>
			<td>43-46</td>
			<td>45-48</td>	
		</tr>
		
		<tr>
			<td class="title3">INSEAM</td>
			<td>30.1</td>
			<td>31</td>
			<td>32</td>
			<td>32.5</td>
			<td>33.5</td>
			<td>34</td>
			<td>35</td>
			<td>36</td>
			<td>36</td>
		</tr>
	</table>
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">WOMEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	
		<tr>
			<td class="title3">PANT SIZE</td>
			<td>3/4</td>
			<td>5/6</td>
			<td>7/8</td>
			<td>9/10</td>
			<td>11/12</td>
		</tr>
		<tr>
			<td class="title3">WAIST SIZE</td>
			<td>29-31</td>
			<td>31-33</td>
			<td>33-35</td>
			<td>35-37</td>
			<td>37-39</td>
		</tr>
		<tr>
			<td class="title3">INSEAM SIZE</td>
			<td>29.5</td>
			<td>29.5</td>
			<td>30</td>
			<td>30.5</td>
			<td>31</td>
		</tr>
		
		<tr>
			<td class="title3">HIP SIZE</td>
			<td>36</td>
			<td>37</td>
			<td>38 1/2</td>
			<td>40</td>
			<td>41 1/2</td>
		</tr>
	</table>
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">YOUTH'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	
		<tr>
			<td class="title3">PANT SIZE</td>
			<td>Y18</td>
			<td>Y20</td>
			<td>Y22</td>
			<td>Y24</td>
			<td>Y26</td>
			<td>Y28</td>
		</tr>
		<tr>
			<td class="title3">WAIST SIZE</td>
			<td>21</td>
			<td>21 1/2</td>
			<td>23</td>
			<td>24</td>
			<td>25</td>
			<td>26</td>
		</tr>
		<tr>
			<td class="title3">INSEAM SIZE</td>
			<td>39-41</td>
			<td>42-44</td>
			<td>47-48</td>
			<td>50-52</td>
			<td>54-56</td>
			<td>58-60</td>
		</tr>
		
	</table>

	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>