<div class="footer-container">
    <div class="footer site-width">
        <?php //echo $this->getChildHtml() ?>
        <?php /* <p class="bugs"><?php echo $this->__('Help Us to Keep Magento Healthy') ?> - <a href="http://www.magentocommerce.com/bug-tracking" onclick="this.target='_blank'"><strong><?php echo $this->__('Report All Bugs') ?></strong></a> <?php echo $this->__('(ver. %s)', Mage::getVersion()) ?></p> */ ?>
        <div class="foot-left">
            <h1 class="foot-logo sh"><a href="<?php echo $this->getUrl('') ?>"><span>Temecula</span></a></h1>
            <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('links-info-about')->toHtml(); ?>
            <div class="custom-serve">
                <h3>customer services</h3>
                <ul>
                    <li><a class="contact" href="<?php echo Mage::getBaseUrl(); ?>contact-us.html">Contact Us</a></li>
                    <li><a class="live-chat" href="#">Live Chat</a></li>
                    <?php //if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                    <li><a class="order-stat" href="<?php echo Mage::getBaseUrl(); ?>sales/order/history/">Order Status</a></li>
                    <li><a class="leave-feedback" href="<?php echo Mage::getBaseUrl(); ?>help-us-improve-tmsparts.html">Leave Feedback</a></li>
                    <?php //endif; ?>
                    <?php /** ?>
                      <li><a class="return-canter" href="#">Return Center</a></li>
                      <li><a class="faq" href="<?php // echo Mage::getBaseUrl(); ?>faq.html">Help &amp; FAQS</a></li>
                      <?php /* */ ?>
                      <?php echo $this->getChildHtml('rma_footer_links') ?>
                </ul>
            </div>
            <div class="parts">
                <ul>
                </ul>
            </div>
            <div class="parts">
                <ul>
                    <li><a href="<?php echo Mage::getBaseUrl() ?>oem-parts/can-am.html">can-am parts</a></li>
                    <li><a href="<?php echo Mage::getBaseUrl() ?>oem-parts/honda.html">honda parts</a></li>
                    <li><a href="<?php echo Mage::getBaseUrl() ?>oem-parts/kawasaki.html">kawasaki parts</a></li>
                    <li><a href="<?php echo Mage::getBaseUrl() ?>oem-parts/polaris.html">polaris parts</a></li>
                    <li><a href="<?php echo Mage::getBaseUrl() ?>oem-parts/sea-doo.html">sea-doo parts</a></li>
                    <li><a href="<?php echo Mage::getBaseUrl() ?>oem-parts/victory.html">victory parts</a></li>
                    <li><a href="<?php echo Mage::getBaseUrl() ?>oem-parts/yamaha.html">yamaha parts</a></li>
                    <li class="last"><a href="<?php echo Mage::getBaseUrl() ?>oem-parts/suzuki.html">suzuki parts</a></li>
                </ul>
            </div>
            <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('socials')->toHtml(); ?>
            <script type="text/javascript">decorateGeneric($$('.foot-left h3'), ['first', 'last'])</script>
            <div class="crystal"></div>
        </div>

        <div class="foot-right">
            <div class="topfoot">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer-tops2')->toHtml(); ?>
                <div class="crystal"></div>
            </div>
            <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer-tops')->toHtml(); ?>
            <div class="crystal"></div>
            <div class="cols-con">
                <div class="cols-con-col col01">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('links-footer-col1')->toHtml(); ?>
                    <?php echo $this->getChildHtml('rma_footer_links') ?>
                </div>
                <div class="cols-con-col col02">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('links-footer-col2')->toHtml(); ?>
                </div>
                <div class="cols-con-col col03">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('links-footer-col3')->toHtml(); ?>
                </div>
                <div class="cols-con-col col04">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('links-footer-col4')->toHtml(); ?>
                </div>

                <div class="crystal"></div>
                <div class="col05">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('links-footer-col5')->toHtml(); ?>
                    <div class="crystal"></div>
                </div>

                <div class="footer-payment-method-wrap">
                    <div class="footer-payment-method-title">Payment Methods</div>
                    <div class="footer-payment-method-icons">
                        <img src="<?php echo $this->getSkinUrl('images/payment-methods/visa.jpg'); ?>" alt="Visa" />
                        <img src="<?php echo $this->getSkinUrl('images/payment-methods/master-card.jpg'); ?>" alt="MasterCard" />
                        <img src="<?php echo $this->getSkinUrl('images/payment-methods/discover.jpg'); ?>" alt="Discover" />
                        <img src="<?php echo $this->getSkinUrl('images/payment-methods/american-express.jpg'); ?>" alt="American Express" />
                        <img src="<?php echo $this->getSkinUrl('images/payment-methods/paypal.jpg'); ?>" alt="Paypal" />
                        <img src="<?php echo $this->getSkinUrl('images/payment-methods/paypal-credit.jpg'); ?>" alt="Paypal Credit" />
                    </div>
                    <div class="footer-payment-norton-wrap">
                        <table width="135" border="0" cellpadding="2" cellspacing="0" title="Click to Verify - This site chose Symantec SSL for secure e-commerce and confidential communications.">
                            <tr>
                                <td width="135" align="center" valign="top">
                                    <script type="text/javascript" src="https://seal.websecurity.norton.com/getseal?host_name=www.tmsparts.com&amp;size=L&amp;use_flash=YES&amp;use_transparent=YES&amp;lang=en"></script>
                                    <?php /* <br />
                                      <a href="http://www.symantec.com/ssl-certificates" target="_blank"  style="color:#000000; text-decoration:none; font:bold 7px verdana,sans-serif; letter-spacing:.5px; text-align:center; margin:0px; padding:0px;">ABOUT SSL CERTIFICATES</a>
                                     */ ?>
                                </td>

                            </tr>
                        </table>
                    </div>
                    <div class="footer-payment-heartland-wrap">
						<a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/footer/Heartland_Secure.jpg' ?>" title="Heartland Secure logo" target="_blank"><img src="<?php echo $this->getSkinUrl('images/footer/HeartlandSecure.jpg') ?>" /></a>
					</div>
					<div class="crystal"></div>
                </div>
                <script type="text/javascript">decorateGeneric($$('.col05 ul li'), ['first', 'last'])</script>

            </div>
            <div class="copyw"><?php echo preg_replace('/\d{4}/i', date('Y'), $this->getCopyright()) ?> <span>|</span> <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('links-footer-copy')->toHtml(); ?></div>
        </div>

    </div>
</div>

<?php if(
		Mage::helper('core')->isModuleEnabled('Phoenix_VarnishCache')
	&&	Mage::helper('core')->isModuleOutputEnabled('Phoenix_VarnishCache')
): ?>
	<script type="text/javascript">
		jQuery(document).ready(function() {
			if(!jQuery('input[name="form_key"]').length) return;
			jQuery.ajax({
				url: '<?php echo $this->getUrl('', array('_direct' => 'varnishcache/getformkey/')) ?>',
				cache: false,
				success: function(response) {
					jQuery('input[name="form_key"]').val(response);
				}
			});
		});
	</script>
<?php endif ?>

<?php
/*
// Google Trusted Stores Badge Code
$product = Mage::registry('product');
?>
<script type="text/javascript">
	var gts = gts || [];
	gts.push(["id", 690938]);
	gts.push(["badge_position", "BOTTOM_RIGHT"]);
	gts.push(["locale", "en"]);
	gts.push(["google_base_offer_id", "<?php echo is_object($product) ? $product->getSku() : '' ?>"]);
	gts.push(["google_base_country", "US"]);
	gts.push(["google_base_language", "en"]);
	gts.push(["google_base_subaccount_id", ""]);

	(function() {
		var gts = document.createElement("script");
		gts.type = "text/javascript";
		gts.async = true;
		gts.src = "https://www.googlecommerce.com/trustedstores/api/js";
		var s = document.getElementsByTagName("script")[0];
		s.parentNode.insertBefore(gts, s);
	})();
</script>
<?php /**/ ?>