<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */

$_menu = $this->getHtml('level-top');

?>
<?php if($_menu): ?>
<div class="li-first"></div>
<div class="li-last"></div>
<ul id="nav" class="nav-ul"><?php echo $_menu ?></ul>
<li class="featured-brands-menu" style="display: none;">
	<div id="dd-banner"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('dropdown-banner')->toHtml(); ?></div>
	<ul>
		<li class="headrmenu"><h3>featured brands:</h3></li>
		<?php echo strip_tags($this->getLayout()->createBlock('cms/block')->setBlockId('featured-brands-dropdown')->toHtml(), '<li><a>'); ?>
	</ul>
	<div class="crystal"></div>
</li>
<?php endif ?>
