<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'mobius';
$default = true;
?>
<div class="fox-gloves">
	<h1>Mobius Knee Brace Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.png' ?>" alt="Mobius" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/knee_brace.jpg' ?>" alt="Knee Brace Sizes" />
	</div>

	<h1>Knee Brace Size</h1>

	<p>Measure 6 inches above the center of your knee cap.</p>

	<div class='fox-gloves-table-header'>Knee Brace Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">SIZE</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
		</tr>
		<tr>
			<td class="title3">THIGH INCH</td>					
			<td>16-18</td>
			<td>18-20</td>
			<td>20-22</td>
		</tr>
	</table>

	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>