<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'fly'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Fly Offroad Men's, Women's, and Youth's Jersey Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="Fly" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/jersey.jpg' ?>" alt="Glove Sizes" />
	</div>

	<h1>Description</h1>

	<p>Jerseys will run slightly bigger for a good comfortable and unrestricted fit.</p>
	
	<h1>Sleeve</h1>

	<p>Measure from center of the spine at the base of the neck, around the shoulder, over the elbow and down to the wrist.</p>
	
	<h1>Chest</h1>

	<p>Measure around the broadest part of the chest 1-2 below the arm pits.</p>

	<div class='fox-gloves-table-header'>Jersey Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">JERSEY SIZE</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
			<td>3XL</td>
			<td>4XL</td>
			<td>5XL</td>
		</tr>
		<tr>
			<td class="title3">SLEEVE</td>
			<td>31-32</td>
			<td>32-33</td>
			<td>33-34</td>
			<td>34-35</td>
			<td>37</td>
			<td>38</td>
			<td>38</td>
			<td>38</td>
		</tr>
		<tr>
			<td class="title3">CHEST</td>
			<td>34-35</td>
			<td>36-38</td>
			<td>40-42</td>
			<td>44-46</td>
			<td>48-50</td>
			<td>52-54</td>
			<td>56-58</td>
			<td>60-62</td>
		 </tr>
	</table>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">WOMEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">JERSEY SIZE</td>
			<td>XS</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
		</tr>
		<tr>
			<td class="title3">SLEEVE</td>
			<td>28</td>
			<td>29</td>
			<td>30</td>
			<td>31</td>
			<td>32</td>
			<td>33</td>
		</tr>
		<tr>
			<td class="title3">BUST</td>
			<td>32</td>
			<td>35</td>
			<td>38</td>
			<td>41</td>
			<td>44</td>
			<td>48</td>
		</tr>
		<tr>
			<td class="title3">WAIST</td>
			<td>23.5-24.5</td>
			<td>25.5-26.5</td>
			<td>27.5-28.5</td>
			<td>30-31.5</td>
			<td>33-35</td>
			<td>37</td>
		</tr>
	</table>
	
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">YOUTH'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">JERSEY SIZE</td>
			<td>YS</td>
			<td>YM</td>
			<td>YL</td>
			<td>YXL</td>
		</tr>
		<tr>
			<td class="title3">SLEEVE</td>
			<td>20-21</td>
			<td>22-23</td>
			<td>24-26</td>
			<td>27-30</td>
		</tr>
		<tr>
			<td class="title3">CHEST</td>
			<td>20-22</td>
			<td>24-26</td>
			<td>28-30</td>
			<td>32-33</td>
		</tr>
	</table>
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit.</p>

</div>