<?php
?>
<div class="fari">
	<script type="text/javascript" src="https://services.arinet.com/PartStream/?appKey=9oiOWqDlvNLyUXT4Qtun"></script>	
	<style>
.fari .ariparts_btnMultiCart {
	cursor: pointer;
}
	</style>
</div>

<script type="text/javascript" src="<?php echo $this->getJsUrl('arioem/OEM.js') ?>"></script>

<script type="text/javascript">

jQuery(document).ready(function() {

	function adjustARILayout() {
		OEMCartManager.url = '<?php echo $this->getUrl('arioem/cart/add') ?>';
		ARI.PartStream.Cart.PostSkuQty = OEMCartManager.addToCartSingle.bind(OEMCartManager);
		ARI.PartStream.Cart.PostMultiSkuQty = OEMCartManager.addToCartMulti.bind(OEMCartManager);
		ARI.PartStream.Navigation.getDetailPage = function(i) {
			document.location = '<?php echo $this->getUrl('', array('_direct' => 'oem-part.html')) ?>#' + i.slug;
		};
	}

	var ariObjectWatcher = setInterval(function() {
		if(ARI) {
			adjustARILayout();
			clearInterval(ariObjectWatcher);
		} else {
			// just wait
		}
	}, 1000);
});

</script>
