<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'slippery'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Slippery Wetsuites Boot Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.png' ?>" alt="Slippery Wetsuites" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/boots.jpg' ?>" alt="Glove Sizes" />
	</div>

	<div class='fox-gloves-table-header'>Boot Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">SIZE</td>
			<td>6</td>
			<td>7</td>
			<td>8</td>
			<td>9</td>
			<td>10</td>
			<td>11</td>
			<td>12</td>
			<td>13</td>
		</tr>
		<tr>
			<td class="title3">SHOE SIZE</td>
			<td>5-6</td>
			<td>6-7</td>
			<td>7-8</td>
			<td>8-9</td>
			<td>9-10</td>
			<td>10-11</td>
			<td>11-12</td>
			<td>12-13</td>
		</tr>
	</table>
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>