<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'slippery'; // folder name
$default = false;
?>
<div class="fox-gloves">
	<h1>Slippery Wetsuites Life Jacket Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.png' ?>" alt="Slippery Wetsuites" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/life-jacket.png' ?>" alt="Life Jacket Sizes" />
	</div>
	
	<h1>Chest</h1>

	<p>Measure around the broadest part of the chest, 1-2 inches below the arm pits.</p>

	<div class='fox-gloves-table-header'>Jacket Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">SIZE</td>
			<td>XS</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
			<td>3XL</td>
		</tr>
		<tr>
			<td class="title3">CHEST</td>
			<td>28-32</td>
			<td>32-36</td>
			<td>36-40</td>
			<td>40-44</td>
			<td>44-48</td>
			<td>48-52</td>
			<td>52-56</td>
		</tr>
	</table>
	
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">WOMEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">SIZE</td>
			<td>XS</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
		</tr>
		<tr>
			<td class="title3">CHEST</td>
			<td>28-32</td>
			<td>32-36</td>
			<td>36-40</td>
			<td>40-44</td>
		</tr>
	</table>	
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit.</p>

</div>