<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;
$brand = 'fox'; // folder name
$default = true;
?>

<div class="fox-gloves">
  <h1>Fox Casual Shorts Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="Fox" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/shorts.jpg' ?>" alt="Shorts Sizes" /> </div>
  
  <h1>WAIST</h1>
  
  <p>Measure about 1 inch below top of pelvic bone.</p>
  
  <h1>INSEAM</h1>
  
  <p>Measure down from the crotch to the top of the ankle bone.</p>
  
  <div class='fox-gloves-table-header'>Casual Shorts Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
		<td class="title2">MENS</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
    </tr>
    <tr>
		<td class="title3">SIZE</td>
		<td>28</td>
		<td>29</td>
		<td>30</td>
		<td>31</td>
		<td>32</td>
		<td>33</td>
		<td>34</td>
		<td>36</td>
		<td>38</td>
		<td>40</td>
    </tr>
    <tr>
      <td class="title3">WAIST</td>
		<td>28-29</td>
		<td>29-30</td>
		<td>30-31</td>
		<td>31-32</td>
		<td>32-33</td>
		<td>33-34</td>
		<td>34-35</td>
		<td>36-37</td>
		<td>38-39</td>
		<td>40-41</td>
    </tr>
    <tr>
		<td class="title3">HIP</td>
		<td>34-35</td>
		<td>35-36</td>
		<td>36-37</td>
		<td>37-38</td>
		<td>38-39</td>
		<td>39-40</td>
		<td>40-41</td>
		<td>42-43</td>
		<td>44-45</td>
		<td>46-47</td>
    </tr>
	<tr>
		<td class="title3">INSEAM</td>
		<td>30-30 1/2</td>
		<td>30-30 1/2</td>
		<td>30 1/2-31</td>
		<td>30 1/2-31</td>
		<td>31-31 1/2</td>
		<td>31-31 1/2</td>
		<td>31 1/2-32</td>
		<td>32-32 1/2</td>
		<td>32 1/2-33</td>
		<td>32 1/2-33</td>
    </tr>
	<tr>
		<td class="title3">HEIGHT</td>
		<td>5'6-5'8</td>
		<td>5'6-5'8</td>
		<td>5'8-5'10</td>
		<td>5'8-5'10</td>
		<td>5'10-6</td>
		<td>5'10-6</td>
		<td>6-6'2</td>
		<td>6'1-6'3</td>
		<td>6'1-6'3</td>
		<td>6'1-6'3</td>
    </tr>
  </table>
  
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
