<?php
?>
<div class="fitment-page clearer">

	<h1 class="category-title">&nbsp;</h1>

	<div class="fitment-col-left">
		<div class="fitment-activity-container"></div>
		<div class="fitment-selector-container"></div>
		<div class="fitment-search-container"></div>
		<div class="fitment-filter-container">
		</div>
	</div>
	<div class="fitment-content">
		<div class="fitment-toolbar-container">
			<?php echo $this->getLayout()->createBlock('fitment/fitment_toolbar')->toHtml() ?>
		</div>
		<div class="fitment-pager-top fitment-pager-container"></div>
		<div class="fitment-list-container">
			<div class="fitment-loading">&nbsp;</div>
		</div>
		<div class="fitment-pager-bottom fitment-pager-container"></div>
	</div>
</div>

<div class="fitment-popup-overlay" style="display:none"></div>
<div class="fitment-popup-container" style="display:none">
	<div class="fitment-popup-close">X</div>
	<div class="fitment-popup-wrapper"></div>
</div>

<script type="text/javascript">

	jQuery(document).ready(function() {
		fitment = new Fitment();
		fitment.init('<?php echo $this->getUrl('fitment/index/init') ?>');
	});

</script>
