<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'troylee'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Troy Lee Gloves Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="Troy Lee" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/glove_size.jpg' ?>" alt="Glove Sizes" />
	</div>

	<h1>Hand Length</h1>

	<p>Measure from the bottom of your palm (where it meets your wrist) to the top of your middle finger</p>

	<div class='fox-gloves-table-header'>Glove Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">GLOVE SIZE</td>
			<td>XS</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
		</tr>
		<tr>
			<td class="title3">HAND SIZE</td>
			<td>7-71/8</td>
			<td>7 1/8-7 3/8</td>
			<td>7 3/8-7 5/8</td>
			<td>7 5/8-7 7/8</td>
			<td>7 7/8-8 1/8</td>
			<td>8 1/8-8 3/8</td>
		</tr>
	</table>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">WOMEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">GLOVE SIZE</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
		</tr>
		<tr>
			<td class="title3">HAND SIZE</td>
			<td>6 5/8-6 7/8</td>
			<td>6 7/8-7 1/8</td>
			<td>7 1/8-7 3/8</td>
			<td>7 3/8-7 5/8</td>
		</tr>
	</table>
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">YOUTH'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">GLOVE SIZE</td>
			<td>YXS</td>
			<td>YS</td>
			<td>YM</td>
			<td>YL</td>
			<td>YXL</td>
		</tr>
		<tr>
			<td class="title3">HAND SIZE</td>
			<td>5 1/8-5 3/8</td>
			<td>5 3/8-5 3/4</td>
			<td>5 3/4-6</td>
			<td>6-6 1/8</td>
			<td>6 1/8-6 1/2</td>
			
		</tr>
	</table>
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>