<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>Troy Lee Offroad Open Face Helmet Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'fox/brand_logo.jpg' ?>" alt="Fox" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'fox/glove_size.jpg' ?>" alt="Glove Sizes" /> </div>
  <h1>Size Measurement</h1>
  <p>For best results use a tape measure keeping it level, measure the widest point of your head, approximately 1" above your eyebrows</p>
  <div class='fox-gloves-table-header'>Offroad Open Face Helmet Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens</td>
      <td>S</td>
      <td>M</td>
      <td>L</td>
      <td>XL</td>
      <td>2XL</td>
    </tr>
    <tr>
      <td class="title3">USA HAT SIZE</td>
      <td>6 7/8-7</td>
      <td>7 1/8-7 1/4</td>
      <td>7 3/8-7 1/2</td>
      <td>7 5/8-7 3/4</td>
      <td>7 7/8-8</td>
    </tr>
    <tr>
      <td class="title3">INCHES</td>
      <td>21.7-22</td>
      <td>22.4-22.8</td>
      <td>23.2-23.6</td>
      <td>24-24.4</td>
      <td>24.8-25.2</td>
    </tr>

  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
