<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;
$brand = 'troylee'; // folder name
$default = true;
?>

<div class="fox-gloves">
  <h1>Troy Lee Casual Shorts Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="Troy Lee" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/shorts.jpg' ?>" alt="Shorts Sizes" /> </div>
  
  <h1>WAIST</h1>
  
  <p>Measure about 1 inch below top of pelvic bone.</p>
  
  <h1>INSEAM</h1>
  
  <p>Measure down from the crotch to the top of the ankle bone.</p>
  
  <div class='fox-gloves-table-header'>Casual Shorts Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
		<td class="title2">MENS</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
    </tr>
    <tr>
		<td class="title3">SIZE</td>
		<td>S</td>
		<td>M</td>
		<td>L</td>
		<td>XL</td>
		<td>2XL</td>
		<td>3XL</td>
    </tr>
    <tr>
      <td class="title3">CHEST</td>
		<td>33-35</td>
		<td>36-39</td>
		<td>40-42</td>
		<td>43-46</td>
		<td>47-50</td>
		<td>50-52</td>
    </tr>
    <tr>
		<td class="title3">SLEEVE</td>
		<td>32-33</td>
		<td>33-34</td>
		<td>34-35</td>
		<td>35-36</td>
		<td>36-37</td>
		<td>37-38</td>
    </tr>
	
	<tr>
		<td class="title3">HEIGHT</td>
		<td>5'6-5'10</td>
		<td>5'10-6</td>
		<td>6-6'2</td>
		<td>6'1-6'3</td>
		<td>6'1-6'3</td>
		<td>6'3-6'4</td>
    </tr>
  </table>

  <table class="sizing_chart">
    <tr class="title1">
		<td class="title2">WOMEN'S</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
    </tr>
    <tr>
		<td class="title3">SIZE</td>
		<td>S    3/4</td>
		<td>M      5/6</td>
		<td>L    7/8</td>
		<td>XL 9/10</td>
    </tr>
	<tr>
		<td class="title3">WAIST</td>
		<td>29-31</td>
		<td>31-33</td>
		<td>33-35</td>
		<td>35-37</td>
    </tr>
	<tr>
		<td class="title3">INSEAM</td>
		<td>10</td>
		<td>10.5</td>
		<td>10.6</td>
		<td>11</td>
    </tr>
	
	
	</table>
  
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
