<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'alpinestars'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Alpinestars Offroad Jersey Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="Alpinestars" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/jersey.jpg' ?>" alt="Jersey Sizes" />
	</div>

	<h1>Description</h1>

	<p>Jerseys will run slightly bigger for a good comfortable and unrestricted fit.</p>
	
	<h1>Sleeve</h1>

	<p>Measure from center of the spine at the base of the neck, around the shoulder, over the elbow and down to the wrist.</p>
	
	<h1>Chest</h1>

	<p>Measure around the broadest part of the chest 1-2 below the arm pits.</p>

	<div class='fox-gloves-table-header'>Jersey Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">JERSEY SIZE</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
		</tr>
		<tr>
			<td class="title3">CHEST SIZE</td>
			<td>33-35</td>
			<td>36-39</td>
			<td>40-42</td>
			<td>43-46</td>
			<td>47-50</td>
		</tr>
		<tr>
		<td class="title3">SLEEVE SIZE</td>
			<td>32-32 1/2</td>
			<td>33-33 1/2</td>
			<td>33 1/2-34</td>
			<td>34 1/2-35</td>
			<td>35 1/2-36</td>
		</tr>
	</table>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">YOUTH</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">JERSEY SIZE</td>
			<td>YS</td>
			<td>YM</td>
			<td>YL</td>
			<td>YXL</td>
		</tr>
		<tr>
			<td class="title3">CHEST SIZE</td>
			<td>25</td>
			<td>27</td>
			<td>28</td>
			<td>29 1/2</td>
		</tr>
		<tr>
			<td class="title3">SLEEVE SIZE</td>
			<td>22</td>
			<td>23</td>
			<td>25</td>
			<td>27</td>
		</tr>
	</table>
	
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit.</p>

</div>