<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<div class="amshopby-filters-bottom-cms">
    <?php
    $blocks = Mage::registry('amshopby_bottom_cms');
    if (is_array($blocks)) {
        foreach ($blocks as $block) {
            /** @var Mage_Cms_Block_Block $block */
            echo $block->toHtml();
        }
    }
    ?>
</div>
