<?php
$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;
 
$brand = 'yamaha'; // folder name
$default = true;
?>

<div class="fox-gloves">
  <h1>Yamaha Boot Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="Yamaha" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/boots.jpg' ?>" alt="Boot Sizes" /> </div>
  <div class='fox-gloves-table-header'>Boot Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
		<td class="title2">MENS</td>
		<td>Race Boot</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
    </tr>
    <tr>
		<td class="title3">size</td>
		<td>XS</td>
		<td>S</td>
		<td>M</td>
		<td>L</td>
		<td>XL</td>
		<td>2XL</td>
    </tr>
	<tr>
		<td class="title3">Shoe size</td>
		<td>6-6.5</td>
		<td>7.7.5</td>
		<td>8-8.5</td>
		<td>9-9.5</td>
		<td>10-10.5</td>
		<td>11-11.5</td>
    </tr>    
  </table>
  
  <table class="sizing_chart">
    <tr class="title1">
		<td class="title2">Womens</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
    </tr>
    <tr>
		<td class="title3">size</td>
		<td>XS</td>
		<td>S</td>
		<td>M</td>
		<td>L</td>
    </tr>
	<tr>
		<td class="title3">Shoe size</td>
		<td>8-8.5</td>
		<td>9-9.5</td>
		<td>10-10.5</td>
		<td>11-1.5</td>
    </tr>    
  </table>
  
  <table class="sizing_chart">
    <tr class="title1">
		<td class="title2">Mens</td>
		<td>Amp Boot</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
    </tr>
    <tr>
		<td class="title3">size</td>
		<td>XXS</td>
		<td>XS</td>
		<td>S</td>
		<td>M</td>
		<td>L</td>
		<td>XL</td>
		<td>2XL</td>
    </tr>
	<tr>
		<td class="title3">Shoe size</td>
		<td>5/6</td>
		<td>6/7</td>
		<td>7/8</td>
		<td>8/9</td>
		<td>9/10</td>
		<td>11/12</td>
		<td>12/13</td>
    </tr>    
  </table>
  
  <table class="sizing_chart">
    <tr class="title1">
		<td class="title2">Womens</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
    </tr>
    <tr>
		<td class="title3">size</td>
		<td>XXS</td>
		<td>XS</td>
		<td>S</td>
		<td>M</td>
		<td>L</td>
		<td>XL</td>
    </tr>
	<tr>
		<td class="title3">Shoe size</td>
		<td>5/6</td>
		<td>6/7</td>
		<td>8/9</td>
		<td>9/10</td>
		<td>10/11</td>
		<td>11/12</td>
    </tr>    
  </table>
 
  <p>&nbsp;</p>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
