<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'moose'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Moose Racing Boot Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.png' ?>" alt="Moose Racing" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/boots.jpg' ?>" alt="Glove Sizes" />
	</div>

	<div class='fox-gloves-table-header'>Boot Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">US</td>
			<td>13</td>
			<td>1</td>
			<td>2</td>
			<td>3</td>
			<td>4</td>
			<td>5</td>
			<td>6</td>
			<td>7</td>
			<td>8</td>
			<td>9</td>
			<td>10</td>
			<td>11</td>
			<td>12</td>
			<td>13</td>
			<td>14</td>
		</tr>
		<tr>
			<td class="title3">EURO</td>
			<td>32</td>
			<td>33</td>
			<td>34.5</td>
			<td>35.5</td>
			<td>37</td>
			<td>38</td>
			<td>39.5</td>
			<td>40.5</td>
			<td>42</td>
			<td>43.5</td>
			<td>44.5</td>
			<td>46</td>
			<td>47</td>
			<td>48.5</td>
			<td>49.5</td>
		</tr>
		<tr>
			<td class="title3">JPN</td>
			<td>21.5</td>
			<td>22</td>
			<td>22.5</td>
			<td>23.5</td>
			<td>24</td>
			<td>24.5</td>
			<td>25</td>
			<td>26</td>
			<td>26.5</td>
			<td>27</td>
			<td>28</td>
			<td>28.5</td>
			<td>29</td>
			<td>29.5</td>
			<td>30.5</td>
		</tr>
	</table>
	
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">WOMEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">EURO</td>
			<td>36</td>
			<td>37</td>
			<td>38</td>
			<td>39</td>
			<td>40</td>
			<td>41</td>
			<td>42</td>
			<td>43</td>
			<td>44</td>
		</tr>
		<tr>
			<td class="title3">US</td>
			<td>5</td>
			<td>6</td>
			<td>7</td>
			<td>8</td>
			<td>8.5</td>
			<td>9</td>
			<td>10</td>
			<td>11</td>
			<td>11.5</td>
		</tr>
		<tr>
			<td class="title3">JPN</td>
			<td>22.5</td>
			<td>23</td>
			<td>24</td>
			<td>25</td>
			<td>25.5</td>
			<td>26</td>
			<td>26.5</td>
			<td>27.5</td>
			<td>28</td>
		</tr>
	</table>
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>