<div class="the-tireshop">
	<h2 class="hdr-under-over">Tire Shop</h2>
	<div class="tireshop-banner">
		<img src="<?php echo $this->getSkinUrl('images/cms/tireshop/tireshopbanner.jpg');?>" alt="" />
	</div>

	<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('vk_fitment/tireshop/container.phtml')->toHtml() ?>

	<link rel="stylesheet" href="<?php echo $this->getSkinUrl('vk_fitment/css/tireshop.css') ?>">
	<?php // echo $this->getLayout()->createBlock('core/template')->setTemplate('vk_fitment/tireshop/contentdraft.phtml')->toHtml() ?>

</div>