<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'cortech';
$default = true;
?>
<div class="fox-gloves">
	<h1>Cortech Boot Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.png' ?>" alt="Cortech" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/boots.jpg' ?>" alt="Boot Sizes" />
	</div>

	<h1>Boot Size</h1>

	<p>Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

	<div class='fox-gloves-table-header'>Boot Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">US</td>
			<td>7</td>
			<td>8</td>
			<td>8.5</td>
			<td>9</td>
			<td>10</td>
			<td>11</td>
			<td>12</td>
			<td>12.5</td>
			<td>13</td>
			<td>14</td>
		</tr>
		<tr>
			<td class="title3">EURO</td>					
			<td>40</td>
			<td>41</td>
			<td>42</td>
			<td>43</td>
			<td>44</td>
			<td>45</td>
			<td>46</td>
			<td>47</td>
			<td>48</td>
			<td>49</td>
		</tr>
	</table>

</div>