<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'cortech'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Cortech One Piece Suit Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.png' ?>" alt="Cortech" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/suit.jpg' ?>" alt="One Piece Suit Sizes" />
	</div>
	
	<h1>SLEEVE</h1>

	<p>Measure from the center of spine at the base of the neck, around the shoulder, over the elbow and down to the wrist.</p>

	<h1>CHEST</h1>

	<p>Measure around the broadest part of the chest, 1-2  inches below the arm pits.</p>

	<h1>WAIST</h1>

	<p>Measure about 1 inch below top of pelvic bone.</p>
	
	<h1>INSEAM</h1>

	<p>Measure down from the crotch to the top of the ankle bone.</p>

	<h1>HEIGHT</h1>

	<p>Measure how tall you are.</p>

	<div class='fox-gloves-table-header'>One Piece Suit Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">SIZE</td>
			<td>XS</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
		</tr>
		<tr>
			<td class="title3">CHEST</td>
			<td>38</td>
			<td>40</td>
			<td>42</td>
			<td>44</td>
			<td>46</td>
		</tr>
		<tr>
			<td class="title3">WAIST</td>
			<td>32</td>
			<td>34</td>
			<td>36</td>
			<td>38</td>
			<td>40</td>
		</tr>
		<tr>
			<td class="title3">SLEEVE</td>
			<td>25.5</td>
			<td>26</td>
			<td>26.5</td>
			<td>27</td>
			<td>27.5</td>
		</tr>
		<tr>
			<td class="title3">HEIGHT</td>
			<td>5'9-5'10</td>
			<td>5'10-5'11</td>
			<td>5'11-6</td>
			<td>6-6'1</td>
			<td>6'1-6'3</td>
		</tr>
		<tr>
			<td class="title3">INSEAM</td>
			<td>31</td>
			<td>31.5</td>
			<td>32</td>
			<td>32.5</td>
			<td>33</td>
		</tr>
	</table>
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>