<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>Arctiva Cruiser Jacket Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'arctiva/brand_logo.jpg' ?>" alt="Arctiva" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'arctiva/jersey.jpg' ?>" alt="Cruiser Jacket Sizes" /> </div>
  <h1>Size Measurement</h1>
  <p>Sleeve : Measure from the center of spine at the base of the neck, around the shoulder, over the elbow and down to the wrist.</p>
  <p>Chest: Measure around the broadest part of the chest, 1-2 inches below the arm pits.</p>
  <div class='fox-gloves-table-header'>Cruiser Jacket Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens</td>
      <td>XS</td>
      <td>S</td>
      <td>M</td>
      <td>L</td>
      <td>XL</td>
      <td>2XL</td>
      <td>3XL</td>
      <td>4XL</td>
    </tr>
    <tr>
      <td class="title3">CHEST SIZE</td>
      <td>38-40</td>
      <td>40-42</td>
      <td>42-44</td>
      <td>44-46</td>
      <td>46-48</td>
      <td>48-50</td>
      <td>50-52</td>
      <td>52-54</td>
    </tr>
    <tr>
      <td class="title3">SLEEVE LENGTH</td>
      <td>24</td>
      <td>24.5</td>
      <td>25</td>
      <td>25.5</td>
      <td>26</td>
      <td>26.5</td>
      <td>27</td>
      <td>27.5</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
