<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;
 
?>

<div class="fox-gloves">
  <h1>Thor Offroad Pant Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'thor/brand_logo.jpg' ?>" alt="Thor" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'thor/pants.jpg' ?>" alt="Pants Sizes" /> </div>
  <h1>Size Measurement</h1>
  <p>Waist-Measure about 1 inch below top of pelvic bone.</p>
  <p>Inseam-Measure down from the crotch to the top of the ankle bone.</p>
  <div class='fox-gloves-table-header'>Offroad Pant Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr class="title1">
      <td class="title2">PANT SIZE</td>
      <td>28</td>
      <td>30</td>
      <td>32</td>
      <td>34</td>
      <td>36</td>
      <td>38</td>
      <td>40</td>
      <td>42</td>
      <td>44</td>
      <td>46</td>
      <td>48</td>
    </tr>
    <tr>
      <td class="title3">WAIST SIZE</td>
      <td>27-28</td>
      <td>29-30</td>
      <td>31-32</td>
      <td>33-34</td>
      <td>35-36</td>
      <td>37-38</td>
      <td>39-40</td>
      <td>41-42</td>
      <td>43-44</td>
      <td>45-46</td>
      <td>47-48</td>
    </tr>
    <tr>
      <td class="title3">INSEAM SIZE</td>
      <td>27.1</td>
      <td>28.5</td>
      <td>29.3</td>
      <td>30.1</td>
      <td>30.9</td>
      <td>30.9</td>
      <td>31</td>
      <td>31.4</td>
      <td>31.5</td>
      <td>31.6</td>
      <td>31.7</td>
    </tr>
  </table>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Womens</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr class="title1">
      <td class="title2">PANT SIZE</td>
      <td>3/4</td>
      <td>5/6</td>
      <td>7/8</td>
      <td>9/10</td>
      <td>11/12</td>
      <td>13/14</td>
    </tr>
    <tr>
      <td class="title3">WAIST SIZE</td>
      <td>24</td>
      <td>26</td>
      <td>28</td>
      <td>30</td>
      <td>32</td>
      <td>34</td>
    </tr>
    <tr>
      <td class="title3">INSEAM SIZE</td>
      <td>26.5</td>
      <td>27.3</td>
      <td>28</td>
      <td>28.8</td>
      <td>29.5</td>
      <td>30.3</td>
    </tr>
  </table>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Youth</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr class="title1">
      <td class="title2">PANT SIZE</td>
      <td>Y18</td>
      <td>Y20</td>
      <td>Y22</td>
      <td>Y24</td>
      <td>Y26</td>
      <td>Y28</td>
    </tr>
    <tr>
      <td class="title3">WAIST SIZE</td>
      <td>17-18</td>
      <td>19-20</td>
      <td>21-22</td>
      <td>23-24</td>
      <td>25-26</td>
      <td>27-28</td>
    </tr>
    <tr>
      <td class="title3">INSEAM SIZE</td>
      <td>16.2</td>
      <td>20.3</td>
      <td>22.3</td>
      <td>23.6</td>
      <td>25.1</td>
      <td>26</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
