<?php if(Mage::helper('conversionpro')->isLivesightEnabled()): ?>
<!-- BEGIN: LiveSight.Celebros-->
    <script type="text/javascript">
    (function()
      {
        var ms = document.createElement("script");
        var site = ("https:" == document.location.protocol) ? "https://col-ls.celebros.com/cjs.aspx" : "http://col-ls.celebros.com/cjs.aspx";
        ms.src = site;
        ms.setAttribute("async", "true");
        document.documentElement.firstChild.appendChild(ms);
      })();
    </script>
<!-- END: LiveSight.Celebros -->
<?php endif?>