<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'polaris'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Polaris Offroad Helmet Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.png' ?>" alt="Polaris" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/helmet.jpg' ?>" alt="Helmet Sizes" />
	</div>

	<h1>Description</h1>

	<p>For best Results use a tape measure keeping it level, measure the widest point of your head, approximately 1" above your eyebrows.</p>
	
	<div class='fox-gloves-table-header'>Helmet Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">HELMET SIZE</td>
			<td>XS</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
		</tr>
		<tr>
			<td class="title3">USA HAT SIZE</td>
			<td>6 5/8-6 3/4</td>
			<td>6 7/8-7</td>
			<td>7 1/8-7 1/4</td>
			<td>7 3/8-7 1/2</td>
			<td>7 5/8-7 3/4</td>
			<td>7 3/4-8</td>
		</tr>
		<tr>
			<td class="title3">INCHES</td>
			<td>20.50-21.25</td>
			<td>21.25-22.00</td>
			<td>22.00-23.00</td>
			<td>23.00-23.75</td>
			<td>24.00-24.50</td>
			<td>24.50-25.25</td>
		</tr>
	</table>
	
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">YOUTH</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">HELMET SIZE</td>
			<td>YS</td>
			<td>YM</td>
			<td>YL</td>
		</tr>
		<tr>
			<td class="title3">USA HAT SIZE</td>
			<td>5 7/8-6</td>
			<td>6 1/8-6 1/4</td>
			<td>6 3/8-6 1/2</td>
		</tr>
		<tr>
			<td class="title3">INCHES</td>
			<td>18.25-19.00</td>
			<td>19.00-19.75</td>
			<td>19.75-20.5</td>
		</tr>
	</table>
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>