<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'afx'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>AFX Offroad Men's and Youth's Helmet Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="AFX" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/helmet.jpg' ?>" alt="Helmet Sizes" />
	</div>

	<h1>Description</h1>

	<p>For best Results use a tape measure keeping it level, measure the widest point of your head, approximately 1" above your eyebrows.</p>
	
	<div class='fox-gloves-table-header'>Helmet Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">HELMET SIZE</td>
			<td>XXS</td>
			<td>XS</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
			<td>3XL</td>
			<td>4XL</td>
		</tr>
		<tr>
			<td class="title3">USA HAT SIZE</td>
			<td>6 3/8-6 1/2</td>
			<td>6 5/8-6 3/4</td>
			<td>6 7/8-7</td>
			<td>7 1/8-7 1/4</td>
			<td>7 3/8-7 1/2</td>
			<td>7 5/8-7 3/4</td>
			<td>7 7/8-8</td>
			<td>8 1/8-8 1/4</td>
			<td>8 3/8-8 1/2</td>
		</tr>
		<tr>
			<td class="title3">INCHES</td>
			<td>20-20 1/2</td>
			<td>20 7/8-21 1/4</td>
			<td>21 5/8-22</td>
			<td>22 1/2-22 7/8</td>
			<td>23 1/4-23 5/8</td>
			<td>24-24 3/8</td>
			<td>24 3/4-25 1/4</td>
			<td>25 5/8-26</td>
			<td>26 3/8-26 3/4</td>
		</tr>
	</table>
	
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">YOUTH'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">HELMET SIZE</td>
			<td>YS</td>
			<td>YM</td>
			<td>YL</td>
			<td>YS/M</td>
			<td>YL/XL</td>
		</tr>
		<tr>
			<td class="title3">USA HAT SIZE</td>
			<td>6 1/8-6 1/4</td>
			<td>6 3/8-6 1/2</td>
			<td>6 5/8-6 3/4</td>
			<td>6 1/8-6 1/4</td>
			<td>6 3/8-6 1/2</td>
		</tr>
		<tr>
			<td class="title3">INCHES</td>
			<td>19 1/4-19 3/4</td>
			<td>20-20 1/2</td>
			<td>20 7/8-21 1/4</td>
			<td>19 1/4-19 3/4</td>
			<td>20-20 1/2</td>
		</tr>
	</table>
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>