<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>O'Neal Offroad Pant Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'fox/brand_logo.jpg' ?>" alt="Fox" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'fox/glove_size.jpg' ?>" alt="Glove Sizes" /> </div>
  <h1>Size Measurement</h1>
  <p>INSEAM: While standing without shoes and with feet slightly apart, measure from the crotch along the leg to the floor.</p>
  <p>WAIST: With a tape measure about 1 inch below the pelvis bone and holding it level, measure the circumference at the waist while standing with natural bend.</p>
  <div class='fox-gloves-table-header'>Offroad Pant Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="title3">PANT SIZE</td>
      <td>28</td>
      <td>30</td>
      <td>32</td>
      <td>34</td>
      <td>36</td>
      <td>38</td>
      <td>40</td>
      <td>42</td>
      <td>44</td>
      <td>46</td>
      <td>48</td>
      <td>50</td>
    </tr>
    <tr>
      <td class="title3">WAIST SIZE</td>
      <td>27-29</td>
      <td>29-31</td>
      <td>31-33</td>
      <td>33-35</td>
      <td>35-37</td>
      <td>37-39</td>
      <td>39-41</td>
      <td>41-43</td>
      <td>43-45</td>
      <td>45-47</td>
      <td>47-49</td>
      <td>49-51</td>
    </tr>
    <tr>
      <td class="title3">INSEAM SIZE</td>
      <td>30</td>
      <td>30-30 1/2</td>
      <td>30 1/2-31</td>
      <td>31-31 1/2</td>
      <td>31 1/2-32</td>
      <td>32-32 1/2</td>
      <td>32 1/2</td>
      <td>32 1/2</td>
      <td>32 1/2</td>
      <td>32 1/2</td>
      <td>32 1/2</td>
      <td>32 1/2</td>
    </tr>
  </table>
  
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Womens</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="title3">PANT SIZE</td>
      <td>1/2</td>
      <td>3/4</td>
      <td>5/6</td>
      <td>7/8</td>
      <td>9/10</td>
      <td>11/12</td>
      <td>13/14</td>
    </tr>
    <tr>
      <td class="title3">WAIST SIZE</td>
      <td>25</td>
      <td>26</td>
      <td>27</td>
      <td>28 1/2</td>
      <td>30</td>
      <td>31 1/2</td>
      <td>33</td>
    </tr>
    <tr>
      <td class="title3">INSEAM SIZE</td>
      <td>29</td>
      <td>29 1/2</td>
      <td>29 1/2</td>
      <td>30</td>
      <td>30</td>
      <td>30 1/2</td>
      <td>30 1/2</td>
    </tr>    
  </table>
  
  
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Youth</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="title3">PANT SIZE</td>
      <td>Y2/3</td>
      <td>Y4/5</td>
      <td>Y5/6</td>
      <td>Y8/10</td>
      <td>Y12/14</td>
      <td>YTH 28</td>
    </tr>
    <tr>
      <td class="title3">WAIST SIZE</td>
      <td>18</td>
      <td>20</td>
      <td>22</td>
      <td>24</td>
      <td>26</td>
      <td>27</td>
    </tr>
    <tr>
      <td class="title3">INSEAM SIZE</td>
      <td>18</td>
      <td>19</td>
      <td>20</td>
      <td>20</td>
      <td>21 1/2</td>
      <td>24</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
