<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>O'Neal Offroad Jersey Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'fox/brand_logo.jpg' ?>" alt="Fox" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'fox/glove_size.jpg' ?>" alt="Glove Sizes" /> </div>
  <h1>Size Measurement</h1>
  <p>Compare one of your t-shirts with the corresponding size chart. Choose the same size as you would for a t-shirt. Note that jerseys typically run larger for a loose, unrestricted fit.</p>
  <p>Sleeve: Measure from center of the spine at the base of the neck, around the shoulder,over the elbow and down to the wrist</p>
  <p>Chest: Measure around the broadest part of the chest 1-2 below the arm pits.</p>
  <div class='fox-gloves-table-header'>Offroad Jersey Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens</td>
      <td>S</td>
      <td>M</td>
      <td>L</td>
      <td>XL</td>
      <td>2XL</td>
      <td>3XL</td>
      <td>4XL</td>
    </tr>
    <tr>
      <td class="title3">CHEST SIZE</td>
      <td>32-33</td>
      <td>34-35</td>
      <td>36-38</td>
      <td>40-42</td>
      <td>44-46</td>
      <td>48-52</td>
      <td>54-56</td>
    </tr>
    <tr>
      <td class="title3">CHEST</td>
      <td>33</td>
      <td>34</td>
      <td>35 1/4</td>
      <td>36 1/4</td>
      <td>37</td>
      <td>38 1/2</td>
      <td>39 1/2</td>
    </tr>
  </table>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Womens</td>
      <td>S</td>
      <td>M</td>
      <td>L</td>
      <td>XL</td>
      <td>2XL</td>
    </tr>
    <tr>
      <td class="title3">CHEST SIZE</td>
      <td>34</td>
      <td>36</td>
      <td>37 1/2</td>
      <td>39</td>
      <td>40 1/2</td>
    </tr>
    <tr>
      <td class="title3">CHEST</td>
      <td>30</td>
      <td>31</td>
      <td>32</td>
      <td>33 1/2</td>
      <td>34 1/4</td>
    </tr>
  </table>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Youth</td>
      <td>YS</td>
      <td>YM</td>
      <td>YL</td>
      <td>YXL</td>
      <td>12/14</td>
      <td>YTH28</td>
    </tr>
    <tr>
      <td class="title3">CHEST SIZE</td>
      <td>24</td>
      <td>27</td>
      <td>31</td>
      <td>35</td>
      <td>26</td>
      <td>27</td>
    </tr>
    <tr>
      <td class="title3">CHEST</td>
      <td>24 1/2</td>
      <td>26</td>
      <td>28 1/2</td>
      <td>30 1/4</td>
      <td>31</td>
      <td>31 1/4</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
