<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>O'Neal Offroad Boot Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'fox/brand_logo.jpg' ?>" alt="Fox" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'fox/glove_size.jpg' ?>" alt="Glove Sizes" /> </div>
  <h1>Size Measurement</h1>
  <p>INSEAM: While standing without shoes and with feet slightly apart, measure from the crotch along the leg to the floor.</p>
  <p>WAIST: With a tape measure about 1 inch below the pelvis bone and holding it level, measure the circumference at the waist while standing with natural bend.</p>
  <div class='fox-gloves-table-header'>Offroad Boot Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Womens</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="title3">BOOT SIZE</td>
      <td>5</td>
      <td>6</td>
      <td>7</td>
      <td>8</td>
      <td>9</td>
      <td>10</td>
      <td>11</td>
      <td>12</td>
      <td>13</td>
    </tr>
    <tr>
      <td class="title3">FOOT SIZE IN INCHES</td>
      <td>8.5</td>
      <td>8.875</td>
      <td>9.25</td>
      <td>9.5</td>
      <td>9.875</td>
      <td>10.1875</td>
      <td>10.5</td>
      <td>10.9375</td>
      <td>11.25</td>
    </tr>    
  </table>
  
  
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Youth</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="title3">BOOT SIZE</td>
      <td>Y12</td>
      <td>Y13</td>
      <td>Y1</td>
      <td>Y2</td>
      <td>Y3</td>
      <td>Y4</td>
      <td>Y5</td>
      <td>Y6</td>
    </tr>
    <tr>
      <td class="title3">FOOT SIZE IN INCHES</td>
      <td>7.125</td>
      <td>7.5</td>
      <td>7.75</td>
      <td>8.125</td>
      <td>8.5</td>
      <td>8.75</td>
      <td>9.125</td>
      <td>9.5</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
