<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>Allsport Dynamics ATV Ankle Support Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'allsport/brand_logo.jpg' ?>" alt="Allsport Dynamics" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'allsport/boots.jpg' ?>" alt="ATV Ankle Support Sizes" /> </div>
  <h1>Size Measurement</h1>
  <p>Ankle size is determined by shoe size. </p>
  <div class='fox-gloves-table-header'>ATV Ankle Support Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens</td>
      <td>S</td>
      <td>M</td>
      <td>L</td>
      <td>XL</td>
    </tr>
    <tr>
      <td class="title3">SHOE SIZE</td>
      <td>6-8</td>
      <td>8-10</td>
      <td>10-12</td>
      <td>12-14</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
