<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>Allsport Dynamics Street Wrist Brace Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'allsport/brand_logo.jpg' ?>" alt="Allsport Dynamics" /></div>
  <h1>Size Measurement</h1>
  <p>Ankle size is determined by shoe size. </p>
  <div class='fox-gloves-table-header'>Street Wrist Brace Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens</td>
      <td>OSFA</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
