<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'suzuki'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Suzuki Helmet Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.png' ?>" alt="Suzuki" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/helmet.jpg' ?>" alt="Helmet Sizes" />
	</div>

	<h1>Description</h1>

	<p>For best Results use a tape measure keeping it level, measure the widest point of your head, approximately 1" above your eyebrows.</p>
	
	<div class='fox-gloves-table-header'>Helmet Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">HELMET SIZE</td>
			<td>XS</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
			<td>3XL</td>
		</tr>
		<tr>
			<td class="title3">USA HAT SIZE</td>
			<td>6 3/4</td>
			<td>7-7 1/8</td>
			<td>7 1/4-7 3/8</td>
			<td>7 1/2-7 5/8</td>
			<td>7 3/4-7 7/8</td>
			<td>8-8 1/8</td>
			<td>8 1/4-8 3/8</td>
		</tr>
		<tr>
			<td class="title3">INCHES</td>
			<td>21 1/4-21 5/8</td>
			<td>22-227/16</td>
			<td>22 13/16-23 1/4</td>
			<td>23 5/8-24</td>
			<td>24 3/8-24 13/16</td>
			<td>25 3/16-25 5/8</td>
			<td>26-26 3/8</td>
		</tr>
	</table>
	
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">YOUTH</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">HELMET SIZE</td>
			<td>YS</td>
			<td>YS/M</td>
			<td>YM</td>
			<td>YL/XL</td>
			<td>YL</td>
		</tr>
		<tr>
			<td class="title3">USA HAT SIZE</td>
			<td>6 1/4-6 3/8</td>
			<td>6 1/4-6 3/8</td>
			<td>6 1/2-6 5/8</td>
			<td>6 1/2-6 5/8</td>
			<td>6 11/16</td>
		</tr>
		<tr>
			<td class="title3">INCHES</td>
			<td>19 11/16-20 1/16</td>
			<td>19 11/16-20 1/16</td>
			<td>20 7/16-20 7/8</td>
			<td>20 7/16-20 7/8</td>
			<td>21</td>
		</tr>
	</table>
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>