<?php
?>
<div class="wsap-success">
	<h1>Dealer Corner Application</h1>

	<h2>Your application has been sent</h2>

	<p>We are as excited as you are to do business together, but we need to take care of a few business functions to complete your dealer account registration, if you'd like to get a hole shot on your dealer account registration, please do these steps below a.s.a.p.</p>

	<p>(Mandatory All Dealers) <br/>
		Please print out our <a href="<?php echo $this->getUrl('', array('_direct' => 'media/wysiwyg/TMSPARTS.COM CREDIT CARD AUTHORIZATION FORM.pdf')) ?>" target="_blank">Credit Card Authorization Form</a><p>

	<p><strong>Please email this form, along with a photo copy of your driver's license and credit card to <a href="mailto:info@temeculamotorsports.com">info@temeculamotorsports.com</a> or fax to 951-493-8808</strong></p>

	<p>(Applies to dealers located in California only)<br/>
		If you are located in the state of California we will need to have you submit a CA resale certificate to us prior to ordering any parts.</p>

	<p>Click here to download the <a href="http://www.boe.ca.gov/pdf/boe230.pdf">CA resale certificate</a></p>

	<p>It is very important that line  2 and 5 of the CA resale certificate say the following:
		<strong>POWERSPORTS PARTS AND ACCESSORIES</strong><br/>
		And also that line 3 of the CA resale certificate says the following:
		<strong>TEMECULA MOTORSPORTS INC.</strong>
	</p>

	<p><strong>If applicable please email this CA RESALE CERTIFICATE form to <a href="mailto:info@temeculamotorsports.com">info@temeculamotorsports.com</a> or fax to 951-493-8808</strong></p>

	<p>We'll consider your dealer application in the sooner time and inform you on the result, whatever it will be.</p>

	<p>You'll be emailed. However, you can also check the status of your application at <a href="<?php echo $this->getUrl('wholesale/dealer/corner') ?>"><?php echo $this->__('Customer Account') ?></a> area.</p>

	<p><a href="<?php echo $this->getUrl('') ?>"><?php echo $this->__('Continue shopping') ?></a></p>

	<p>Thank you for your interest in doing business with <a href="www.TMSparts.com">www.TMSparts.com</a></p>

	<p><br>
		Sincerely,<br/>
		<br/>
		JD Dominick<br/>
		<br/>
		Dealer Account Manager<br/>
		EMAIL: <a href="mailto:info@temeculamotorsports.com">info@temeculamotorsports.com</a>
	</p>

</div>