<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'slippery'; // folder name
$default = false;
?>
<div class="fox-gloves">
	<h1>Slippery Wetsuites Gloves Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.png' ?>" alt="Slippery Wetsuites" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/glove_size.png' ?>" alt="Glove Sizes" />
	</div>

	<h1>Glove Size</h1>

	<p>Measure from the bottom of your palm (where it meets your wrist) to the top of your middle finger.</p>

	<div class='fox-gloves-table-header'>Glove Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">GLOVE SIZE</td>
			<td>XS</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
		</tr>
		<tr>
			<td class="title3">INCHES</td>
			<td>5-5 1/2</td>
			<td>6-6 1/2</td>
			<td>7- 7 1/2</td>
			<td>8-8 1/2</td>
			<td>9-9 1/2</td>
			<td>10-10 1/2</td>
		</tr>
	</table>
	
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">WOMENS</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">SIZE</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>S/M</td>
			<td>M/L</td>
		</tr>
		<tr>
			<td class="title3">INCHES</td>
			<td>5 1/2-6</td>
			<td>6-6 1/2</td>
			<td>7-7 1/2</td>
			<td>5 1/2-6 1/2</td>
			<td>6-7 1/2</td>
		</tr>
	</table>
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>