<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'alpinestars';
$default = true;
?>
<div class="fox-gloves">
	<h1>Alpinestars Offroad Boot Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="Answer" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/boots.jpg' ?>" alt="Boot Sizes" />
	</div>

	<h1>Boot Size</h1>

	<p>Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

	<div class='fox-gloves-table-header'>Boot Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">EURO</td>
			<td>36</td>
			<td>37</td>
			<td>38</td>
			<td>39</td>
			<td>40</td>
			<td>41</td>
			<td>42</td>
			<td>43</td>
			<td>44</td>
			<td>45</td>
			<td>46</td>
			<td>47</td>
			<td>48</td>
			<td>49</td>
			<td>50</td>
		</tr>
		<tr>
			<td class="title3">US</td>					
			<td>3.5</td>
			<td>4</td>
			<td>5</td>
			<td>6</td>
			<td>6.5</td>
			<td>7.5</td>
			<td>8</td>
			<td>9</td>
			<td>9.5</td>
			<td>10.5</td>
			<td>11.5</td>
			<td>12</td>
			<td>12.5</td>
			<td>13.5</td>
			<td>14</td>	
		</tr>
		<tr>
			<td class="title3">JPN</td>
			<td>22.5</td>
			<td>23</td>
			<td>24</td>
			<td>25</td>
			<td>25.5</td>
			<td>26</td>
			<td>26.5</td>
			<td>27.5</td>
			<td>28.5</td>
			<td>29.5</td>
			<td>30</td>
			<td>30.5</td>
			<td>31.5</td>
			<td>32</td>
			<td>33</td>
		</tr>
	</table>
	
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">WOMEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">EURO</td>
			<td>36</td>
			<td>37</td>
			<td>38</td>
			<td>39</td>
			<td>40</td>
			<td>41</td>
			<td>42</td>
			<td>43</td>
			<td>44</td>
		</tr>
		<tr>
			<td class="title3">US</td>					
			<td>5</td>
			<td>6</td>
			<td>7</td>
			<td>8</td>
			<td>8.5</td>
			<td>9</td>
			<td>10</td>
			<td>11</td>
			<td>11.5</td>
		</tr>
		<tr>
			<td class="title3">JPN</td>
			<td>22.5</td>
			<td>23</td>
			<td>24</td>
			<td>25</td>
			<td>25.5</td>
			<td>26</td>
			<td>26.5</td>
			<td>27.5</td>
			<td>28</td>
		</tr>
	</table>

</div>