<?php

$brand = $this->getBrand();
$partNumber = $this->getPartNumber();
$partInfo = $this->getPartInfo();
$imageSrc = Mage::helper('arioem')->getBarcodeImageFile($this->getPartNumber());
$models = $this->getModels();

?>

<div class="oempart-container product-view">
	<div class="oempart-barcode-container">
		<div class="oempart-barcode-title"><?php echo htmlspecialchars($partInfo['assembly']) ?></div>
		<div class="oempart-barcode-content">
			<span class="oempart-barcode-content-label"><?php echo $this->__('SKU:') ?></span>
			<img src="<?php echo $imageSrc ?>" alt="<?php echo htmlspecialchars($this->getPartNumber()) ?>" title="<?php echo htmlspecialchars($this->getPartNumber()) ?>" />
		</div>
	</div>

	<div class="oempart-cinfo product-shop">
		<div class="oempart-cinfo-title"></div>
		<div class="oempart-cinfo-sku">
			<span class="oempart-cinfo-sku-label"><?php echo $this->__('SKU #') ?></span>
			<span class="oempart-cinfo-sku-value"><?php echo htmlspecialchars($partInfo['partnum']) ?></span>
		</div>
		<div class="oempart-cinfo-prices">
			<div class="oempart-cinfo-price-msrp">
				<span class="oempart-cinfo-price-msrp-label"><?php echo $this->__('MSRP') ?></span>
				<span class="oempart-cinfo-price-msrp-value"><?php echo $partInfo['msrp'] ?></span>
			</div>
			<div class="oempart-cinfo-price-regular">
				<span class="oempart-cinfo-price-regular-label"><?php echo $this->__('Regular price') ?></span>
				<span class="oempart-cinfo-price-regular-value"><?php echo $partInfo['price'] ?></span>
			</div>
		</div>
		<div class="oempart-cinfo-info">
			<span class="oempart-cinfo-info-tip"><?php echo $this->__('Qualifies for free shipping') ?></span>
			<span class="oempart-cinfo-info-tip"><?php echo $this->__('Lowest price guarantee') ?></span>
		</div>
		<?php if($partInfo['price'] > 89): ?>
			<div class="oempart-cinfo-promo oempart-cinfo-wideborder promo-wrapper">
				<span class="promo-free-shipping">Free Shipping</span>&nbsp;
				<span class="promo-rule-text">on orders over</span>&nbsp;
				<span class="promo-rule-price">$89!</span>
				<span class="promo-icon"></span>
			</div>
		<?php endif ?>
		<div class="oempart-cinfo-buttons">
			<div class="add-to-box">
				<div class="add-to-cart">
					<label for="qty"><?php echo $this->__('QUANTITY:') ?></label>
					<input type="text" class="input-text qty" title="Qty" value="1" maxlength="12" id="qty" name="qty">
					<p class="availability in-stock"><span><?php echo $this->__('In stock') ?></span></p>

					<div class="crystal"></div>

					<div class="buttons-prod">
						<a class="button link-wishlist" onclick="productAddToCartForm.submitLight(this, this.href); return false;" href="https://www.tmsparts.com/wishlist/index/add/product/341824/form_key/&lt;esi:include src='http://www.tmsparts.com/varnishcache/getformkey/' /&gt;/"><span><?php echo $this->__('Add to Wishlist') ?></span></a>
						<button onclick="popupcart.addToCart('http://www.tmsparts.com/ajaxcheckout/cart/add/pid/341824/catid/9242/', 'product');" class="button btn-cart" id="product-btn-cart" title="<?php echo $this->__('Add to Cart') ?>" type="button"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
					</div>
				</div>
				<p class="share"><img alt="" src="<?php echo $this->getSkinUrl('images/buttons/share.gif') ?>"></p>
			</div>
		</div>
	</div>

	<div class="oempart-tabs tabstabs">
		<ul class="product-tabs">
			<li class="first active" id="oempart_tabs_description"><a href="javascript:void(0)"><?php echo $this->__('Description') ?></a></li>
			<li class="last" id="oempart_tabs_product_models"><a href="javascript:void(0)"><?php echo $this->__('Models and Schematics') ?></a></li>
		</ul>

		<div class="crystal"></div>

		<div id="oempart_tabs_description_contents" class="oempart-tabs-content product-tabs-content">
<?php
vd($brand);
vd($partNumber);
?>
Part:
<?php vd($partInfo); ?>
		</div>

		<div id="oempart_tabs_product_models_contents" class="oempart-tabs-content product-tabs-content" style="display:none">
Models:
<?php vd($models); ?>
		</div>
	</div>

</div>

<script type="text/javascript">
	//<![CDATA[
	Varien.Tabs = Class.create();
	Varien.Tabs.prototype = {
		initialize: function (selector) {
			$$(selector + ' a').each(this.initTab.bind(this));
		},
		initTab: function (el) {
			el.href = 'javascript:void(0)';
			if ($(el.parentNode).hasClassName('active')) {
				this.showContent(el);
			}
			el.observe('click', this.showContent.bind(this, el));
		},
		showContent: function (a) {
			var li = $(a.parentNode), ul = $(li.parentNode);
			ul.select('li', 'ol').each(function (el) {
				var contents = $(el.id + '_contents');
				if (el == li) {
					el.addClassName('active');
					contents.show();
				} else {
					el.removeClassName('active');
					contents.hide();
				}
			});
		}
	}
	new Varien.Tabs('.product-tabs');
	//]]>
</script>