<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>Thor Offroad Glove Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'thor/brand_logo.jpg' ?>" alt="Thor" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'thor/glove_size.jpg' ?>" alt="Glove Sizes" /> </div>
  <h1>Size Measurement</h1>
  <p>Measure from the bottom of your palm (where it meets your wrist) to the top of your middle finger</p>
  <div class='fox-gloves-table-header'>Offroad Glove Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens</td>
      <td>XS</td>
      <td>S</td>
      <td>M</td>
      <td>L</td>
      <td>XL</td>
      <td>2XL</td>
    </tr>

    <tr>
      <td class="title3">HAND SIZE</td>
      <td>6 7/8-7 1/8</td>
      <td>7 1/8-7 3/8</td>
      <td>7 3/8-7 5/8</td>
      <td>7 5/8-7 3/8</td>
      <td>7 7/8-8 1/8</td>
      <td>8 1/8-8 3/8</td>
    </tr>    
  </table>
  
  
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Womens</td>
      <td>S</td>
      <td>M</td>
      <td>L</td>
      <td>XL</td>
    </tr>

    <tr>
      <td class="title3">HAND SIZE</td>
      <td>6 5/8-6 7/8</td>
      <td>6 7/8-7 1/8</td>
      <td>7 1/8-7 3/8</td>
      <td>7 3/8-7 5/8</td>
    </tr>
  </table>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Youth</td>
      <td>Y2XS</td>
      <td>YXS</td>
      <td>YS</td>
      <td>YM</td>
      <td>YL</td>
    </tr>
    <tr>
      <td class="title3">HAND SIZE</td>
      <td>5-5 1/8</td>
      <td>5 1/8-5 1/4</td>
      <td>5 1/4-5 1/2</td>
      <td>5 1/2-6</td>
      <td>6 1/8-6 1/2</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
