<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'yamaha'; // folder name
$default = false;
?>
<div class="fox-gloves">
	<h1>Yamaha Life Jacket Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="Yamaha" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/life-jacket.png' ?>" alt="Life Jacket Sizes" />
	</div>
	
	<h1>Chest</h1>

	<p>Measure around the broadest part of the chest, 1-2  inches below the arm pits.</p>

	<div class='fox-gloves-table-header'>Jacket Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">SIZE</td>
			<td>XS</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
			<td>3XL</td>
			<td>4XL</td>
		</tr>
		<tr>
			<td class="title3">CHEST SIZE</td>
			<td>30-33</td>
			<td>33-37</td>
			<td>37-41</td>
			<td>41-45</td>
			<td>45-49</td>
			<td>59-53</td>
			<td>53-57</td>
			<td>57-61</td>
		</tr>
	</table>
	
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">Womens</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">SIZE</td>
			<td>XS</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
		</tr>
		<tr>
			<td class="title3">CHEST SIZE</td>
			<td>30-33</td>
			<td>33-37</td>
			<td>37-41</td>
			<td>41-45</td>
			<td>45-49</td>
			<td>49-53</td>
		</tr>
	</table>
	
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">Youth</td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">SIZE</td>
			<td>teen</td>
		</tr>
		<tr>
			<td class="title3">CHEST SIZE</td>
			<td>28-30</td>
		</tr>
	</table>
	
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">Kids</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">SIZE</td>
			<td>youth</td>
			<td>child</td>
			<td>infant</td>
		</tr>
		<tr>
			<td class="title3">weight</td>
			<td>50-90</td>
			<td>30-50</td>
			<td>0-30</td>
		</tr>
	</table>
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit.</p>

</div>