<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'answer';
$default = true;
?>
<div class="fox-gloves">
	<h1>Answer Offroad Men and Youth's Boot Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="Answer" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/boots.jpg' ?>" alt="Glove Sizes" />
	</div>

	<h1>Boot Size</h1>

	<p>Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

	<div class='fox-gloves-table-header'>Boot Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">US</td>
			<td>7</td>
			<td>8</td>
			<td>9</td>
			<td>10</td>
			<td>11</td>
			<td>12</td>
			<td>13</td>
			<td>14</td>
		</tr>
		<tr>
			<td class="title3">EURO</td>					
			<td>40.5</td>
			<td>42</td>
			<td>43.5</td>
			<td>44.5</td>
			<td>46</td>
			<td>47</td>
			<td>48.5</td>
			<td>49.5</td>
		</tr>
		<tr>
			<td class="title3">JPN</td>
			<td>26</td>
			<td>26.5</td>
			<td>27</td>
			<td>28</td>
			<td>28.5</td>
			<td>29</td>
			<td>29.5</td>
			<td>30.5</td>
		</tr>
	</table>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">YOUTH'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">US</td>
			<td>11</td>
			<td>12</td>
			<td>13</td>
			<td>1</td>
			<td>2</td>
			<td>3</td>
			<td>4</td>
			<td>5</td>
			<td>6</td>
		</tr>
		<tr>
			<td class="title3">EURO</td>					
			<td>28.5</td>
			<td>30</td>
			<td>31</td>
			<td>32.5</td>
			<td>34</td>
			<td>35</td>
			<td>36</td>
			<td>37.5</td>
			<td>39</td>
		</tr>
		<tr>
			<td class="title3">JPN</td>
			<td>20</td>
			<td>21</td>
			<td>21.5</td>
			<td>22</td>
			<td>22.5</td>
			<td>23.5</td>
			<td>24</td>
			<td>24.5</td>
			<td>25</td>
		</tr>
	</table>

</div>