<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'allsport_dynamics'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Allsport Dynamics Ankle Protection Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="Allsport Dynamics" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/boot.jpg' ?>" alt="Ankle Protection Sizes" />
	</div>

	<h1>Description</h1>

	<p>Ankle size is determined by shoe size.</p>
	
	<div class='fox-gloves-table-header'>Ankle Protection Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">ANKLE SIZE</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
		</tr>
		<tr>
			<td class="title3">SHOE SIZE</td>
			<td>6-8</td>
			<td>8-10</td>
			<td>10-12</td>
			<td>12-12</td>
		</tr>
	</table>

	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>