<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'gears_canada'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Gears Canada Bike men's & Women's Gloves Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.png' ?>" alt="Gears Canada" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/glove_size.jpg' ?>" alt="Glove Sizes" />
	</div>

	<h1>Hand Length</h1>

	<p>Measure from the bottom of your palm (where it meets your wrist) to the top of your middle finger.</p>

	<div class='fox-gloves-table-header'>Glove Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">GLOVE SIZE</td>
			<td>XS/S</td>
			<td>M/L</td>
			<td>XL/XXL</td>
		</tr>
		<tr>
			<td class="title3">INCHES</td>
			<td>7-73/8</td>
			<td>7 3/8-7 7/8</td>
			<td>7 7/8-8 3/8</td>
		</tr>
	</table>
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>