<?php
/*
 * @var $this Mage_Checkout_Block_Onepage_Success
 */

$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$order = Mage::getModel('sales/order')->loadByIncrementId($orderId);
$amount = number_format($order->getGrandTotal(), 2);

?>

<!-- START Bing Tracking Code -->
<script>(function(w,d,t,r,u){var f,n,i;w[u]=w[u]||[],f=function(){var o={ti:"4048318"};o.q=w[u],w[u]=new UET(o),w[u].push("pageLoad")},n=d.createElement(t),n.src=r,n.async=1,n.onload=n.onreadystatechange=function(){var s=this.readyState;s&&s!=="loaded"&&s!=="complete"||(f(),n.onload=n.onreadystatechange=null)},i=d.getElementsByTagName(t)[0],i.parentNode.insertBefore(n,i)})(window,document,"script","//bat.bing.com/bat.js","uetq");</script>

<script>
var uetq = uetq || [];
uetq.push({'gv':<?php echo $amount; ?>}); // Pass the computed goal value
</script>
<!-- END Bing Tracking Code -->

<img src="https://www.pricegrabber.com/conversion.php?retid=29486&item1=||<?php echo $amount; ?>|||1">

<!-- START Nextag ROI Tracker Code -->
<script type="text/javascript">
<!--
  /* NexTag ROI Optimizer Data */
    var id = 5418896;
    var rev = <?php echo $amount; ?>;
    var order = <?php echo $this->getOrderId(); ?>;
    var units = '1';
//-->
</script>
<script type="text/javascript" src="https://imgsrv.nextag.com/imagefiles/includes/roitrack.js"></script>
<!-- END Nextag ROI Tracker Code -->
<div class="succeed">
<div class="page-title">
    <h1><?php echo $this->__('Your order has been received.') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<h2 class="sub-title"><?php echo $this->__('Thank you for your purchase!') ?></h2>

<?php if ($this->getOrderId()):?>
<?php if ($this->getCanViewOrder()) :?>
    <p><?php echo $this->__('Your order # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?></p>
<?php  else :?>
    <p><?php echo $this->__('Your order # is: %s.', $this->escapeHtml($this->getOrderId())) ?></p>
<?php endif;?>
    <p><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
<?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
    <p class="printtnx">
        <?php echo $this->__('Click <a href="%s" onclick="this.target=\'_blank\'">here to print</a> a copy of your order confirmation.', $this->getPrintUrl()) ?>
        <?php echo $this->getChildHtml() ?>
    </p>
<?php endif;?>
<?php endif;?>

<?php if ($this->getAgreementRefId()): ?>
    <p><?php echo $this->__('Your billing agreement # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId())))?></p>
<?php endif;?>

<?php if ($profiles = $this->getRecurringProfiles()):?>
<p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
<ul class="disc">
<?php foreach($profiles as $profile):?>
<?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id')));?>
    <li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($this->getObjectData($profile, 'schedule_description')))?></li>
<?php endforeach;?>
</ul>
<?php endif;?>
</div>
<div class="buttons-set">
    <button type="button" class="button" title="<?php echo $this->__('Continue Shopping') ?>" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
</div>

<!-- Google Code for Purchase Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 959963017;
var google_conversion_language = "en";
var google_conversion_format = "2";
var google_conversion_color = "ffffff";
var google_conversion_label = "EbJhCKDTr1kQib_fyQM";
var google_conversion_value = <?php echo $amount ?>;
var google_conversion_currency = "USD";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js"></script>
<noscript><div style="display:inline;"><img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/959963017/?value=<?php echo $amount ?>&amp;currency_code=USD&amp;label=EbJhCKDTr1kQib_fyQM&amp;guid=ON&amp;script=0"/></div></noscript>

<?php
/*
// Google Trusted Stores Badge Code

$customer = Mage::getModel('customer/customer')->load($order->getCustomerId());
$shippingAddress = $order->getShippingAddress();
$backorder = false; // not now
$download = false; // are motorcycles downloadable? hmm...
$shipDate = new Zend_Date(); // this is very hard to define...

?>
<div id="gts-order" style="display:none;">
	<span id="gts-o-id"><?php echo $orderId ?></span>
	<span id="gts-o-domain"><?php echo $this->getUrl('') ?></span>
	<span id="gts-o-email"><?php echo htmlentities($customer->getEmail()) ?></span>
	<span id="gts-o-country"><?php echo htmlentities($shippingAddress->getCountryId()) ?></span>
	<span id="gts-o-currency">USD</span>
	<span id="gts-o-total"><?php echo $order->getGrandTotal() ?></span>
	<span id="gts-o-discounts">-<?php echo $order->getDiscountAmount() ?></span>
	<span id="gts-o-shipping-total"><?php echo $order->getShippingAmount() ?></span>
	<span id="gts-o-tax-total"><?php echo $order->getTaxAmount() ?></span>
	<span id="gts-o-est-ship-date"><?php echo $shipDate->toString('yyyy-MM-dd') ?></span>
	<span id="gts-o-has-preorder"><?php echo $backorder ? 'Y' : 'N' ?></span>
	<span id="gts-o-has-digital"><?php echo $download ? 'Y' : 'N' ?></span>
	<?php foreach ($order->getAllItems() as $item): ?>
		<span class="gts-item">
			<span class="gts-i-name"><?php echo htmlentities($item->getName()) ?></span>
			<span class="gts-i-price"><?php echo $item->getBasePrice() ?></span>
			<span class="gts-i-quantity"><?php echo (int)$item->getQtyOrdered() ?></span>
			<span class="gts-i-prodsearch-country">US</span>
			<span class="gts-i-prodsearch-language">en</span>
		</span>
	<?php endforeach; ?>
</div>
<?php /**/ ?>