<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>Arctiva Adventure Boot Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'arctiva/brand_logo.jpg' ?>" alt="Arctiva" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'arctiva/boots.jpg' ?>" alt="Adventure Boot Sizes" /> </div>
  <h1>Size Measurement</h1>
  <p>Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
  <div class='fox-gloves-table-header'>Adventure Boot Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td class="title3">BOOT SIZE</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td class="title3">US</td>
      <td>5.5</td>
      <td>6</td>
      <td>7</td>
      <td>7.5</td>
      <td>8.5</td>
      <td>9.5</td>
      <td>10</td>
      <td>10.5</td>
      <td>11.5</td>
      <td>12</td>
      <td>13</td>
    </tr>
    <tr>
      <td class="title3">EURO</td>
      <td>38</td>
      <td>39</td>
      <td>40</td>
      <td>41</td>
      <td>42</td>
      <td>43</td>
      <td>44</td>
      <td>45</td>
      <td>46</td>
      <td>47</td>
      <td>48</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
