<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>Arctiva Dirt Pant Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'arctiva/brand_logo.jpg' ?>" alt="Arctiva" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'arctiva/pants.jpg' ?>" alt="Dirt Pant Sizes" /> </div>
  <h1>Size Measurement</h1>
  <p>Inseam : While standing without shoes and with feet slightly apart, measure from the crotch along the leg to the floor.</p>
  <p>Waist: With a tape measure about 1 inch below the pelvis bone and holding it level, measure the circumference at the waist while standing with natural bend.</p>
  <div class='fox-gloves-table-header'>Dirt Pant Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td class="title3">WAIST</td>
      <td>28</td>
      <td>30</td>
      <td>32</td>
      <td>34</td>
      <td>36</td>
      <td>38</td>
      <td>40</td>
      <td>42</td>
      <td>44</td>
    </tr>
    <tr>
      <td class="title3">INSEAM</td>
      <td>32</td>
      <td>32</td>
      <td>33</td>
      <td>33</td>
      <td>33</td>
      <td>34</td>
      <td>34</td>
      <td>34</td>
      <td>34</td>
    </tr>
  </table>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Womens</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td class="title3">PANT SIZE</td>
      <td>1</td>
      <td>3</td>
      <td>5</td>
      <td>7</td>
      <td>9</td>
      <td>11</td>
      <td>13</td>
    </tr>
    <tr>
      <td class="title3">WAIST</td>
      <td>24</td>
      <td>26</td>
      <td>28</td>
      <td>30</td>
      <td>32</td>
      <td>34</td>
      <td>36</td>
    </tr>
    <tr>
      <td class="title3">INSEAM</td>
      <td>29-31</td>
      <td>30-32</td>
      <td>30-32</td>
      <td>31-33</td>
      <td>31-33</td>
      <td>31-33</td>
      <td>31-33</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
