<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'hmk'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>HMK Boot Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.png' ?>" alt="HMK" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/boots.jpg' ?>" alt="Glove Sizes" />
	</div>

	<h1>Boot Size</h1>

	<p>Use your street shoe size to find the corresponding models boot size.</p>

	<div class='fox-gloves-table-header'>Boot Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">STREET SHOE SIZE</td>
			<td>5</td>
			<td>5.5</td>
			<td>6</td>
			<td>6.5</td>
			<td>7</td>
			<td>7.5</td>
			<td>8</td>
			<td>8.5</td>
			<td>9</td>
			<td>9.5</td>
			<td>10</td>
		</tr>
		<tr>
			<td class="title3">PRO &amp; PRO BOA BOOT SIZE</td>					
			<td>n/a</td>
			<td>n/a</td>
			<td>7</td>
			<td>8</td>
			<td>8</td>
			<td>9</td>
			<td>9</td>
			<td>10</td>
			<td>10</td>
			<td>11</td>
			<td>11</td>
		</tr>
		<tr>
			<td class="title3">HIGHMARK 3 &AMP; 4 BOOT SIZE</td>
			<td>6</td>
			<td>6</td>
			<td>7</td>
			<td>7</td>
			<td>8</td>
			<td>8</td>
			<td>9</td>
			<td>9</td>
			<td>10</td>
			<td>10</td>
			<td>11</td>
		</tr>
		<tr>
			<td class="title3">CRUISER BOOT SIZE</td>
			<td>5</td>
			<td>6</td>
			<td>6</td>
			<td>7</td>
			<td>7</td>
			<td>8</td>
			<td>8</td>
			<td>9</td>
			<td>9</td>
			<td>10</td>
			<td>10</td>
		</tr>
	</table>
	
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">STREET SHOE SIZE</td>
			<td>10.5</td>
			<td>11</td>
			<td>11.5</td>
			<td>12</td>
			<td>12.5</td>
			<td>13</td>
			<td>13.5</td>
			<td>14</td>
			<td>14.5</td>
			<td>15</td>
		</tr>
		<tr>
			<td class="title3">PRO &amp; PRO BOA BOOT SIZE</td>					
			<td>12</td>
			<td>12</td>
			<td>13</td>
			<td>13</td>
			<td>14</td>
			<td>14</td>
			<td>14</td>
			<td>15</td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">HIGHMARK 3 &AMP; 4 BOOT SIZE</td>
			<td>11</td>
			<td>12</td>
			<td>12</td>
			<td>13</td>
			<td>13</td>
			<td>14</td>
			<td>14</td>
			<td>15</td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">CRUISER BOOT SIZE</td>
			<td>11</td>
			<td>11</td>
			<td>12</td>
			<td>12</td>
			<td>13</td>
			<td>13</td>
			<td>14</td>
			<td>14</td>
			<td>15</td>
			<td>15</td>
		</tr>
	</table>
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>