<?php

?>

<div class="fitment-selector block">
	<div class="block-title">
		<strong><span><?php echo $this->__('Shop By') ?></span></strong>
	</div>

	<div class="block-content">
		<dt class=""><?php echo $this->__('Select your ride') ?></dt>
		<dd class="">
			<select class="fitment-year-select">
				<option><?php echo $this->__('Choose Year') ?></option>
			</select>
			<select class="fitment-make-select">
				<option><?php echo $this->__('Choose Make') ?></option>
			</select>
			<select class="fitment-model-select">
				<option><?php echo $this->__('Choose Model') ?></option>
			</select>
		</dd>
	</div>
</div>