<div class="wholesale-left">

	<div class="wholesale-left-group-header"><?php echo $this->__('Catalog') ?></div>
	<ul class="wholesale-left-group-list">
		<li class="wholesale-left-group-list-item"><a href="<?php echo $this->getUrl('', array('_direct' => 'oem-parts.html')) ?>"><?php echo $this->__('OEM Diagrams') ?></a></li>
		<li class="wholesale-left-group-list-item"><a href="<?php echo $this->getUrl('') ?>"><?php echo $this->__('Parts & Accessories') ?></a></li>
		<li class="wholesale-left-group-list-item"><a href="<?php echo $this->getUrl('', array('_direct' => 'dealer-corner-service-manuals.html')) ?>"><?php echo $this->__('Service Manuals') ?></a></li>
		<li class="wholesale-left-group-list-item"><a href="<?php echo $this->getUrl('', array('_direct' => 'dealer-corner-oem-oils-chemicals.html')) ?>"><?php echo $this->__('OEM Oils & Chemicals') ?></a></li>
	</ul>

	<div class="wholesale-left-group-header"><?php echo $this->__('Order Info') ?></div>
	<ul class="wholesale-left-group-list">
		<li class="wholesale-left-group-list-item"><a href="<?php echo $this->getUrl('sales/order/history') ?>"><?php echo $this->__('New Orders') ?></a></li>
<?php /** ?>
		<li class="wholesale-left-group-list-item"><a href="<?php echo $this->getUrl('customer/account/invoice') ?>"><?php echo $this->__('Order Status') ?></a></li>
		<li class="wholesale-left-group-list-item"><a href="<?php echo $this->getUrl('sales/order/history') ?>"><?php echo $this->__('Parts History') ?></a></li>
<?php /**/ ?>
		<li class="wholesale-left-group-list-item"><a href="<?php echo $this->getUrl('wholesale/quickorder') ?>"><?php echo $this->__('Price Check') ?></a></li>
	</ul>


	<div class="wholesale-left-group-header"><?php echo $this->__('Account Info') ?></div>
	<ul class="wholesale-left-group-list">
		<li class="wholesale-left-group-list-item"><a href="<?php echo $this->getUrl('', array('_direct' => 'dealer-terms.html')) ?>"><?php echo $this->__('Dealer Terms') ?></a></li>
		<li class="wholesale-left-group-list-item"><a href="<?php echo $this->getUrl('', array('_direct' => 'dealer-corner-policies-procedures.html')) ?>"><?php echo $this->__('Policies & Procedures') ?></a></li>
		<li class="wholesale-left-group-list-item"><a href="<?php echo $this->getUrl('', array('_direct' => 'dealer-corner-faq.html')) ?>"><?php echo $this->__('FAQ\'s') ?></a></li>
		<li class="wholesale-left-group-list-item"><a href="<?php echo $this->getUrl('customer/address') ?>"><?php echo $this->__('Update address info') ?></a></li>
		<li class="wholesale-left-group-list-item"><a href="http://www.boe.ca.gov/pdf/boe230.pdf"><?php echo $this->__('CA Resale Certificate') ?></a></li>
	</ul>

</div>
