<?php

$dealerStatus = $this->getDealerStatus();

$appBlockHtml = $this->hasApplication()
	?	$this->getLayout()->createBlock('core/template')
			->setTemplate('vk_wholesale/dealer/application.phtml')
			->setApplicationData($this->getApplicationData())
			->setAddress($this->getAddress())
			->toHtml()
	:	'';

?>
<div class="wsdc wholesale">

	<div class="page-title">
		<h1><?php echo $this->__('Dealer Corner') ?></h1>
	</div>

	<?php if(Vikont_Wholesale_Helper_Data::isApplicationSent()): ?>

		<div class="wsdc-dealer">
			<h3><?php echo $this->__('Dealer Information') ?></h3>
			<div class="wsdc-tablecontainer">
				<table class="wsdc-fields">
					<tr>
						<th><?php echo $this->__('Dealer status') ?></th>
						<td><?php echo htmlspecialchars(Mage::getModel('wholesale/source_dealer_status')->getOptionText($dealerStatus)) ?></td>
					</tr>
				</table>
			</div>
		</div>

		<?php echo $appBlockHtml ?>

	<?php else: ?>

		<p><?php echo $this->__('In order to become a dealer, you need to send a Dealer Application.') ?></p>
		<div class="wsap-button-container">
			<a class="wsap-button" href="<?php echo $this->getUrl('wholesale/application') ?>"><?php echo $this->__('Apply for dealership') ?></a>
		</div>

	<?php endif ?>

	<div class="buttons-set">
		<p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
	</div>

</div>