<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'spidi'; // folder name
$default = false;
?>
<div class="fox-gloves">
	<h1>Spidi Sport Gloves Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.png' ?>" alt="Spidi Sport" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/glove_size.png' ?>" alt="Glove Sizes" />
	</div>

	<h1>Glove Size</h1>

	<p>Measurement should be at the widest point of your palm.</p>

	<div class='fox-gloves-table-header'>Glove Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">GLOVE SIZE</td>
			<td>XS</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
			<td>3XL</td>
		</tr>
		<tr>
			<td class="title3">EURO SIZE</td>
			<td>6.5</td>
			<td>7</td>
			<td>8</td>
			<td>9</td>
			<td>9.5</td>
			<td>10</td>
			<td>11</td>
		</tr>
		<tr>
			<td class="title3">INCHES A</td>
			<td>19.8-20.6</td>
			<td>20.6-21.4</td>
			<td>21.4-22.2</td>
			<td>22.2-23.0</td>
			<td>23.0-23.8</td>
			<td>23.8-24.6</td>
			<td>24.6-25.4</td>
		</tr>
	</table>
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>