<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'troylee'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Troy Lee Casual Pants Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="Troy Lee" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/pants.jpg' ?>" alt="Pants Sizes" />
	</div>

	<h1>INSEAM</h1>

	<p>Measure down from the crotch to the top of the ankle bone.</p>
	
	<h1>WAIST</h1>

	<p>Waist-Measure about 1 inch below top of pelvic bone.</p>

	<div class='fox-gloves-table-header'>Pants Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	
		<tr>
			<td class="title3">PANT SIZE</td>
			<td>28</td>
			<td>30</td>
			<td>32</td>
			<td>34</td>
			<td>36</td>
			<td>38</td>
			<td>40</td>
			<td>42</td>
			<td>44</td>
		</tr>
		
		<tr>
			<td class="title3">WAIST SIZE</td>
			<td>29-33</td>
			<td>31-34</td>
			<td>33-36</td>
			<td>35-38</td>
			<td>37-40</td>
			<td>39-42</td>
			<td>41-44</td>
			<td>43-46</td>
			<td>45-48</td>
		</tr>
		
		<tr>
			<td class="title3">INSEAM</td>
			<td>30.5</td>
			<td>31</td>
			<td>32</td>
			<td>32.5</td>
			<td>33.5</td>
			<td>34</td>
			<td>35</td>
			<td>36</td>
			<td>36</td>
		</tr>
	</table>
	
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>