<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'can-am'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Can-am Jersey Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="Can-am" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/jersey.jpg' ?>" alt="Jersey Sizes" />
	</div>

	<h1>Description</h1>

	<p>Jerseys will run slightly bigger for a good comfortable and unrestricted fit.</p>
	
	<h1>Sleeve</h1>

	<p>Measure from center of the spine at the base of the neck, around the shoulder, over the elbow and down to the wrist.</p>
	
	<h1>Chest</h1>

	<p>Measure around the broadest part of the chest 1-2 below the arm pits.</p>

	<div class='fox-gloves-table-header'>Jersey Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">JERSEY SIZE</td>
			<td>XS</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
			<td>3XL</td>
			<td>4XL</td>
		</tr>
		<tr>
			<td class="title3">T SHIRT SIZE</td>
			<td>XS</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
			<td>3XL</td>
			<td>4XL</td>
		</tr>
	</table>
	
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">WOMENS</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">JERSEY SIZE</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
		</tr>
		<tr>
			<td class="title3">T SHIRT SIZE</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
		</tr>
	</table>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">YOUTH</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">JERSEY SIZE</td>
			<td>YS</td>
			<td>YM</td>
			<td>YL</td>
			<td>YXL</td>
			<td>Y2XL</td>
		</tr>
		<tr>
			<td class="title3">T SHIRT SIZE</td>
			<td>XS</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
		</tr>
	</table>
	
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit.</p>

</div>