<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'fox'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Fox Offroad Men's, Women's, and Youth's Jersey Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="Fox" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/jersey.jpg' ?>" alt="Glove Sizes" />
	</div>
	
	<h1>Sleeve</h1>

	<p>Measure from center of the spine at the base of the neck, around the shoulder, over the elbow and down to the wrist.</p>
	
	<h1>Chest</h1>

	<p>Measure around the broadest part of the chest 1-2 below the arm pits.</p>

	<div class='fox-gloves-table-header'>Jersey Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">SIZE</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
		</tr>
		<tr>
			<td class="title3">CHEST</td>
			<td>33-35</td>
			<td>36-39</td>
			<td>40-42</td>
			<td>43-46</td>
			<td>47-50</td>
		</tr>
		<tr>
			<td class="title3">SLEEVE</td>
			<td>32-33</td>
			<td>33-34</td>
			<td>34-35</td>
			<td>35-36</td>
			<td>36-37</td>
		 </tr>
		 <tr>
			<td class="title3">HEIGHT</td>
			<td>5'6-5'10</td>
			<td>5'10-6'</td>
			<td>6'-6'2</td>
			<td>6'1-6'3</td>
			<td>6'1-6'3</td>
		 </tr>
	</table>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">WOMEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">SIZE</td>
			<td>XS</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
		</tr>
		<tr>
			<td class="title3">BUST</td>
			<td>31-33</td>
			<td>34-36</td>
			<td>36-37</td>
			<td>38-39</td>
			<td>39-40</td>
		</tr>
		<tr>
			<td class="title3">SLEEVE</td>
			<td>28-29</td>
			<td>29-30</td>
			<td>30-31</td>
			<td>31-31 1/2</td>
			<td>31-31 1/2</td>
		</tr>
	</table>
	
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">YOUTH</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">SIZE</td>
			<td>KS</td>
			<td>KM</td>
			<td>YS</td>
			<td>YM</td>
			<td>YL</td>
			<td>YXL</td>
		</tr>
		<tr>
			<td class="title3">CHEST</td>
			<td>22</td>
			<td>23</td>
			<td>25</td>
			<td>27</td>
			<td>28</td>
			<td>29 1/2</td>
		</tr>
		<tr>
			<td class="title3">SLEEVE</td>
			<td>18 3/4</td>
			<td>20</td>
			<td>22</td>
			<td>23</td>
			<td>25</td>
			<td>27</td>
		</tr>
	</table>
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit.</p>

</div>