<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'fox'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Fox Boot Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="Fox" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/boots.jpg' ?>" alt="Glove Sizes" />
	</div>

	<h1>Boot Size</h1>

	<p>Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

	<div class='fox-gloves-table-header'>Boot Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">USA</td>
			<td>8</td>
			<td>9</td>
			<td>10</td>
			<td>11</td>
			<td>12</td>
			<td>13</td>
			<td>14</td>
			<td>15</td>
		</tr>
		<tr>
			<td class="title3">INCHES</td>					
			<td>9.9375</td>
			<td>10.25</td>
			<td>10.5625</td>
			<td>10.9375</td>
			<td>11.25</td>
			<td>11.5625</td>
			<td>11.875</td>
			<td>12.1875</td>
		</tr>
	</table>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">WOMAN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">USA</td>
			<td>5</td>
			<td>6</td>
			<td>7</td>
			<td>8</td>
			<td>9</td>
			<td>10</td>
			<td>11</td>
		</tr>
		<tr>
			<td class="title3">INCHES</td>					
			<td>8.5</td>
			<td>8.875</td>
			<td>9.25</td>
			<td>9.5</td>
			<td>9.875</td>
			<td>10.1875</td>
			<td>10.5</td>
		</tr>
	</table>
	
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">YOUTH</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">USA</td>
			<td>Y1</td>
			<td>Y2</td>
			<td>Y3</td>
			<td>Y4</td>
			<td>Y5</td>
			<td>Y6</td>
			<td>Y7</td>
			<td>Y8</td>
		</tr>
		<tr>
			<td class="title3">INCHES</td>					
			<td>7.75</td>
			<td>8.125</td>
			<td>8.5</td>
			<td>8.75</td>
			<td>9.125</td>
			<td>9.5</td>
			<td>9.75</td>
			<td>9.9375</td>
		</tr>
	</table>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">KIDS</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">USA</td>
			<td>K10</td>
			<td>K11</td>
			<td>K12</td>
			<td>K13</td>
		</tr>
		<tr>
			<td class="title3">INCHES</td>					
			<td>6.5</td>
			<td>6.75</td>
			<td>7.125</td>
			<td>7.5</td>
		</tr>
	</table>
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>