<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'fox'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Fox Rain/Snow Jacket Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="Fox" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/jersey.jpg' ?>" alt="Jacket Sizes" />
	</div>
	
	<h1>Sleeve</h1>

	<p>Measure from center of the spine at the base of the neck, around the shoulder, over the elbow and down to the wrist.</p>
	
	<h1>Chest</h1>

	<p>Measure around the broadest part of the chest 1-2 below the arm pits.</p>

	<div class='fox-gloves-table-header'>Jacket Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
		<tr>
			<td class="title3">JACKET SIZE</td>
			<td>XS</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
			<td>3XL</td>
		</tr>
		<tr>
			<td class="title3">CHEST</td>
			<td>38</td>
			<td>39</td>
			<td>40</td>
			<td>41</td>
			<td>43</td>
			<td>45</td>
			<td>47</td>
		</tr>
		<tr>
		<td class="title3">WAIST</td>
			<td>37</td>
			<td>38</td>
			<td>39</td>
			<td>40</td>
			<td>42</td>
			<td>44</td>
			<td>46</td>
		</tr>
	</table>
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit.</p>

</div>