<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'fly_snow'; // folder name
$default = false;
?>
<div class="fox-gloves">
	<h1>Fly Snow Pants Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="Fly Snow" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/pants.jpg' ?>" alt="Pants Sizes" />
	</div>

	<h1>WAIST</h1>

	<p>Measure about 1 inch below top of pelvic bone.</p>
	
	<h1>INSEAM</h1>

	<p>Measure down from the crotch to the top of the ankle bone.</p>

	<div class='fox-gloves-table-header'>Pants Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">SNOW  REGULAR</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">PANT SIZE</td>
			<td>XS</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
			<td>3XL</td>
		</tr>
		<tr>
			<td class="title3">WAIST</td>
			<td>28 1/2-30</td>
			<td>30 1/2-32</td>
			<td>32 1/2-34</td>
			<td>34 1/2-36</td>
			<td>36 1/2-38</td>
			<td>38 1/2-40</td>
			<td>40 1/2-42</td>
		</tr>
		<tr>
			<td class="title3">INSEAM</td>
			<td>29</td>
			<td>30</td>
			<td>31</td>
			<td>32</td>
			<td>32.5</td>
			<td>32.5</td>
			<td>32.5</td>
		</tr>
	</table>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">SNOW  SHORT</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">PANT SIZE</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
			<td>3XL</td>
		</tr>
		<tr>
			<td class="title3">WAIST</td>
			<td>34 1/2-36</td>
			<td>36 1/2-38</td>
			<td>38 1/2-40</td>
			<td>40 1/2-42</td>
		</tr>
		<tr>
			<td class="title3">INSEAM</td>
			<td>28</td>
			<td>28.5</td>
			<td>28.5</td>
			<td>28.5</td>
		</tr>
	</table>
	
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">SNOW  TALL</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">PANT SIZE</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
			<td>3XL</td>
		</tr>
		<tr>
			<td class="title3">WAIST</td>
			<td>34 1/2-36</td>
			<td>36 1/2-38</td>
			<td>38 1/2-40</td>
			<td>40 1/2-42</td>
		</tr>
		<tr>
			<td class="title3">INSEAM</td>
			<td>36</td>
			<td>36.5</td>
			<td>36.5</td>
			<td>36.5</td>
		</tr>
	</table>
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>