<?php
$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;
 
$brand = 'yamaha'; // folder name
$default = true;
?>

<div class="fox-gloves">
  <h1>Yamaha Footwear Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="Yamaha" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/boots.jpg' ?>" alt="Footwear Sizes" /> </div>
  <div class='fox-gloves-table-header'>Offroad Footwear Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
		<td class="title2">MENS</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
    </tr>
    <tr>
		<td class="title3">US</td>
		<td>7</td>
		<td>7.5</td>
		<td>8</td>
		<td>8.5</td>
		<td>9</td>
		<td>9.5</td>
		<td>10</td>
		<td>10.5</td>
		<td>11</td>
		<td>12</td>
		<td>13</td>
		<td>14</td>
    </tr>
    <tr>
		<td class="title3">UK</td>	
		<td>6</td>
		<td>6.5</td>
		<td>7</td>
		<td>7.5</td>
		<td>8</td>
		<td>8.5</td>
		<td>9</td>
		<td>9.5</td>
		<td>10</td>
		<td>11</td>
		<td>12</td>
		<td>13</td>
    </tr>
	<tr>
		<td class="title3">EU</td>
		<td>40</td>
		<td>40.5</td>
		<td>41</td>
		<td>42</td>
		<td>42.5</td>
		<td>43</td>
		<td>44</td>
		<td>44.5</td>
		<td>45</td>
		<td>46</td>
		<td>47.5</td>
		<td>48</td>
    </tr>
	<tr>
		<td class="title3">CM</td>
		<td>25</td>
		<td>25.5</td>
		<td>26</td>
		<td>26.5</td>
		<td>27</td>
		<td>27.5</td>
		<td>28</td>
		<td>28.5</td>
		<td>29</td>
		<td>30</td>
		<td>31</td>
		<td>31.5</td>
    </tr>    
  </table>
 
  <p>&nbsp;</p>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
