<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;
 
$brand = 'yamaha'; // folder name
$default = true;
?>

<div class="fox-gloves">
  <h1>Yamaha Offroad Jersey Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="Thor" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/jersey.jpg' ?>" alt="Yamaha Sizes" /> </div>
  <h1>Size Measurement</h1>
  <p>Jerseys will run slightly bigger for a good confortable and unrestricted fit.</p>
  <p>Sleeve: Measure from center of the spine at the base of the neck, around the shoulder,over the elbow and down to the wrist</p>
  <p>Chest: Measure around the broadest part of the chest 1-2 below the arm pits.</p>
  <div class='fox-gloves-table-header'>Offroad Jersey Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
    </tr>
    <tr>
      <td class="title3">Jersey size</td>
		<td>S</td>
		<td>M</td>
		<td>L</td>
		<td>XL</td>
		<td>2XL</td>
		<td>3XL</td>
		<td>4XL</td>
		<td>5XL</td>
    </tr>
    <tr>
		<td class="title3">chest</td>
		<td>41-43</td>
		<td>43-45</td>
		<td>45-47</td>
		<td>47-49</td>
		<td>49-51</td>
		<td>51-53</td>
		<td>53-55</td>
		<td>55-57</td>
    </tr>
	<tr>
		<td class="title3">sleeve</td>
		<td>33-34</td>
		<td>34-35</td>
		<td>35-36</td>
		<td>36-37</td>
		<td>37-38</td>
		<td>38-39</td>
		<td>39-40</td>
		<td>40-41</td>
    </tr>
  </table>
  
  <table class="sizing_chart">
    <tr class="title1">
		<td class="title2">Youth</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
    </tr>
    <tr>
		<td class="title3">Jersey size</td>
		<td>XS</td>
		<td>S</td>
		<td>M</td>
		<td>L</td>
		<td>XL</td>
    </tr>
    <tr>
	<tr>
      <td class="title3">CHEST</td>
		<td>27-29</td>
		<td>29-31</td>
		<td>31-33</td>
		<td>33-35</td>
		<td>35-37</td>
    </tr>
    <tr>
		<td class="title3">SLEEVE</td>
		<td>27-28</td>
		<td>28-29</td>
		<td>29-30</td>
		<td>30-31</td>
		<td>31-32</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
