<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'yamaha'; // folder name
$default = false;
?>
<div class="fox-gloves">
	<h1>Yamaha Wetsuites Wet Suit Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.png' ?>" alt="Yamaha Wetsuites" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/wet-suit.png' ?>" alt="Wet Suit Sizes" />
	</div>
	
	<h1>Chest</h1>

	<p>Measure around the broadest part of the chest, 1-2  inches below the arm pits.</p>

	<div class='fox-gloves-table-header'>Jacket Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">SIZE</td>
			<td>XS</td>
			<td>S</td>
			<td>M</td>
			<td>MT</td>
			<td>L</td>
			<td>LT</td>
			<td>XL</td>
			<td>2XL</td>
		</tr>
		<tr>
			<td class="title3">CHEST</td>
			<td>32-35</td>
			<td>34-37</td>
			<td>36-39</td>
			<td>36-39</td>
			<td>38-41</td>
			<td>38-41</td>
			<td>40-43</td>
			<td>42+</td>
		</tr>
		<tr>
			<td class="title3">WAIST</td>
			<td>24-27</td>
			<td>27-30</td>
			<td>27-30</td>
			<td>29-32</td>
			<td>31-34</td>
			<td>32-35</td>
			<td>33-36</td>
			<td>36+</td>
		</tr>
		<tr>
			<td class="title3">HEIGHT</td>
			<td>5'1-5'5</td>
			<td>5'4-5'7</td>
			<td>5'6-5'9</td>
			<td>5'10-6'0</td>
			<td>5'8-5'11</td>
			<td>6'0-6'3</td>
			<td>5'10-6'1</td>
			<td>6+</td>
		</tr>
		<tr>
			<td class="title3">WEIGHT</td>
			<td>120-140</td>
			<td>130-155</td>
			<td>145-170</td>
			<td>155-180</td>
			<td>165-190</td>
			<td>175-200</td>
			<td>185-205</td>
			<td>205+</td>
		</tr>
	</table>
	
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">WOMENS</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">SIZE</td>
			<td>XS</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
		</tr>
		<tr>
			<td class="title3">BUST</td>
			<td>32-34</td>
			<td>33.5-35.5</td>
			<td>35-37</td>
			<td>36.5-38.5</td>
			<td>38+</td>
		</tr>
		<tr>
			<td class="title3">WAIST</td>
			<td>23-25</td>
			<td>24.5-26.5</td>
			<td>26-28</td>
			<td>27.5-29.5</td>
			<td>29+</td>
		</tr>
		<tr>
			<td class="title3">HEIGHT</td>
			<td>5'4-5'6</td>
			<td>5'5-5'7</td>
			<td>5'6-5'8</td>
			<td>5'7-5'9</td>
			<td>5'9+</td>
		</tr>
		<tr>
			<td class="title3">WEIGHT</td>
			<td>100-115</td>
			<td>110-125</td>
			<td>120-125</td>
			<td>130-145</td>
			<td>150+</td>
		</tr>
	</table>
	
	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">YOUTH</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">SIZE</td>
			<td>6</td>
			<td>8</td>
			<td>10</td>
			<td>12</td>
			<td>14</td>
			<td>16</td>
		</tr>
		<tr>
			<td class="title3">CHEST</td>
			<td>25-26</td>
			<td>26-27</td>
			<td>27-28</td>
			<td>28-30</td>
			<td>29-31</td>
			<td>31-33</td>
		</tr>
		<tr>
			<td class="title3">WAIST</td>
			<td>21-22</td>
			<td>22-23</td>
			<td>23-24</td>
			<td>24-26</td>
			<td>25-27</td>
			<td>27-29</td>
		</tr>
		<tr>
			<td class="title3">HEIGHT</td>
			<td>4'6-4'8</td>
			<td>4'8-4'10</td>
			<td>4'10-5'1</td>
			<td>4'11-5'1</td>
			<td>5'-5'3</td>
			<td>5'1-5'4</td>
		</tr>
		<tr>
			<td class="title3">WEIGHT</td>
			<td>50-60</td>
			<td>60-70</td>
			<td>70-80</td>
			<td>80-90</td>
			<td>90-105</td>
			<td>105-120</td>
		</tr>
	</table>
	
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit.</p>

</div>