<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'river_road'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>River Road Pants Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.png' ?>" alt="River Road" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/pants.jpg' ?>" alt="Pants Sizes" />
	</div>

	<h1>PANTS SIZE</h1>

	<p>River road pants and over pants fit true to size. If you wear a size 34 waist jeans, purchase a size 34 pant.</p>
	
	<h1>WAIST</h1>

	<p>Measure about 1 inch below top of pelvic bone.</p>
	
	<h1>INSEAM</h1>

	<p>Measure down from the crotch to the top of the ankle bone.</p>

	<div class='fox-gloves-table-header'>Pants Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">PANT SIZE</td>
			<td>30</td>
			<td>32</td>
			<td>34</td>
			<td>36</td>
			<td>38</td>
			<td>40</td>
			<td>42</td>
			<td>44</td>
			<td>46</td>
			<td>48</td>
		</tr>
		<tr>
			<td class="title3">WAIST</td>
			<td>30</td>
			<td>32</td>
			<td>34</td>
			<td>36</td>
			<td>38</td>
			<td>40</td>
			<td>42</td>
			<td>44</td>
			<td>46</td>
			<td>48</td>
		</tr>
		<tr>
			<td class="title3">INSEAM</td>
			<td>31</td>
			<td>31</td>
			<td>31 1/2</td>
			<td>32</td>
			<td>32 1/2</td>
			<td>33</td>
			<td>33 1/2</td>
			<td>33 1/2</td>
			<td>33 1/2</td>
			<td>34</td>
		</tr>
	</table>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">WOMEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">PANT SIZE</td>
			<td>4</td>
			<td>6</td>
			<td>8</td>
			<td>10</td>
			<td>12</td>
			<td>14</td>
		</tr>
		<tr>
			<td class="title3">WAIST</td>
			<td>28</td>
			<td>29.5</td>
			<td>31</td>
			<td>33</td>
			<td>35</td>
			<td>38</td>
		</tr>
		<tr>
			<td class="title3">INSEAM</td>
			<td>29</td>
			<td>30</td>
			<td>31</td>
			<td>32.5</td>
			<td>33</td>
			<td>33</td>
		</tr>
	</table>
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>