<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>O'Neal Offroad Glove Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'fox/brand_logo.jpg' ?>" alt="Fox" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'fox/glove_size.jpg' ?>" alt="Glove Sizes" /> </div>
  <h1>Hand Length</h1>
  <p>Measure from the bottom of your palm (where it meets your wrist) to the top of your middle finger</p>
  <div class='fox-gloves-table-header'>Offroad Glove Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">MEN'S</td>
      <td>S8</td>
      <td>M9</td>
      <td>L10</td>
      <td>XL 11</td>
      <td>2XL 12</td>
    </tr>
    <tr>
      <td class="title3">HAND SIZE</td>
      <td>7 1/8-7 3/8</td>
      <td>7 3/8-7 5/8</td>
      <td>7 5/8-7 7/8</td>
      <td>7 7/8-8 1/8</td>
      <td>8 1/8-8 3/8</td>
    </tr>
  </table>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">WOMEN'S</td>
      <td>L8</td>
      <td>XL9</td>
      <td>2XL 10</td>
    </tr>
    <tr>
      <td class="title3">HAND SIZE</td>
      <td>7 5/8-7 7/8</td>
      <td>7 7/8-8 1/8</td>
      <td>8 1/8-8 3/8</td>
    </tr>
  </table>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">YOUTH</td>
      <td>Y2KS</td>
      <td>YXS</td>
      <td>YS</td>
      <td>YM</td>
      <td>YL</td>
    </tr>
    <tr>
      <td class="title3">HAND SIZE</td>
      <td>5-5 1/8</td>
      <td>5 1/8-5 3/8</td>
      <td>5 3/8-5 5/8</td>
      <td>5 5/8-5 3/4</td>
      <td>6-6 1/4</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
