<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>Kabuto Cruiser Helmet Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'kabuto/brand_logo.jpg' ?>" alt="Kabuto" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'kabuto/helmet.jpg' ?>" alt="Cruiser Helmet Sizes" /> </div>
  <h1>Size Measurement</h1>
  <p>For best results use a tape measure keeping it level, measure the widest point of your head, approximately 1&quot; above your eyebrows</p>
  <div class='fox-gloves-table-header'>Cruiser Helmet Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens</td>
      <td>XS</td>
      <td>S</td>
      <td>M</td>
      <td>L</td>
      <td>XL</td>
      <td>2XL</td>
    </tr>
    <tr>
      <td class="title3">HELMET  SIZE</td>
      <td>6 5/8-6 3/4</td>
      <td>6 7/8-7</td>
      <td>7 1/8-7 3/4</td>
      <td>7 3/8-7 1/2</td>
      <td>7 5/8-7 3/4</td>
      <td>7 7/8-8</td>
    </tr>
    <tr>
      <td class="title3">INCHES</td>
      <td>20.50-21.25</td>
      <td>21.25-22.00</td>
      <td>22.00-23.00</td>
      <td>23.00-23.75</td>
      <td>24.00-24.50</td>
      <td>24.50-25.25</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
