<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'speed_strength'; // folder name
$default = false;
?>
<div class="fox-gloves">
	<h1>Speed &amp; Strength Gloves Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.png' ?>" alt="Speed and Strength" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/glove_size.png' ?>" alt="Glove Sizes" />
	</div>

	<h1>Glove Size</h1>

	<p>Measurement should be at the widest point of your palm.</p>

	<div class='fox-gloves-table-header'>Glove Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">GLOVE SIZE</td>
			<td>XS</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
		</tr>
		<tr>
			<td class="title3">PALM SIZE</td>
			<td>2 1/4-2 5/8</td>
			<td>2 5/8-3 1/4</td>
			<td>3 1/4-3 5/8</td>
			<td>3 5/8-4 1/4</td>
			<td>4 1/4-4 5/8</td>
			<td>4 5/8-5 1/4</td>
		</tr>
	</table>
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>