<?php
$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;
$brand = 'venture'; // folder name
$default = false;
?>
<div class="fox-gloves">
  <h1>Venture Offroad Glove Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.png' ?>" alt="Venture" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . $brand . '/glove_size.png' ?>" alt="Glove Sizes" /> </div>
  <h1>Size Measurement</h1>
  <p>Measure around the hand at the fullest point excluding the thumb. Use chart to determine size.</p>
  <div class='fox-gloves-table-header'>Offroad Glove Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
		<td class="title2">Mens</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
    </tr>
    <tr>
		<td class="title3">glove size</td>
		<td>S</td>
		<td>M</td>
		<td>L</td>
		<td>XL</td>
		<td>2XL</td>
		<td>3XL</td>
    </tr>
	<tr>
		<td class="title3">Inches</td>
		<td>8-8.5</td>
		<td>9-9.5</td>
		<td>10-10.5</td>
		<td>11-11.5</td>
		<td>12-12.5</td>
		<td>13-13.5</td>
    </tr>    
  </table>
  
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
