<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'shift'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Shift Hoody Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.png' ?>" alt="Shift" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/jersey.jpg' ?>" alt="Hoody Sizes" />
	</div>
	
	<h1>Description</h1>

	<p>Hoodys will run slightly bigger for a good confortable and unrestricted fit.</p>
	
	<h1>Sleeve</h1>

	<p>With elbow slightly bent measure from the center behind the neck, over the point of the shoulder, around the elbow and down to the wrist.</p>
	
	<h1>Chest</h1>

	<p>Measure around the broadest part of the chest 1-2 below the arm pits.</p>

	<div class='fox-gloves-table-header'>Hoody Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">SIZE</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
			<td>3XL</td>
		</tr>
		<tr>
			<td class="title3">CHEST</td>
			<td>33-35</td>
			<td>36-39</td>
			<td>40-42</td>
			<td>43-46</td>
			<td>47-50</td>
			<td>50-52</td>
		</tr>
		<tr>
		<td class="title3">SLEEVE</td>
			<td>32-33</td>
			<td>33-34</td>
			<td>34-35</td>
			<td>35-36</td>
			<td>36-37</td>
			<td>37-38</td>
		</tr>
			<td class="title3">HEIGHT</td>
			<td>5'6-5'10</td>
			<td>5'10-6</td>
			<td>6-6'2</td>
			<td>6'1-6'3</td>
			<td>6'1-6'3</td>
			<td>6'3-6'4</td>
		</tr>
	</table>	
	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit.</p>

</div>