<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

$brand = 'nelson-rigg'; // folder name
$default = true;
?>
<div class="fox-gloves">
	<h1>Nelson-Rigg Men's Rain Pants Sizing Chart</h1>

	<div class="brand_logo"><img src="<?php echo $baseMediaUrl . $brand . '/brand_logo.jpg' ?>" alt="nelson-rigg" /></div>

	<div style="text-align:center;">
		<img src="<?php echo $baseMediaUrl . ($default == true ? 'default' : $brand) . '/pants.jpg' ?>" alt="Pants Sizes" />
	</div>

	<h1>INSEAM</h1>

	<p>Measure down from the crotch to the top of the ankle bone.</p>
	
	<h1>WAIST</h1>

	<p>Measure about 1 inch below top of pelvic bone.</p>

	<div class='fox-gloves-table-header'>Pants Sizing Chart</div>

	<table class="sizing_chart">
		<tr class="title1">
			<td class="title2">MEN'S</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td class="title3">PANT SIZE</td>
			<td>S</td>
			<td>M</td>
			<td>L</td>
			<td>XL</td>
			<td>2XL</td>
			<td>3XL</td>
			<td>4XL</td>
		</tr>
		<tr>
			<td class="title3">WAIST RELAXED</td>
			<td>20</td>
			<td>26</td>
			<td>29</td>
			<td>32</td>
			<td>35</td>
			<td>37</td>
			<td>42</td>
		</tr>
		<tr>
			<td class="title3">WAIST STRETCHED>/td>
			<td>40</td>
			<td>46</td>
			<td>49</td>
			<td>52</td>
			<td>55</td>
			<td>57</td>
			<td>60</td>
		</tr>
		<tr>
			<td class="title3">INSEAM</td>
			<td>30</td>
			<td>30.5</td>
			<td>31</td>
			<td>31.5</td>
			<td>32</td>
			<td>33</td>
			<td>33.5</td>
		</tr>
	</table>

	
	<p>* Disclaimer: Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>

</div>