<div class="wsqps wholesale">
	<div id="ariPartStream" lang="en">
		<div id="ariHotSpotToolTipWrapper" class="ariToolTipBase" style="position: fixed; display: none; z-index: 10000; padding: 0px 0px 0px 37px; ">
			<img id="ariHotSpotToolTipLeftArrow" style="position: fixed;" src="//partstream.arinet.com/Content/Images/Angle_Left.png" />
			<img id="ariHotSpotToolTipTopArrow" style="position: fixed; display: none;" src="//partstream.arinet.com/Content/Images/Angle_Top.png"  />
			<div id="ariHotSpotToolTip" style="border: solid 1px black; background-color: White; padding: 5px 5px 5px 5px; width: 300px;">
				<div id="ariHotSpotToolTipTitle" class="ariToolTipTitle" style="margin: 0px; border-width: 0px; text-align: center;">
						<span id="ariHotSpotBrandName"></span><br />
					<span id="ariHotSpotPartDesc"></span>
				</div>
				<div id="ariHotSpotToolTipImage" data-zoom-level="2" data-zoom-width="580"
					style="float: left; padding: 10px 5px 0px 0px; width: 150px; height: 150px; margin: 0px; border-width: 0px; text-align: center;">
					<div class="ari_partImage_thumbnail_loading" style="display:none; float: left; max-width:140px;max-height:110px;"></div>
					<img src="//partstream.arinet.com/Content/Images/Angle_Top.png" style="max-width:140px; max-height:110px;" alt=""/>
					<div class="ariHotSpotToolTipPartImageDisclaimer" style="display:none;width:140px; max-height:30px; font-weight:bold; font-size:x-small; text-align: center;"><span>Image may not be an exact representation</span></div>
				</div>
				<div id="ariHotSpotToolTipInfo" style="float: left; padding-top: 10px; text-align: right; margin: 0px; border-width: 0px;">
					<div style="text-align: right; padding-bottom: 5px;  margin: 0px; border-width: 0px;">
						<span class="ariToolTipPartNumber">
							<span id="ariHotSpotToolTipPartNumberLabel">Part Number:</span>
							<span id="ariHotSpotToolTipPartNumber"></span>
						</span>
					</div>
					<div style="text-align: right; padding-bottom: 5px; text-align: right; margin: 0px; border-width: 0px;">
						<span class="ariToolTipPrice">
							<span id="ariHotSpotToolTipPriceLabel">Price:</span>
							<span id="ariHotSpotToolTipPrice"></span>
						</span>
					</div>
					<div style="text-align: right; padding-bottom: 5px; text-align: right; margin: 0px; border-width: 0px;">
						<span class="ariToolTipMSRP">
							<span id="ariHotSpotToolTipMSRPLabel">MSRP:</span>
							<span id="ariHotSpotToolTipMSRP"></span>
						</span>
					</div>
					<div style="text-align: right;  padding-bottom: 5px; text-align: right; margin: 0px; border-width: 0px;">
						<span id="ariHotSpotToolTipQtyLabel">Quantity:</span>
						<input type="text" class="ariHotSpotToolTipQty" style="width: 30px; padding: 0px;" />
						<div style="clear: both"></div>
					</div>
					<div id="ariHotSpotToolTipBtn" style="text-align: right;"></div>
				</div>
				<div style="clear: both; margin: 0px; border-width: 0px;"></div>
			</div>
			<img id="ariHotSpotToolTipRightArrow" style="position: fixed; display: none;" src="//partstream.arinet.com/Content/Images/Angle_Right.png" />
			<img id="ariHotSpotToolTipBottomArrow" style="position: fixed; display: none;" src="//partstream.arinet.com/Content/Images/Angle_Bottom.png" />
		</div>
		<div id="ariSupersesionToolTipWrapper" class="ariToolTipBase" style="position: fixed; display: none; z-index: 100; padding: 0px 0px 0px 37px; ">
			<img id="ariSupersesionToolTipLeftArrow" style="position: fixed;" src="//partstream.arinet.com/Content/Images/Angle_Left.png" />
			<img id="ariSupersesionToolTipTopArrow" style="position: fixed; display: none;" src="//partstream.arinet.com/Content/Images/Angle_Top.png" />
			<div id="ariSupersesionToolTip" style="border: solid 1px black; background-color: White; padding: 5px 10px 5px 10px; width: 220px;">
				<div id="ariSupersesionToolTipTitle" class="ariSupersesionToolTipTitleClass">This is the most current part for this model.</div>
				<div id="ariSupersesionToolTipInfo" style="text-align: left; margin: 15px 10px; border-width: 0px;">
					<div id="ariSupersesionToolTipLabel" class="ariSupersesionToolTipPartLabelClass">Previous part number</div>
					<div class="ariSupersesionToolTipPartInfoClass" style="padding: 4px; margin-top: 4px;">
						<span id="ariSupersesionToolTipPartNumber">.</span>
						<span id="ariSupersesionToolTipPartDescription">,</span>
					</div>
				</div>
				<div style="clear: both; margin: 0px; border-width: 0px;"></div>
			</div>
			<img id="ariSupersesionToolTipRightArrow" style="position: fixed; display: none;" src="//partstream.arinet.com/Content/Images/Angle_Right.png" />
			<img id="ariSupersesionToolTipBottomArrow" style="position: fixed; display: none;" src="//partstream.arinet.com/Content/Images/Angle_Bottom.png" />
		</div>
		<div id="ariSearchSupersesionToolTipWrapper" class="ariToolTipBase" style="position: fixed; display: none; z-index: 100; padding: 0px 0px 0px 37px; ">
			<img id="ariSearchSupersesionToolTipLeftArrow" style="position: fixed;" src="//partstream.arinet.com/Content/Images/Angle_Left.png" />
			<img id="ariSearchSupersesionToolTipTopArrow" style="position: fixed; display: none;" src="//partstream.arinet.com/Content/Images/Angle_Top.png" />
			<div id="ariSearchSupersesionToolTip" style="border: solid 1px black; background-color: White; padding: 5px 10px 5px 10px; width: 220px;">
				<div id="ariSearchSupersesionToolTipTitle" class="ariSupersesionToolTipTitleClass">A newer part has replaced this item.</div>
				<div id="ariSearchSupersesionToolTipInfo" style="text-align: left; margin: 15px 10px; border-width: 0px;">
					<div id="ariSearchSupersesionToolTipLabel" class="ariSupersesionToolTipPartLabelClass">The latest part that replaces this item is:</div>
					<div class="ariSupersesionToolTipPartInfoClass" style="padding: 4px; margin-top: 4px;">
						<span id="ariSearchSupersesionToolTipPartNumber">.</span>
						<span id="ariSearchSupersesionToolTipPartDescription">,</span>
						<div id="ariSearchSupersesionToolTipPartInfoLoading" class='ari_loading'></div>
					</div>
				</div>
				<div style="clear: both; margin: 0px; border-width: 0px;"></div>
			</div>
			<img id="ariSearchSupersesionToolTipRightArrow" style="position: fixed; display: none;" src="//partstream.arinet.com/Content/Images/Angle_Right.png" />
			<img id="ariSearchSupersesionToolTipBottomArrow" style="position: fixed; display: none;" src="//partstream.arinet.com/Content/Images/Angle_Bottom.png" />
		</div>
		<div id="ariControlPanel" style="text-align: right;float:right;">
			<div id="ariDefaultLanguage" style="display:none;" value="en"></div>
			<div id="ariDefaultRegion" style="display:none;" value="US"></div>
		</div>
		<div style="clear: both;"></div>
		<div id="ariPartSelectPanel">
			<div id="ariRightSide">
				<div id="ariSearchLabel" class="ariMainTitle ariSearchBlock ariImageOverride" style="padding-left: 10px;">
					Quick Part Search:
				</div>
				<div class="ariHR"></div>
				<div class="ariSearchBlock">
					<div style="padding-left: 10px;">
						<div class='ariSearchBrandDDLDiv'>
						<div class="ariMainLabel">Select:</div>
						<div class="">
							<select id="arisearch_brands" class="ariInputs">
								<option value="0">-- Brands --</option>
								<option value="BRP">Can-Am (Bombardier)</option>
								<option value="HOM">Honda</option>
								<option value="HONPE">Honda Power Equipment</option>
								<option value="KUS">Kawasaki</option>
								<option value="POL">Polaris</option>
								<option value="BRP_SEA">Sea-Doo</option>
								<option value="SUZ">Suzuki Motor of America, Inc</option>
								<option value="VIC">Victory</option>
								<option value="YAM">Yamaha</option>
							</select>
						</div>
						</div>
						<div class="ariMainLabel">Model:</div>
						<div class="">
							<input type="text" id="arisearch_txtModel" class="ariInputs" />
						</div>
						<div class="ariMainLabel">Part:</div>
						<div class="">
							<input type="text" id="arisearch_txtSearch" class="ariInputs" />
						</div>
						<div class="ariSearchButtonWidth">
							<input value="Search" type="button" id="arisearch_btnLookup" class="ariImageOverride" />
						</div>
					</div>
				</div>
			</div>
			<div class="ariClear"></div>
		</div>
		<div id="ariSearchPanel" style="display:none;"></div>
		<div id="ariDetailsPanel" style="display:none;"></div>
		<div id="ariAssemblyPagePanel" style="display:none;"></div>
		<div class="ariSpacer"></div>
	</div>
</div>


<script type="text/javascript">

	var ariPartStreamUrl = '//partstream.arinet.com/Parts/Script?arik=9oiOWqDlvNLyUXT4Qtun&{aricookie}ariv=' + encodeURIComponent(location.href) + '';

	function ARIReadCookie(name) {
		if (document.cookie && document.cookie != '') {
			var cs = document.cookie.split(';'), cv = '';
			for (var i = 0; i < cs.length; i++) {
				c = cs[i].replace(/^\s*/, '').replace(/\s*$/, '');
				if (c.substring(0, name.length + 1).toLowerCase() == (name.toLowerCase() + '=')) {
					cv = decodeURIComponent(c.substring(name.length + 1));
					break;
				}
			}
			return cv.replace('&', 'ariamp');
		} else {
			return '';
		}
	}

	var cdata = ARIReadCookie('ARIPartStream');
	if(cdata != '') {
		ariPartStreamUrl = ariPartStreamUrl.replace('{aricookie}', 'aric=' + cdata + '&')
	} else {
		ariPartStreamUrl = ariPartStreamUrl.replace('{aricookie}', '')
	}


	// Global Variables
	var ariStreamEndpoint = '//partstream.arinet.com';
	var arik = '9oiOWqDlvNLyUXT4Qtun';
	var languageCode = 'en-US';
	var defaultLanguageCode = 'en';
	var ari_cartWindowHeight = '400';
	var ari_cartWindowWidth = '800';
	var ari_cartWindowTarget = '_self';
	var jsAddToCart = 'car.addToCart';

	var selectText = 'Select';
	// Gloabal Urls
	var actionUrl_Parts_GetAssembly = '/Parts/GetAssembly';
	var actionUrl_Parts_GetDetail = '/Parts/GetDetails';
	var actionUrl_Search_Index = '/Search';
	var imageUrl_Tree_Gear = '/Scripts/jsTree/themes/classic/gear.png';
	var imageUrl_Spinner = '/Scripts/jsTree/themes/classic/throbber.gif';
	var imageUrl_Down_Arrow = '/Content/Images/down-arrow.png';
	var imageUrl_Magnify = '/Content/Images/magGlass.png';
	var hotSpotToolTip_MultiPartMessage = 'There is more than one part available.  Please view list below.';

	var defaultZoomLevel = 1;
	var minZoomLevel = -1;
	var maxZoomLevel = 5;
	var defaultBrandCode = '';
	var defaultAssemblyName = '';

	var autoCompleteEnabled = true;
	var autoCompleteAcrossBrandsEnabled = false;

	var initializeFunctions = [];

	// Set defaults
	var defaultSearchBrandCode = '';
	var defaultModelSearchText = '';
	var defaultPartSearchText = '';

</script>

<!-- this loads PartStream stuff right here -->
<script src="<?php echo $this->getSkinUrl('vk_wholesale/js/partslookup/partstream.js') ?>" type="text/javascript"></script>

<script type="text/javascript">

	var initializeSearchJS = function () {
		ARI.PartStream.Main.setInitialSearchValues(defaultSearchBrandCode, defaultModelSearchText, defaultPartSearchText);
		ARI.PartStream.Main.init();
		ARI.PartStream.AutoCompleteHeaderText = 'Recommended Searches';
/**
		// Initialize Cart Properties
		// REVIEW: cartWindowProperties can be NULL
		var cartwindowTarget = '_self';
		var cartwindowWidth = '800';
		var cartwindowHeight = '400';
		var langCode = 'en';
		ARI.PartStream.Cart.setCartWindowProperties(cartwindowTarget, cartwindowWidth, cartwindowHeight, langCode);
/**/
	};

	if ((typeof ARI == "undefined") ||
	(typeof ARI.PartStream == "undefined") ||
	(typeof ARI.PartStream.Main == "undefined") ||
	(typeof ARI.PartStream.Cart == "undefined")) {
		initializeFunctions.push(initializeSearchJS);
	} else {
		initializeSearchJS();
	}

	var initializeDropDownJS = function () {
		ARI.PartStream.Dropdown.Navigation.init();
	}

	if ((typeof ARI == "undefined") ||
		(typeof ARI.PartStream == "undefined") ||
		(typeof ARI.PartStream.Dropdown == "undefined") ||
		(typeof ARI.PartStream.Dropdown.Navigation == "undefined")) {
		initializeFunctions.push(initializeDropDownJS);
	} else initializeDropDownJS();

	var initializeSideBySideJS = function () {
		ARI.PartStream.init();
	};

	if ((typeof ARI == "undefined") ||
		(typeof ARI.PartStream == "undefined")) {
		initializeFunctions.push(initializeSideBySideJS);
	} else initializeSideBySideJS();

</script>

<script type="text/javascript">

var partsLookup = new PartsLookup();
partsLookup.init({
	addToCartURL: '<?php echo $this->getUrl('arioem/cart/add') ?>'.replace('http:', location.protocol),
	assemblyPageBaseUrl: '<?php echo $this->getUrl('', array('_direct' => 'oem-part.html')) ?>'
});

ARI.PartStream.Cart.PostSkuQty = partsLookup.addToCart.bind(partsLookup);

</script>

 <!-- overriding the default stuff -->
<script src="<?php echo $this->getSkinUrl('vk_wholesale/js/partslookup/postload.js') ?>" type="text/javascript"></script>
