<?php ?>

<div class="contest-form-wrapper">

    <div class="contest-form-left">
        <img src="<?php echo $this->getSkinUrl('images/contest/contest-giveaway-gopro.jpg'); ?>" alt="" />

        <div class="contest-gopro-spec">
            Enter to win a GoPro Hero4 Session and capture every curve, every summit and all that riding action in crystal-clear 1080p and premium still images.
        </div>

        <div class="contest-instructions">Simply fill out your contact information for future promo's and discounts. And for a second chance to WIN like us on Facebook!<br>
        Must be a valid email address to win.        </div>

        <button type="submit" class="terms-conditions-btn" >Click here for terms and conditions.</button>
    </div>
    <div class="contest-form-right">
        <!--Begin CTCT Sign-Up Form-->
        <!-- EFD 1.0.0 [Tue Nov 17 19:06:23 EST 2015] -->
        <link rel='stylesheet' type='text/css' href='https://static.ctctcdn.com/h/contacts-embedded-signup-assets/1.0.2/css/signup-form.css'>
        <div class="ctct-embed-signup" style="font: 16px Helvetica Neue, Arial, sans-serif; font: 1rem Helvetica Neue, Arial, sans-serif; line-height: 1.5; -webkit-font-smoothing: antialiased;">
            <div class="contest-form-conent-wrapper" style="color:#5b5b5b; background-color:#e8e8e8; border-radius:5px;">
                <span id="success_message" style="display:none;">
                    <div style="text-align:center;">Thanks for signing up!</div>
                </span>
                <form data-id="embedded_signup:form" class="ctct-custom-form Form" name="embedded_signup" method="POST" action="https://visitor2.constantcontact.com/api/signup">
                    <h2 style="margin:0;">ENTER TO WIN A GOPRO HERO4 SESSION!</h2>
                    <p>Simply fill out the form below to enter. Double your chances of winning by liking us on Facebook for a second entry!</p>
                    <!-- The following code must be included to ensure your sign-up form works properly. -->
                    <input data-id="ca:input" name="ca" value="a7c1bd2a-aa4f-4b95-b851-410c9ff50f95" type="hidden">
                    <input data-id="list:input" name="list" value="1343531348" type="hidden">
                    <input data-id="source:input" name="source" value="EFD" type="hidden">
                    <input data-id="required:input" name="required" value="list,email,first_name,last_name" type="hidden">
                    <input data-id="url:input" name="url" value="" type="hidden">
                    <p data-id="Email Address:p" ><label data-id="Email Address:label" data-name="email" class="ctct-form-required">Email Address</label> <input data-id="Email Address:input" name="email" value="" maxlength="80" type="text"></p>
                    <p data-id="First Name:p" ><label class="ctct-form-required" data-id="First Name:label" data-name="first_name">First Name</label> <input data-id="First Name:input" name="first_name" value="" maxlength="50" type="text"></p>
                    <p data-id="Last Name:p" ><label class="ctct-form-required" data-id="Last Name:label" data-name="last_name">Last Name</label> <input data-id="Last Name:input" name="last_name" value="" maxlength="50" type="text"></p>
                    <p data-id="Phone Number:p" ><label data-id="Phone Number:label" data-name="phone">Phone Number</label> <input data-id="Phone Number:input" name="phone" value="" maxlength="50" type="text"></p>
                    <p data-id="Zip Code:p" ><label data-id="Zip Code:label" data-name="address_postal_code"  class="ctct-form-required">Zip Code</label> <input data-id="Zip Code:input" name="address_postal_code" value="" maxlength="50" type="text"></p>
                    <p data-id="Mandatory Info:p" ><label class="ctct-form-required">Mandatory Info needed to win!</label></p>
                    <button type="submit" class="Button ctct-button Button--block Button-secondary" data-enabled="enabled">Sign Up</button>
                    <div><p class="ctct-form-footer">By submitting this form, you are granting: Temecula Motorsports, Inc.,  permission to email you. You may unsubscribe via the link found at the bottom of every email.  (See our <a href="http://www.constantcontact.com/legal/privacy-statement" target="_blank">Email Privacy Policy</a> for details.) Emails are serviced by Constant Contact.</p></div>
                </form>
            </div>
        </div>

        <div class="contest-rules-wrap">
            <div class="contest-rules-launcher">OFFICIAL CONTEST RULES</div>
            <div class="contest-rules-verbage">
                <p>
                    <strong>Official Contest Rules</strong>
                </p>
                <p>
                    TMSParts.com's Monthly Giveaway Rules - "NO PURCHASE NECESSARY!"
                </p>
                <p>
                    <strong>TO BE ELIGIBLE</strong>
                    Only legal residents of the United States, that are 18 years of age or older with a valid email address and have lawful access to the internet are eligible to enter TMSParts.com's monthly giveaways (giveway). By entering the giveaway the participant will be opted into TMSParts.com's email marketing as a member of TMSParts.com's. Participants must remain a member of TMSParts.com the full length of the contest to be eligible at the time of the drawing to win. Employees of TMSParts.com or (Temecula Motorsports Inc.) its affiliated companies, subsidiaries, retailers, suppliers, vendors, sales representatives, distributors, advertising agencies, promotional suppliers, and their parent companies, agents, officers, directors, and the members of the immediate families and/or persons living in the same household as such individuals, of each of the foregoing, are not eligible to enter the contest giveaways. 
                </p>
                <p>
                    <strong>HOW TO ENTER: Winner Notification</strong>
                </p>
                <p>
                    Facebook Giveaway -Simply fill out your contact information for future promo's and discounts. And for a second chance to WIN like us on Facebook!
                    Must be a valid email address to win.</p>
                <p>
                    <strong>WINNER NOTIFICATION:</strong>
                </p>

                <p>
                    Winners will be selected in a random drawing on or before the end of the corresponding giveaway month. Odds of winning depends on the number of eligible entries received. The winner will be notified by email to the email address provided via entry form. If a potential winner cannot be reached at the email address provided and does not respond to TMSParts.com within five (5) days from TMSParts.com first attempt to contact him/her, or if he/she is found to be ineligible, or if he/she cannot or does not otherwise comply with these Official Rules, an alternate winner will be selected by random drawing. The prize may not be substituted, and the winner is not entitled to receive any additional or alternate compensation.
                </p>
            </div>

        </div>
    </div>

    <div class="term-conditions-holder" style="display: none;">
        <div class="terms-conditions-title">Terms and Conditions</div>
        <div class="terms-conditions-content">
            <?php echo Mage::getModel('cms/block')->load('gopro-terms-conditions')->getContent(); ?>
        </div>
    </div>

    <div class="crystal"></div>
</div>
<script type='text/javascript'>
    var localizedErrMap = {};
    localizedErrMap['required'] = 'This field is required.';
    localizedErrMap['ca'] = 'An unexpected error occurred while attempting to send email.';
    localizedErrMap['email'] = 'Please enter your email address in name@email.com format.';
    localizedErrMap['birthday'] = 'Please enter birthday in MM/DD format.';
    localizedErrMap['anniversary'] = 'Please enter anniversary in MM/DD/YYYY format.';
    localizedErrMap['custom_date'] = 'Please enter this date in MM/DD/YYYY format.';
    localizedErrMap['list'] = 'Please select at least one email list.';
    localizedErrMap['generic'] = 'This field is invalid.';
    localizedErrMap['shared'] = 'Sorry, we could not complete your sign-up. Please contact us to resolve this.';
    localizedErrMap['state_mismatch'] = 'Mismatched State/Province and Country.';
    localizedErrMap['state_province'] = 'Select a state/province';
    localizedErrMap['selectcountry'] = 'Select a country';
    var postURL = 'https://visitor2.constantcontact.com/api/signup';
</script>
<script type='text/javascript' src='https://static.ctctcdn.com/h/contacts-embedded-signup-assets/1.0.2/js/signup-form.js'></script>
<!--End CTCT Sign-Up Form-->

<script type="text/javascript">
    jQuery(document).ready(function () {
        jQuery(".contest-rules-launcher").click(function () {

            if (jQuery(".contest-rules-verbage").is(":visible")) {
                jQuery(this).css({
                    backgroundImage: "url(<?php echo $this->getSkinUrl('images/contest/dropdown-arrow-down.jpg'); ?>)"
                });
            } else {
                jQuery(this).css({
                    backgroundImage: "url(<?php echo $this->getSkinUrl('images/contest/dropdown-arrow-right.jpg'); ?>)"
                });
            }
            jQuery(".contest-rules-verbage").slideToggle("fast");
        });

        jQuery(".terms-conditions-btn").click(function () {
            jQuery("body").append("<div id='cart-overlay' />");
            jQuery("body").append("<div id='contest-overlay-content' />");
            jQuery("#contest-overlay-content").append('<div class="close-floating-cart-wrap"><a href="#" onclick="overlay.hide(event);" class="close-floating-cart">x</a></div>');
            jQuery("#contest-overlay-content").append('<div class="contest-terms-mainwrap" />');
            jQuery(".contest-terms-mainwrap").html(jQuery(".term-conditions-holder").html());

            jQuery("#contest-overlay-content").css({
                marginLeft: '-' + (jQuery("#contest-overlay-content").width() / 2) + 'px'
            });
            
            jQuery("#cart-overlay").click(function () {
                overlay.hide();
            });
        });


        overlay = {
            hide: function (evt) {
                jQuery("#contest-overlay-content").fadeOut("fast", function () {
                    jQuery("#contest-overlay-content").remove();
                    jQuery("#cart-overlay").fadeOut("fast", function () {
                        jQuery("#cart-overlay").remove();
                    });

                });
            }
        }
    });
</script>