<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>Mobile Street Pant Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'mobile/brand_logo.jpg' ?>" alt="Mobile" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'mobile/jersey.jpg' ?>" alt="Street Pant Sizes" /> </div>
  <h1>Size Measurement</h1>
  <p>Waist: Measure about 1 inch below top of pelvic bone.</p>
  <p>Inseam: Measure down from the crotch to the top of the ankle bone.</p>
  <div class='fox-gloves-table-header'>Street Pant Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens</td>
      <td>XS</td>
      <td>S</td>
      <td>M</td>
      <td>L</td>
      <td>XL</td>
      <td>2XL</td>
      <td>3XL</td>
      <td>4XL</td>
    </tr>
    <tr>
      <td class="title3">WAIST</td>
      <td>26</td>
      <td>28-30</td>
      <td>32-34</td>
      <td>36-38</td>
      <td>40-42</td>
      <td>44</td>
      <td>47</td>
      <td>50</td>
    </tr>
    <tr>
      <td class="title3">INSEAM SHORT</td>
      <td>28</td>
      <td>28.5</td>
      <td>29.5</td>
      <td>30</td>
      <td>31</td>
      <td>31.5</td>
      <td>31.5</td>
      <td>31.5</td>
    </tr>
    <tr>
      <td class="title3">INSEAM REG.</td>
      <td>30</td>
      <td>30.5</td>
      <td>31.5</td>
      <td>32</td>
      <td>33</td>
      <td>33.5</td>
      <td>33.5</td>
      <td>33.5</td>
    </tr>
    <tr>
      <td class="title3">INSEAM LONG</td>
      <td>32</td>
      <td>32.5</td>
      <td>33.5</td>
      <td>34</td>
      <td>35</td>
      <td>35.5</td>
      <td>35.5</td>
      <td>35.5</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
