<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>Kawasaki Casual Hoody Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'kawasaki/brand_logo.jpg' ?>" alt="Kawasaki" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'kawasaki/jersey.jpg' ?>" alt="Glove Sizes" /> </div>
  <h1>Size Measurement</h1>
  <p>Hoodys will run slightly bigger for a good confortable and unrestricted fit.</p>
  <p>Sleeve:	With elbow slightly bent measure from the center behind					ehind the neck, over the point of the shoulder, around the elbow and down to the wrist. </p>
  <p> Chest:	Measure around the broadest part of the chest 1-2 below the arm pits. <br />
  </p>
  <div class='fox-gloves-table-header'>Casual Hoody Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens</td>
      <td>S</td>
      <td>M</td>
      <td>L</td>
      <td>XL</td>
      <td>2XL</td>
    </tr>
    <tr>
      <td class="title3">CHEST</td>
      <td>33-35
</td>
      <td>36-39
</td>
      <td>40-42
</td>
      <td>43-46
</td>
      <td>47-50
</td>
    </tr>
    <tr>
      <td class="title3">SLEEVE</td>
      <td>32-33
</td>
      <td>33-34
</td>
      <td>34-35
</td>
      <td>35-36
</td>
      <td>36-37
</td>
    </tr>
    <tr>
      <td class="title3">HEIGHT</td>
      <td>5'6-5'10
</td>
      <td>5'10-6
</td>
      <td>6-6'2
</td>
      <td>6'1-6'3
</td>
      <td>6'1-6'3
</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
