<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>Kawasaki Casual Short Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'kawasaki/brand_logo.jpg' ?>" alt="Kawasaki" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'kawasaki/pants.jpg' ?>" alt="Pant Sizes" /> </div>
  <h1>Size Measurement</h1>
  <p>Waist-Measure about 1 inch below top of pelvic bone.</p>
  <p>Inseam-Measure down from the crotch to the top of the ankle bone.<br />
  </p>
  <div class='fox-gloves-table-header'>Casual Short Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens</td>
      <td>28</td>
      <td>30</td>
      <td>32</td>
      <td>34</td>
      <td>36</td>
      <td>38</td>
    </tr>
    <tr>
      <td class="title3">WAIST</td>
      <td>27-29</td>
      <td>29-31</td>
      <td>31-33</td>
      <td>33-35</td>
      <td>35-37</td>
      <td>37-39</td>
    </tr>
    <tr>
      <td class="title3">INSEAM</td>
      <td>14.75</td>
      <td>14.75</td>
      <td>14.75</td>
      <td>14.75</td>
      <td>14.75</td>
      <td>14.75</td>
    </tr>
  </table>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Womens</td>
      <td>S 3/4</td>
      <td>M 5/6</td>
      <td>L 7/8</td>
      <td>XL 9/10</td>
    </tr>
    <tr>
      <td class="title3">WAIST</td>
      <td>29-31</td>
      <td>31-33</td>
      <td>33-35</td>
      <td>35-37</td>
    </tr>
    <tr>
      <td class="title3">INSEAM</td>
      <td>10</td>
      <td>10.5</td>
      <td>10.6</td>
      <td>11</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
