<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>Kawasaki H2<sup>O</sup> Footwear Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'kawasaki/brand_logo.jpg' ?>" alt="Kawasaki" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'kawasaki/boot.jpg' ?>" alt="Boot Sizes" /> </div>
  <h1>Size Measurement</h1>
  <div class='fox-gloves-table-header'>H2O Footwear Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td class="title3">USA</td>
      <td>5</td>
      <td>5.5</td>
      <td>6</td>
      <td>6.5</td>
      <td>7</td>
      <td>7.5</td>
      <td>8</td>
      <td>8.5</td>
      <td>9</td>
      <td>9.5</td>
      <td>10</td>
      <td>1.5</td>
      <td>11</td>
    </tr>
    <tr>
      <td class="title3">EU</td>
      <td>37.5</td>
      <td>38</td>
      <td>38.5</td>
      <td>39</td>
      <td>40</td>
      <td>40.5</td>
      <td>41</td>
      <td>42</td>
      <td>42.5</td>
      <td>43</td>
      <td>44</td>
      <td>44.5</td>
      <td>45</td>
    </tr>
    <tr>
      <td class="title3">UK</td>
      <td>4</td>
      <td>4.5</td>
      <td>5</td>
      <td>5.5</td>
      <td>6</td>
      <td>6.5</td>
      <td>7</td>
      <td>7.5</td>
      <td>8</td>
      <td>8.5</td>
      <td>9</td>
      <td>9.5</td>
      <td>10</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
