<?php

$baseMediaUrl = Mage::getBaseUrl('media') . DS . 'sizing_charts' . DS;

?>

<div class="fox-gloves">
  <h1>Kawasaki H2<sup>O</sup> Life Jacket Sizing Chart</h1>
  <div class="brand_logo"><img src="<?php echo $baseMediaUrl . 'kawasaki/brand_logo.jpg' ?>" alt="Kawasaki" /></div>
  <div style="text-align:center;"> <img src="<?php echo $baseMediaUrl . 'kawasaki/lifejacket.jpg' ?>" alt="Life Jacket Sizes" /> </div>
  <h1>Size Measurement</h1>
  <p>Chest: Measure around the broadest part of the chest, 1-2  inches below the arm pits.</p>
  <div class='fox-gloves-table-header'>H2O Life Jacket Sizing Chart</div>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Mens</td>
      <td>XS</td>
      <td>S</td>
      <td>M</td>
      <td>L</td>
      <td>XL</td>
      <td>2XL</td>
      <td>3XL</td>
    </tr>
    <tr>
      <td class="title3">CHEST SIZE</td>
      <td>33-35 </td>
      <td>35-37</td>
      <td>37-39</td>
      <td>39-41</td>
      <td>41-43</td>
      <td>43-45</td>
      <td>47-50</td>
    </tr>
  </table>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Womens</td>
      <td>XS</td>
      <td>S</td>
      <td>M</td>
      <td>L</td>
      <td>XL</td>
      <td>2XL</td>
    </tr>
    <tr>
      <td class="title3">CHEST SIZE</td>
      <td>30-33 </td>
      <td>33-37</td>
      <td>37-39</td>
      <td>39-41</td>
      <td>41-43</td>
      <td>43-45</td>
    </tr>
  </table>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Youth</td>
      <td>TEEN</td>
    </tr>
    <tr>
      <td class="title3">CHEST SIZE</td>
      <td>28-30</td>
    </tr>
  </table>
  <table class="sizing_chart">
    <tr class="title1">
      <td class="title2">Kids</td>
      <td>YOUTH</td>
      <td>CHILD</td>
      <td>INFANT</td>
    </tr>
    <tr>
      <td class="title3">WEIGHT</td>
      <td>50-90</td>
      <td>30-50</td>
      <td>0-30</td>
    </tr>
  </table>
  <p>** Sizing information is provided by the manufacturer and does not guarantee a perfect fit. Please use this chart as a guide only.</p>
</div>
